Muscovite C++ Framework: muscovite::qt::widgets::LatLonInput Class Reference
muscovite::qt::widgets::LatLonInput Class Reference
Coordinate input widget combining latitude and longitude spinboxes.
#include <spatial_widgets.hpp>
Signals
void coordinatesChanged (double _t1, double _t2)
Emitted when either coordinate changes.
void latitudeChanged (double _t1)
Emitted when latitude value changes.
void longitudeChanged (double _t1)
Emitted when longitude value changes.
void validityChanged (bool _t1)
Emitted when validity changes.
Public Member Functions
LatLonInput (const QString &label="Coordinates", QWidget *parent=nullptr)
std::pair< double, double > coordinates () const
Get both coordinates as a pair.
bool isValid () const
Check if current coordinates are valid.
double latitude () const
Get current latitude value.
double longitude () const
Get current longitude value.
void setCoordinates (double lat, double lon)
Set both coordinates from a pair.
void setEnabled (bool enabled)
Enable/disable coordinate inputs.
void setLatitude (double value)
Set latitude value.
void setLongitude (double value)
Set longitude value.
validation::ValidationResult validate () const
Get validation results for both coordinates.
Detailed Description
Coordinate input widget combining latitude and longitude spinboxes.
Features:
Two QDoubleSpinBox widgets (one per coordinate)
Built-in CoordinateValidator for range checking
Clear labeling: "Latitude" and "Longitude"
Automatic validation on value changes
Integration with validation framework
Layout: [ Latitude | spinbox ] [ Longitude | spinbox ]
Definition at line 118 of file spatial_widgets.hpp.
Constructor & Destructor Documentation
LatLonInput()
muscovite::qt::widgets::LatLonInput::LatLonInput (const QString & label = "Coordinates", QWidget * parent = nullptr) explicit
Definition at line 120 of file spatial_widgets.cpp.
Member Function Documentation
coordinates()
std::pair< double, double > muscovite::qt::widgets::LatLonInput::coordinates () const nodiscard
Get both coordinates as a pair.
Definition at line 192 of file spatial_widgets.cpp.
References latitude(), and longitude().
isValid()
bool muscovite::qt::widgets::LatLonInput::isValid () const nodiscard
Check if current coordinates are valid.
Both latitude and longitude must be within valid ranges.
Definition at line 203 of file spatial_widgets.cpp.
References latitude(), and longitude().
latitude()
double muscovite::qt::widgets::LatLonInput::latitude () const nodiscard
Get current latitude value.
Definition at line 172 of file spatial_widgets.cpp.
Referenced by coordinates(), isValid(), and validate().
longitude()
double muscovite::qt::widgets::LatLonInput::longitude () const nodiscard
Get current longitude value.
Definition at line 182 of file spatial_widgets.cpp.
Referenced by coordinates(), isValid(), and validate().
setCoordinates()
void muscovite::qt::widgets::LatLonInput::setCoordinates (double lat, double lon)
Set both coordinates from a pair.
Definition at line 197 of file spatial_widgets.cpp.
References setLatitude(), and setLongitude().
setEnabled()
void muscovite::qt::widgets::LatLonInput::setEnabled (bool enabled)
Enable/disable coordinate inputs.
Definition at line 225 of file spatial_widgets.cpp.
setLatitude()
void muscovite::qt::widgets::LatLonInput::setLatitude (double value)
Set latitude value.
Definition at line 177 of file spatial_widgets.cpp.
Referenced by setCoordinates().
setLongitude()
void muscovite::qt::widgets::LatLonInput::setLongitude (double value)
Set longitude value.
Definition at line 187 of file spatial_widgets.cpp.
Referenced by setCoordinates().
validate()
validation::ValidationResult muscovite::qt::widgets::LatLonInput::validate () const nodiscard
Get validation results for both coordinates.
Returns
ValidationResult with errors for invalid coordinates
Definition at line 208 of file spatial_widgets.cpp.
References latitude(), and longitude().
The documentation for this class was generated from the following files:
framework/qt/include/muscovite/qt/widgets/spatial_widgets.hpp
framework/qt/src/widgets/spatial_widgets.cpp