Muscovite C++ Framework: muscovite::dba::ConnectionPool Class Reference
muscovite::dba::ConnectionPool Class Reference
#include <connection_pool.hpp>
Public Member Functions
ConnectionPool (ConnectionPool &&) noexcept
ConnectionPool (const ConnectionPool &)=delete
auto acquire () -> std::expected< PooledConnection, Error< PoolError > >
auto acquire (std::chrono::milliseconds timeout) -> std::expected< PooledConnection, Error< PoolError > >
auto active_connections () const noexcept -> std::size_t
Get number of active (checked out) connections.
auto available_connections () const noexcept -> std::size_t
Get number of available (idle) connections.
auto max_connections () const noexcept -> std::size_t
Get maximum pool size.
ConnectionPool & operator= (ConnectionPool &&) noexcept
ConnectionPool & operator= (const ConnectionPool &)=delete
void shutdown ()
Shutdown the pool, closing all connections.
auto try_acquire () -> std::optional< PooledConnection >
Static Public Member Functions
static auto create (PoolConfig config) -> std::expected< ConnectionPool, Error< PoolError > >
Friends
class PooledConnection
Detailed Description
Thread-safe PostgreSQL connection pool.
Usage:
auto pool = ConnectionPool::create(config).value();
{
    auto conn = pool.acquire().value();
    pqxx::work tx{conn.get()};
    tx.exec("SELECT 1");
    tx.commit();
} // Connection returns to pool
Definition at line 93 of file connection_pool.hpp.
Member Function Documentation
acquire() [1/2]
auto muscovite::dba::ConnectionPool::acquire () -> std::expected< PooledConnection, Error< PoolError > > nodiscard
Acquire a connection from the pool. Blocks until a connection is available.
Returns
Connection on success, Error on failure
Definition at line 332 of file connection_pool.cpp.
References acquire().
Referenced by muscovite::dba::TestTransactionFixture::TestTransactionFixture(), acquire(), acquire(), and muscovite::dba::execute().
acquire() [2/2]
auto muscovite::dba::ConnectionPool::acquire (std::chrono::milliseconds timeout) -> std::expected< PooledConnection, Error< PoolError > > nodiscard
Acquire a connection with timeout.
Parameters
timeout Maximum time to wait
Returns
Connection on success, Error on failure/timeout
Definition at line 340 of file connection_pool.cpp.
References acquire().
active_connections()
auto muscovite::dba::ConnectionPool::active_connections () const -> std::size_t nodiscard noexcept
Get number of active (checked out) connections.
Definition at line 356 of file connection_pool.cpp.
References active_connections().
Referenced by active_connections().
available_connections()
auto muscovite::dba::ConnectionPool::available_connections () const -> std::size_t nodiscard noexcept
Get number of available (idle) connections.
Definition at line 360 of file connection_pool.cpp.
References available_connections().
Referenced by available_connections().
create()
auto muscovite::dba::ConnectionPool::create (PoolConfig config) -> std::expected< ConnectionPool, Error< PoolError > > static nodiscard
Create a new connection pool.
Parameters
config Pool configuration
Returns
Pool on success, Error on failure
Definition at line 295 of file connection_pool.cpp.
References create().
Referenced by create(), and muscovite::dba::ReadReplicaRouter::create().
max_connections()
auto muscovite::dba::ConnectionPool::max_connections () const -> std::size_t nodiscard noexcept
Get maximum pool size.
Definition at line 364 of file connection_pool.cpp.
References max_connections().
Referenced by max_connections().
shutdown()
void muscovite::dba::ConnectionPool::shutdown ()
Shutdown the pool, closing all connections.
Definition at line 368 of file connection_pool.cpp.
References shutdown().
Referenced by shutdown().
try_acquire()
auto muscovite::dba::ConnectionPool::try_acquire () -> std::optional< PooledConnection > nodiscard
Try to acquire a connection without blocking.
Returns
Connection if immediately available, nullopt otherwise
Definition at line 348 of file connection_pool.cpp.
References try_acquire().
Referenced by try_acquire().
Friends And Related Symbol Documentation
PooledConnection
friend class PooledConnection friend
Definition at line 135 of file connection_pool.hpp.
The documentation for this class was generated from the following files:
framework/dba/include/muscovite/dba/connection_pool.hpp
framework/dba/src/connection_pool.cpp