Muscovite C++ Framework: muscovite::types::strong_type_base< Derived > Class Template Reference
muscovite::types::strong_type_base< Derived > Class Template Reference
Public Member Functions
strong_type_base ()=default
Default constructor creates empty value.
strong_type_base (std::string_view value)
Construct with validation.
auto empty () const noexcept -> bool
Check if empty.
operator std::string_view () const noexcept
Implicit conversion to string_view for compatibility.
auto operator<=> (const strong_type_base &other) const noexcept=default
Three-way comparison.
auto operator== (const strong_type_base &other) const noexcept -> bool=default
Equality comparison.
auto value () const noexcept -> const std::string &
Get the underlying string value.
Static Public Member Functions
static auto from_trusted (std::string value) noexcept -> Derived
Construct from trusted source without validation.
Protected Attributes
std::string value_
Detailed Description
template<typename Derived>
class muscovite::types::strong_type_base< Derived >
Definition at line 58 of file strong_type_base.hpp.
Constructor & Destructor Documentation
strong_type_base()
template<typename Derived> muscovite::types::strong_type_base< Derived >::strong_type_base (std::string_view value) inline explicit
Construct with validation.
Parameters
value The string value to wrap
Exceptions
invalid_value_error if validation fails
Definition at line 71 of file strong_type_base.hpp.
References value().
Member Function Documentation
empty()
template<typename Derived> auto muscovite::types::strong_type_base< Derived >::empty () const -> bool inline nodiscard noexcept
Check if empty.
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/strong_type_base.hpp.
Definition at line 103 of file strong_type_base.hpp.
from_trusted()
template<typename Derived> auto muscovite::types::strong_type_base< Derived >::from_trusted (std::string value) -> Derived inline static nodiscard noexcept
Construct from trusted source without validation.
Parameters
value The string value (assumed valid)
Returns
Constructed object
Use this when loading from a database where the CHECK constraint already guarantees validity, avoiding redundant validation.
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/strong_type_base.hpp.
Definition at line 86 of file strong_type_base.hpp.
References value().
operator std::string_view()
template<typename Derived> muscovite::types::strong_type_base< Derived >::operator std::string_view () const inline nodiscard noexcept
Implicit conversion to string_view for compatibility.
Definition at line 98 of file strong_type_base.hpp.
value()
template<typename Derived> auto muscovite::types::strong_type_base< Derived >::value () const -> const std::string & inline nodiscard noexcept
Get the underlying string value.
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/strong_type_base.hpp.
Definition at line 93 of file strong_type_base.hpp.
Referenced by strong_type_base(), and from_trusted().
Member Data Documentation
value_
template<typename Derived> std::string muscovite::types::strong_type_base< Derived >::value_ protected
Definition at line 114 of file strong_type_base.hpp.
The documentation for this class was generated from the following file:
framework/types/include/muscovite/types/strong_type_base.hpp