Muscovite C++ Framework: muscovite::types::NonEmptyString Class Reference
muscovite::types::NonEmptyString Class Reference
Public Member Functions
auto length () const noexcept -> std::size_t
Get length (character count).
strong_type_base ()=default
Default constructor creates empty value.
strong_type_base (std::string_view value)
Construct with validation.
auto trimmed () const -> std::string_view
Get trimmed version (whitespace removed from ends).
Public Member Functions inherited from muscovite::types::strong_type_base< NonEmptyString >
strong_type_base ()=default
Default constructor creates empty value.
auto empty () const noexcept -> bool
Check if empty.
operator std::string_view () const noexcept
Implicit conversion to string_view for compatibility.
auto operator<=> (const strong_type_base &other) const noexcept=default
Three-way comparison.
auto operator== (const strong_type_base &other) const noexcept -> bool=default
Equality comparison.
auto value () const noexcept -> const std::string &
Get the underlying string value.
Static Public Member Functions
static auto is_valid (std::string_view value) noexcept -> bool
Validate non-empty string.
static constexpr auto pattern () noexcept -> std::string_view
Validation description.
static constexpr auto type_name () noexcept -> std::string_view
Type name for error messages.
Static Public Member Functions inherited from muscovite::types::strong_type_base< NonEmptyString >
static auto from_trusted (std::string value) noexcept -> NonEmptyString
Construct from trusted source without validation.
Additional Inherited Members
Protected Attributes inherited from muscovite::types::strong_type_base< NonEmptyString >
std::string value_
Detailed Description
Definition at line 34 of file non_empty_string.hpp.
Member Function Documentation
is_valid()
auto muscovite::types::NonEmptyString::is_valid (std::string_view value) -> bool inline static nodiscard noexcept
Validate non-empty string.
Parameters
value String to validate
Returns
true if not empty and not whitespace-only
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/non_empty_string.hpp.
Definition at line 51 of file non_empty_string.hpp.
References muscovite::types::strong_type_base< NonEmptyString >::value().
length()
auto muscovite::types::NonEmptyString::length () const -> std::size_t inline nodiscard noexcept
Get length (character count).
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/non_empty_string.hpp.
Definition at line 67 of file non_empty_string.hpp.
pattern()
constexpr auto muscovite::types::NonEmptyString::pattern () -> std::string_view inline static nodiscard constexpr noexcept
Validation description.
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/non_empty_string.hpp.
Definition at line 44 of file non_empty_string.hpp.
References muscovite::types::strong_type_base< NonEmptyString >::operator std::string_view().
strong_type_base()
muscovite::types::strong_type_base< Derived >::strong_type_base (std::string_view value) inline explicit
Construct with validation.
Parameters
value The string value to wrap
Exceptions
invalid_value_error if validation fails
Definition at line 71 of file strong_type_base.hpp.
trimmed()
auto muscovite::types::NonEmptyString::trimmed () const -> std::string_view inline nodiscard
Get trimmed version (whitespace removed from ends).
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/non_empty_string.hpp.
Definition at line 59 of file non_empty_string.hpp.
References muscovite::types::strong_type_base< NonEmptyString >::operator std::string_view().
type_name()
constexpr auto muscovite::types::NonEmptyString::type_name () -> std::string_view inline static nodiscard constexpr noexcept
Type name for error messages.
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/non_empty_string.hpp.
Definition at line 39 of file non_empty_string.hpp.
References muscovite::types::strong_type_base< NonEmptyString >::operator std::string_view().
The documentation for this class was generated from the following file:
framework/types/include/muscovite/types/non_empty_string.hpp