Muscovite C++ Framework: muscovite::dba::TestTransactionFixture Class Reference
muscovite::dba::TestTransactionFixture Class Reference
#include <test_fixture.hpp>
Public Member Functions
TestTransactionFixture (ConnectionPool &pool)
TestTransactionFixture (const TestTransactionFixture &)=delete
TestTransactionFixture (pqxx::connection &connection)
TestTransactionFixture (TestTransactionFixture &&)=delete
~TestTransactionFixture ()
auto connection () -> pqxx::connection &
TestTransactionFixture & operator= (const TestTransactionFixture &)=delete
TestTransactionFixture & operator= (TestTransactionFixture &&)=delete
void release_savepoint (std::string_view name)
void rollback_to (std::string_view name)
void savepoint (std::string_view name)
auto transaction () -> pqxx::work &
auto transaction () const -> const pqxx::work &
Get read-only access to the transaction.
Detailed Description
Test fixture providing automatic transaction rollback for test isolation.
Purpose: Ensures each test runs in complete isolation by wrapping all database operations in a transaction that is unconditionally rolled back at the end.
Benefits:
Zero test data pollution between tests
No cleanup code required in tests
Tests can run in any order
Parallel test execution safe (if using separate connections)
Usage with doctest:
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <doctest/doctest.h>
#include <muscovite/dba/test_fixture.hpp>
SCENARIO("Patient CRUD operations") {
    GIVEN("a live database connection") {
        auto pool = ConnectionPool::create(std::getenv("MUSCOVITE_TEST_DB"));
        TestTransactionFixture fixture(pool);
        auto& txn = fixture.transaction();
        WHEN("inserting a new patient") {
            PatientRepository repo;
            auto patient = repo.insert(txn, create_test_patient());
            THEN("the patient has a valid id") {
                CHECK(patient.id() != boost::uuids::nil_uuid());
            }
        }
        // Fixture destructor rolls back - patient is NOT persisted
    }
}
Generated Test Pattern: The DBA test generator (dslgen/generators/cpp/dba/unified.rkt) uses this fixture automatically for all generated repository tests.
Definition at line 67 of file test_fixture.hpp.
Constructor & Destructor Documentation
TestTransactionFixture() [1/2]
muscovite::dba::TestTransactionFixture::TestTransactionFixture (ConnectionPool & pool) explicit
Construct fixture from connection pool
Parameters
pool Connection pool for acquiring test connection
Definition at line 15 of file test_fixture.cpp.
References muscovite::dba::ConnectionPool::acquire().
TestTransactionFixture() [2/2]
muscovite::dba::TestTransactionFixture::TestTransactionFixture (pqxx::connection & connection) explicit
Construct fixture from existing connection
Parameters
connection Active database connection (caller retains ownership)
Definition at line 28 of file test_fixture.cpp.
References connection().
~TestTransactionFixture()
muscovite::dba::TestTransactionFixture::~TestTransactionFixture ()
Destructor - ALWAYS rolls back the transaction This ensures test isolation regardless of test outcome.
Definition at line 34 of file test_fixture.cpp.
Member Function Documentation
connection()
auto muscovite::dba::TestTransactionFixture::connection () -> pqxx::connection & nodiscard
Get the underlying connection
Returns
Reference to the database connection
Definition at line 54 of file test_fixture.cpp.
Referenced by TestTransactionFixture().
release_savepoint()
void muscovite::dba::TestTransactionFixture::release_savepoint (std::string_view name)
Release a savepoint (allows partial commits within the test)
Parameters
name Savepoint name to release
Definition at line 66 of file test_fixture.cpp.
rollback_to()
void muscovite::dba::TestTransactionFixture::rollback_to (std::string_view name)
Rollback to a savepoint
Parameters
name Savepoint name to rollback to
Definition at line 62 of file test_fixture.cpp.
savepoint()
void muscovite::dba::TestTransactionFixture::savepoint (std::string_view name)
Create a savepoint for nested transaction simulation
Parameters
name Savepoint name (must be unique within transaction)
Definition at line 58 of file test_fixture.cpp.
transaction() [1/2]
auto muscovite::dba::TestTransactionFixture::transaction () -> pqxx::work & nodiscard
Get the transaction for test operations
Returns
Reference to the active pqxx::work transaction
Definition at line 46 of file test_fixture.cpp.
transaction() [2/2]
auto muscovite::dba::TestTransactionFixture::transaction () const -> const pqxx::work & nodiscard
Get read-only access to the transaction.
Definition at line 50 of file test_fixture.cpp.
The documentation for this class was generated from the following files:
framework/dba/include/muscovite/dba/test_fixture.hpp
framework/dba/src/test_fixture.cpp