Muscovite C++ Framework: muscovite::qt::AuthManager Class Reference
muscovite::qt::AuthManager Class Reference
Authentication manager for built-in username/password authentication.
#include <auth_manager.hpp>
Signals
void authStateChanged ()
Emitted when authentication state changes.
void errorOccurred (const QString &_t1)
Emitted when an error occurs.
void loggedOut ()
Emitted when logout completes.
void loginFailed (const QString &_t1)
Emitted when login fails.
void loginProgressChanged ()
Emitted when login progress changes.
void loginSucceeded (const Session &_t1)
Emitted when login succeeds.
void passwordChanged ()
Emitted when password change succeeds.
void passwordChangeFailed (const QString &_t1)
Emitted when password change fails.
void sessionExpired ()
Emitted when the session has expired.
void sessionExpiring (int _t1)
Emitted when the session is about to expire.
void tokenRefreshed ()
Emitted when token refresh succeeds.
void tokenRefreshFailed (const QString &_t1)
Emitted when token refresh fails.
Public Member Functions
AuthManager (AuthManager &&)=delete
AuthManager (const AuthManager &)=delete
QString accessToken () const
Get the current access token.
Q_SLOT void changePassword (const QString &currentPassword, const QString &newPassword)
Change the current user's password.
const AuthConfig & config () const
Get the current configuration.
void configure (const AuthConfig &config)
Configure the authentication manager.
QString displayName () const
Get the current display name.
QStringList groups () const
Get the current user's groups.
Q_INVOKABLE bool hasAllPrivileges (const QStringList &privileges) const
Check if the user has all specified privileges.
Q_INVOKABLE bool hasAnyPrivilege (const QStringList &privileges) const
Check if the user has any of the specified privileges.
Q_INVOKABLE bool hasPrivilege (const QString &privilege) const
Check if the user has a specific privilege.
Q_INVOKABLE bool isAdmin () const
Check if the user is an administrator.
bool isAuthenticated () const
Check if the user is currently authenticated.
Q_INVOKABLE bool isInGroup (const QString &group) const
Check if the user is in a specific group.
bool isLoginInProgress () const
Check if a login operation is in progress.
QString lastError () const
Get the last error message.
Q_SLOT void login (const QString &username, const QString &password)
Login with username and password.
Q_SLOT void logout ()
Logout and invalidate the current session.
Q_SLOT void logoutAll ()
Logout from all sessions.
AuthManager & operator= (AuthManager &&)=delete
AuthManager & operator= (const AuthManager &)=delete
QStringList privileges () const
Get the current user's privileges.
Q_SLOT void refreshToken ()
Refresh the access token.
std::optional< Session > session () const
Get the current session.
QString username () const
Get the current username.
Static Public Member Functions
static AuthManager & instance ()
Get singleton instance.
Properties
bool authenticated
Whether the user is currently authenticated.
QString displayName
Current user's display name.
QStringList groups
Current user's groups.
QString lastError
Error message from last failed operation.
bool loginInProgress
Whether a login/logout operation is in progress.
QStringList privileges
Current user's privileges.
QString username
Current user's username (empty if not authenticated).
Detailed Description
Authentication manager for built-in username/password authentication.
This class manages authentication state and provides signals for auth events. It communicates with the muscoviteserver security gRPC services.
Usage:
auto& auth = AuthManager::instance();
auth.configure(AuthConfig{.serverAddress = "localhost:50051"});
connect(&auth, &AuthManager::loginSucceeded, [](const Session& session) {
    qDebug() << "Logged in as" << session.username;
});
connect(&auth, &AuthManager::loginFailed, [](const QString& error) {
    qWarning() << "Login failed:" << error;
});
auth.login("admin", "password");
Definition at line 75 of file auth_manager.hpp.
Member Function Documentation
accessToken()
QString muscovite::qt::AuthManager::accessToken () const nodiscard
Get the current access token.
Returns
Access token for gRPC calls
Definition at line 206 of file auth_manager.cpp.
Referenced by changePassword(), and muscovite::qt::CreateAuthCallCredentials().
changePassword()
void muscovite::qt::AuthManager::changePassword (const QString & currentPassword, const QString & newPassword)
Change the current user's password.
Parameters
currentPassword Current password
newPassword New password
Definition at line 411 of file auth_manager.cpp.
References accessToken(), errorOccurred(), passwordChanged(), and passwordChangeFailed().
config()
const AuthConfig & muscovite::qt::AuthManager::config () const nodiscard
Get the current configuration.
Returns
Current authentication configuration
Definition at line 164 of file auth_manager.cpp.
Referenced by configure().
configure()
void muscovite::qt::AuthManager::configure (const AuthConfig & config)
Configure the authentication manager.
Parameters
config Authentication configuration
Definition at line 159 of file auth_manager.cpp.
References config().
displayName()
QString muscovite::qt::AuthManager::displayName () const nodiscard
Get the current display name.
Returns
Display name or empty string if not authenticated
Definition at line 178 of file auth_manager.cpp.
errorOccurred
void muscovite::qt::AuthManager::errorOccurred (const QString & _t1) signal
Emitted when an error occurs.
Parameters
error Error message
References errorOccurred().
Referenced by changePassword(), errorOccurred(), login(), and refreshToken().
groups()
QStringList muscovite::qt::AuthManager::groups () const nodiscard
Get the current user's groups.
Returns
List of group names
Definition at line 188 of file auth_manager.cpp.
hasAllPrivileges()
bool muscovite::qt::AuthManager::hasAllPrivileges (const QStringList & privileges) const nodiscard
Check if the user has all specified privileges.
Parameters
privileges List of privilege names
Returns
true if user has all privileges
Definition at line 226 of file auth_manager.cpp.
References privileges.
Referenced by muscovite::qt::PrivilegeChecker::hasAll().
hasAnyPrivilege()
bool muscovite::qt::AuthManager::hasAnyPrivilege (const QStringList & privileges) const nodiscard
Check if the user has any of the specified privileges.
Parameters
privileges List of privilege names
Returns
true if user has at least one privilege
Definition at line 217 of file auth_manager.cpp.
References privileges.
Referenced by muscovite::qt::PrivilegeChecker::hasAny().
hasPrivilege()
bool muscovite::qt::AuthManager::hasPrivilege (const QString & privilege) const nodiscard
Check if the user has a specific privilege.
Parameters
privilege Privilege name to check
Returns
true if user has the privilege
Definition at line 211 of file auth_manager.cpp.
Referenced by muscovite::qt::PrivilegeChecker::has().
instance()
AuthManager & muscovite::qt::AuthManager::instance () static nodiscard
Get singleton instance.
Returns
Reference to the global AuthManager instance
Definition at line 146 of file auth_manager.cpp.
References instance().
Referenced by muscovite::qt::CreateAuthCallCredentials(), muscovite::qt::PrivilegeChecker::displayName(), muscovite::qt::PrivilegeChecker::has(), muscovite::qt::PrivilegeChecker::hasAll(), muscovite::qt::PrivilegeChecker::hasAny(), muscovite::qt::PrivilegeChecker::inGroup(), instance(), muscovite::qt::PrivilegeChecker::isAdmin(), muscovite::qt::PrivilegeChecker::isAuthenticated(), muscovite::qt::example::MuscoviteApplication::run(), and muscovite::qt::PrivilegeChecker::username().
isAdmin()
bool muscovite::qt::AuthManager::isAdmin () const nodiscard
Check if the user is an administrator.
Returns
true if user is in the admin group
Definition at line 241 of file auth_manager.cpp.
References isInGroup().
Referenced by muscovite::qt::PrivilegeChecker::isAdmin().
isAuthenticated()
bool muscovite::qt::AuthManager::isAuthenticated () const nodiscard
Check if the user is currently authenticated.
Returns
true if authenticated, false otherwise
Definition at line 168 of file auth_manager.cpp.
Referenced by muscovite::qt::PrivilegeChecker::isAuthenticated().
isInGroup()
bool muscovite::qt::AuthManager::isInGroup (const QString & group) const nodiscard
Check if the user is in a specific group.
Parameters
group Group name to check
Returns
true if user is in the group
Definition at line 235 of file auth_manager.cpp.
Referenced by muscovite::qt::PrivilegeChecker::inGroup(), and isAdmin().
isLoginInProgress()
bool muscovite::qt::AuthManager::isLoginInProgress () const nodiscard
Check if a login operation is in progress.
Returns
true if login/logout in progress
Definition at line 193 of file auth_manager.cpp.
lastError()
QString muscovite::qt::AuthManager::lastError () const nodiscard
Get the last error message.
Returns
Error message or empty string
Definition at line 197 of file auth_manager.cpp.
login()
void muscovite::qt::AuthManager::login (const QString & username, const QString & password)
Login with username and password.
Parameters
username Username
password Password
This is an asynchronous operation. Connect to loginSucceeded or loginFailed signals to handle the result.
Definition at line 245 of file auth_manager.cpp.
References authStateChanged(), errorOccurred(), loginFailed(), loginProgressChanged(), loginSucceeded(), and username.
loginFailed
void muscovite::qt::AuthManager::loginFailed (const QString & _t1) signal
Emitted when login fails.
Parameters
error Error message
References loginFailed().
Referenced by login(), and loginFailed().
loginSucceeded
void muscovite::qt::AuthManager::loginSucceeded (const Session & _t1) signal
Emitted when login succeeds.
Parameters
session The new session information
References loginSucceeded().
Referenced by login(), and loginSucceeded().
logout()
void muscovite::qt::AuthManager::logout ()
Logout and invalidate the current session.
Definition at line 307 of file auth_manager.cpp.
References authStateChanged(), and loggedOut().
logoutAll()
void muscovite::qt::AuthManager::logoutAll ()
Logout from all sessions.
Definition at line 337 of file auth_manager.cpp.
References authStateChanged(), and loggedOut().
passwordChangeFailed
void muscovite::qt::AuthManager::passwordChangeFailed (const QString & _t1) signal
Emitted when password change fails.
Parameters
error Error message
References passwordChangeFailed().
Referenced by changePassword(), and passwordChangeFailed().
privileges()
QStringList muscovite::qt::AuthManager::privileges () const nodiscard
Get the current user's privileges.
Returns
List of privilege names
Definition at line 183 of file auth_manager.cpp.
refreshToken()
void muscovite::qt::AuthManager::refreshToken ()
Refresh the access token.
This is called automatically if autoRefresh is enabled.
Definition at line 364 of file auth_manager.cpp.
References authStateChanged(), errorOccurred(), refreshToken(), sessionExpired(), tokenRefreshed(), and tokenRefreshFailed().
Referenced by refreshToken().
session()
std::optional< Session > muscovite::qt::AuthManager::session () const nodiscard
Get the current session.
Returns
Session info or nullopt if not authenticated
Definition at line 201 of file auth_manager.cpp.
sessionExpiring
void muscovite::qt::AuthManager::sessionExpiring (int _t1) signal
Emitted when the session is about to expire.
Parameters
secondsRemaining Seconds until expiry
References sessionExpiring().
Referenced by sessionExpiring().
tokenRefreshFailed
void muscovite::qt::AuthManager::tokenRefreshFailed (const QString & _t1) signal
Emitted when token refresh fails.
Parameters
error Error message
References tokenRefreshFailed().
Referenced by refreshToken(), and tokenRefreshFailed().
username()
QString muscovite::qt::AuthManager::username () const nodiscard
Get the current username.
Returns
Username or empty string if not authenticated
Definition at line 173 of file auth_manager.cpp.
Property Documentation
authenticated
bool muscovite::qt::AuthManager::authenticated read
Whether the user is currently authenticated.
Definition at line 79 of file auth_manager.hpp.
displayName
QString muscovite::qt::AuthManager::displayName read
Current user's display name.
Definition at line 85 of file auth_manager.hpp.
Referenced by muscovite::qt::PrivilegeChecker::displayName().
groups
QStringList muscovite::qt::AuthManager::groups read
Current user's groups.
Definition at line 91 of file auth_manager.hpp.
lastError
QString muscovite::qt::AuthManager::lastError read
Error message from last failed operation.
Definition at line 97 of file auth_manager.hpp.
loginInProgress
bool muscovite::qt::AuthManager::loginInProgress read
Whether a login/logout operation is in progress.
Definition at line 94 of file auth_manager.hpp.
privileges
QStringList muscovite::qt::AuthManager::privileges read
Current user's privileges.
Definition at line 88 of file auth_manager.hpp.
Referenced by hasAllPrivileges(), and hasAnyPrivilege().
username
QString muscovite::qt::AuthManager::username read
Current user's username (empty if not authenticated).
Definition at line 82 of file auth_manager.hpp.
Referenced by muscovite::qt::services::GeosciencesServiceClient::createSample(), muscovite::qt::services::GeosciencesServiceClient::deleteSample(), muscovite::qt::services::GeosciencesServiceClient::fetchSamples(), login(), muscovite::qt::services::GeosciencesServiceClient::updateSample(), and muscovite::qt::PrivilegeChecker::username().
The documentation for this class was generated from the following files:
framework/qt/include/muscovite/qt/auth/auth_manager.hpp
framework/qt/src/auth/auth_manager.cpp