Muscovite C++ Framework: muscovite::dba::InfrastructureStateMachineBase< BackoffPolicy > Class Template Reference
muscovite::dba::InfrastructureStateMachineBase< BackoffPolicy > Class Template Reference
Three-state circuit breaker: Closed → Open → Half-Open.
#include <infrastructure_state_machine.hpp>
Public Types
using State = CircuitState
Alias for the namespace-scoped CircuitState enum.
Public Member Functions
InfrastructureStateMachineBase (const InfrastructureStateMachineBase &)=delete
InfrastructureStateMachineBase (InfrastructureStateMachineBase &&)=default
InfrastructureStateMachineBase (int failure_threshold=3)
Construct with configurable failure threshold.
template<typename F>
auto call (F &&fn) -> bool
Execute a callable through the circuit breaker.
auto failure_count () const noexcept -> int
Number of consecutive failures in current Closed cycle.
auto failure_threshold () const noexcept -> int
Configured failure threshold.
auto operator= (const InfrastructureStateMachineBase &) -> InfrastructureStateMachineBase &=delete
auto operator= (InfrastructureStateMachineBase &&) -> InfrastructureStateMachineBase &=default
void reset ()
Manual reset to Closed state.
auto state () const noexcept -> State
Current circuit breaker state.
Protected Member Functions
virtual void on_half_open ()
Called when circuit transitions from Open to Half-Open (probe).
virtual void on_open ()
Called when circuit trips from Closed/Half-Open to Open. Override to log, emit metrics, or publish NATS event.
virtual void on_trip ()
Called on the specific failure that triggers the trip to Open.
Detailed Description
template<typename BackoffPolicy>
class muscovite::dba::InfrastructureStateMachineBase< BackoffPolicy >
Three-state circuit breaker: Closed → Open → Half-Open.
This is NOT a domain state machine. It tracks infrastructure health for plugin calls (gRPC, QtRemoteObjects). The BackoffPolicy template parameter controls the cool-down schedule between Open → Half-Open probe attempts.
State transitions:
Closed: normal operation. Failures increment counter.
Open: all calls rejected. After backoff delay, transitions to Half-Open.
Half-Open: one probe call allowed. Success → Closed, Failure → Open.
Template Parameters
BackoffPolicy Must satisfy: next_delay(int) → chrono::milliseconds, reset().
See also
ADR 20260223-circuit-breaker-as-infrastructure-state-machine
Note
This class is NOT related to muscovite::qt::validation::EntityDialogStateMachine. That hierarchy models domain entity lifecycles; this models infrastructure health.
Definition at line 163 of file infrastructure_state_machine.hpp.
Member Typedef Documentation
State
template<typename BackoffPolicy> using muscovite::dba::InfrastructureStateMachineBase< BackoffPolicy >::State = CircuitState
Alias for the namespace-scoped CircuitState enum.
Definition at line 166 of file infrastructure_state_machine.hpp.
Constructor & Destructor Documentation
InfrastructureStateMachineBase()
template<typename BackoffPolicy> muscovite::dba::InfrastructureStateMachineBase< BackoffPolicy >::InfrastructureStateMachineBase (int failure_threshold = 3) inline explicit
Construct with configurable failure threshold.
Parameters
failure_threshold Number of consecutive failures before tripping to Open.
Definition at line 170 of file infrastructure_state_machine.hpp.
References failure_threshold().
Member Function Documentation
call()
template<typename BackoffPolicy> template<typename F> auto muscovite::dba::InfrastructureStateMachineBase< BackoffPolicy >::call (F && fn) -> bool inline
Execute a callable through the circuit breaker.
In Closed/Half-Open: calls fn(). In Open: checks if backoff elapsed. Returns true if the call succeeded, false if rejected or failed.
Template Parameters
F Callable returning bool (true = success, false = failure).
Parameters
fn The wrapped operation (e.g., gRPC plugin invocation).
Returns
true if fn executed and returned true, false otherwise.
Definition at line 188 of file infrastructure_state_machine.hpp.
References on_half_open().
failure_count()
template<typename BackoffPolicy> auto muscovite::dba::InfrastructureStateMachineBase< BackoffPolicy >::failure_count () const -> int inline nodiscard noexcept
Number of consecutive failures in current Closed cycle.
Definition at line 236 of file infrastructure_state_machine.hpp.
failure_threshold()
template<typename BackoffPolicy> auto muscovite::dba::InfrastructureStateMachineBase< BackoffPolicy >::failure_threshold () const -> int inline nodiscard noexcept
Configured failure threshold.
Definition at line 241 of file infrastructure_state_machine.hpp.
Referenced by InfrastructureStateMachineBase().
on_half_open()
template<typename BackoffPolicy> virtual void muscovite::dba::InfrastructureStateMachineBase< BackoffPolicy >::on_half_open () inline protected virtual
Called when circuit transitions from Open to Half-Open (probe).
Definition at line 260 of file infrastructure_state_machine.hpp.
Referenced by call().
on_open()
template<typename BackoffPolicy> virtual void muscovite::dba::InfrastructureStateMachineBase< BackoffPolicy >::on_open () inline protected virtual
Called when circuit trips from Closed/Half-Open to Open. Override to log, emit metrics, or publish NATS event.
Definition at line 257 of file infrastructure_state_machine.hpp.
on_trip()
template<typename BackoffPolicy> virtual void muscovite::dba::InfrastructureStateMachineBase< BackoffPolicy >::on_trip () inline protected virtual
Called on the specific failure that triggers the trip to Open.
Definition at line 263 of file infrastructure_state_machine.hpp.
reset()
template<typename BackoffPolicy> void muscovite::dba::InfrastructureStateMachineBase< BackoffPolicy >::reset () inline
Manual reset to Closed state.
Definition at line 246 of file infrastructure_state_machine.hpp.
state()
template<typename BackoffPolicy> auto muscovite::dba::InfrastructureStateMachineBase< BackoffPolicy >::state () const -> State inline nodiscard noexcept
Current circuit breaker state.
Definition at line 231 of file infrastructure_state_machine.hpp.
The documentation for this class was generated from the following file:
framework/dba/include/muscovite/dba/infrastructure_state_machine.hpp