Muscovite C++ Framework: muscovite::qt::widgets::BoundsInput Class Reference
muscovite::qt::widgets::BoundsInput Class Reference
Bounding box input widget for bounded spatial queries.
#include <spatial_widgets.hpp>
Classes
struct Bounds
Get all bounds as a struct for easier handling.
Signals
void boundsChanged (const BoundsInput::Bounds &_t1)
Emitted when any bound value changes.
void validityChanged (bool _t1)
Emitted when validity changes.
Public Member Functions
BoundsInput (const QString &label="Bounding Box", QWidget *parent=nullptr)
Bounds bounds () const
Get current bounds.
bool isValid () const
Check if current bounds are valid.
void setBounds (const Bounds &bounds)
Set all bounds from a Bounds structure.
void setBounds (double minLat, double minLon, double maxLat, double maxLon)
Set bounds from individual values.
void setBoundsAroundPoint (double centerLat, double centerLon, double marginDegrees=0.1)
Set bounds centered on coordinates with a margin.
void setEnabled (bool enabled)
Enable/disable bounds inputs.
validation::ValidationResult validate () const
Get validation results.
Detailed Description
Bounding box input widget for bounded spatial queries.
Features:
Four QDoubleSpinBox widgets (min/max latitude and longitude)
Automatic validation that min <= max
Clear labeling of each corner
Can generate ST_MakeEnvelope parameters for PostgreSQL
Layout: [ Min Latitude | spinbox ] [ Max Latitude | spinbox ] [ Min Longitude | spinbox ] [ Max Longitude | spinbox ]
Definition at line 326 of file spatial_widgets.hpp.
Constructor & Destructor Documentation
BoundsInput()
muscovite::qt::widgets::BoundsInput::BoundsInput (const QString & label = "Bounding Box", QWidget * parent = nullptr) explicit
Definition at line 385 of file spatial_widgets.cpp.
Member Function Documentation
bounds()
BoundsInput::Bounds muscovite::qt::widgets::BoundsInput::bounds () const nodiscard
Get current bounds.
Definition at line 468 of file spatial_widgets.cpp.
Referenced by isValid(), setBounds(), and validate().
isValid()
bool muscovite::qt::widgets::BoundsInput::isValid () const nodiscard
Check if current bounds are valid.
Valid bounds have:
All coordinates in valid ranges
minLatitude <= maxLatitude
minLongitude <= maxLongitude
Definition at line 497 of file spatial_widgets.cpp.
References bounds(), and muscovite::qt::widgets::BoundsInput::Bounds::isValid().
setBounds() [1/2]
void muscovite::qt::widgets::BoundsInput::setBounds (const Bounds & bounds)
Set all bounds from a Bounds structure.
Definition at line 476 of file spatial_widgets.cpp.
References bounds().
Referenced by setBounds(), and setBoundsAroundPoint().
setBounds() [2/2]
void muscovite::qt::widgets::BoundsInput::setBounds (double minLat, double minLon, double maxLat, double maxLon)
Set bounds from individual values.
Definition at line 484 of file spatial_widgets.cpp.
References setBounds().
setBoundsAroundPoint()
void muscovite::qt::widgets::BoundsInput::setBoundsAroundPoint (double centerLat, double centerLon, double marginDegrees = 0.1)
Set bounds centered on coordinates with a margin.
Useful for creating a bounding box around a point.
Parameters
centerLat Center latitude
centerLon Center longitude
marginDegrees Margin in degrees (0.1 = ~11 km at equator)
Definition at line 489 of file spatial_widgets.cpp.
References setBounds().
setEnabled()
void muscovite::qt::widgets::BoundsInput::setEnabled (bool enabled)
Enable/disable bounds inputs.
Definition at line 554 of file spatial_widgets.cpp.
validate()
validation::ValidationResult muscovite::qt::widgets::BoundsInput::validate () const nodiscard
Get validation results.
Definition at line 502 of file spatial_widgets.cpp.
References bounds().
The documentation for this class was generated from the following files:
framework/qt/include/muscovite/qt/widgets/spatial_widgets.hpp
framework/qt/src/widgets/spatial_widgets.cpp