Muscovite C++ Framework: muscovite::dba::ReadReplicaRouter Class Reference
muscovite::dba::ReadReplicaRouter Class Reference
#include <read_replica_router.hpp>
Public Member Functions
ReadReplicaRouter (const ReadReplicaRouter &)=delete
ReadReplicaRouter (ReadReplicaRouter &&) noexcept
ReadReplicaRouter (std::shared_ptr< ConnectionPool > primary)
auto acquire_read () -> std::expected< PooledConnection, Error< PoolError > >
auto acquire_write () -> std::expected< PooledConnection, Error< PoolError > >
void check_replica_health ()
Force health check on replica (useful after network issues).
auto has_replica () const noexcept -> bool
Check if read replica is configured and enabled.
auto is_replica_healthy () const noexcept -> bool
Check if read replica is currently healthy.
ReadReplicaRouter & operator= (const ReadReplicaRouter &)=delete
ReadReplicaRouter & operator= (ReadReplicaRouter &&) noexcept
auto primary_pool () const noexcept -> std::shared_ptr< ConnectionPool >
Get the primary connection pool (for direct access if needed).
auto replica_lag_ms () const -> std::optional< std::chrono::milliseconds >
auto replica_pool () const noexcept -> std::shared_ptr< ConnectionPool >
Get the replica connection pool (nullptr if not configured).
void shutdown ()
Shutdown both pools.
Static Public Member Functions
static auto create (std::shared_ptr< ConnectionPool > primary, ReadReplicaConfig config) -> std::expected< ReadReplicaRouter, Error< PoolError > >
Detailed Description
Routes database connections based on operation type.
For CQRS architecture:
Write operations (Commands) → Primary database
Read operations (Queries) → Read replica (with fallback to primary)
Thread-safe: Multiple threads can call acquire_* concurrently.
Definition at line 81 of file read_replica_router.hpp.
Constructor & Destructor Documentation
ReadReplicaRouter()
muscovite::dba::ReadReplicaRouter::ReadReplicaRouter (std::shared_ptr< ConnectionPool > primary) explicit
Create a router with primary pool only (no read replica)
Parameters
primary Primary database connection pool
Definition at line 40 of file read_replica_router.cpp.
Referenced by acquire_write(), and create().
Member Function Documentation
acquire_read()
auto muscovite::dba::ReadReplicaRouter::acquire_read () -> std::expected< PooledConnection, Error< PoolError > > nodiscard
Acquire a connection for read operations
Returns
Connection from replica if available, otherwise primary (if fallback enabled)
Definition at line 95 of file read_replica_router.cpp.
acquire_write()
auto muscovite::dba::ReadReplicaRouter::acquire_write () -> std::expected< PooledConnection, Error< PoolError > > nodiscard
Acquire a connection for write operations (always primary)
Returns
Connection from primary pool
Definition at line 91 of file read_replica_router.cpp.
References ReadReplicaRouter(), and acquire_write().
Referenced by acquire_write().
check_replica_health()
void muscovite::dba::ReadReplicaRouter::check_replica_health ()
Force health check on replica (useful after network issues).
Definition at line 168 of file read_replica_router.cpp.
create()
auto muscovite::dba::ReadReplicaRouter::create (std::shared_ptr< ConnectionPool > primary, ReadReplicaConfig config) -> std::expected< ReadReplicaRouter, Error< PoolError > > static nodiscard
Create a router with primary and optional read replica
Parameters
primary Primary database connection pool
config Read replica configuration
Definition at line 43 of file read_replica_router.cpp.
References ReadReplicaRouter(), and muscovite::dba::ConnectionPool::create().
has_replica()
auto muscovite::dba::ReadReplicaRouter::has_replica () const -> bool nodiscard noexcept
Check if read replica is configured and enabled.
Definition at line 123 of file read_replica_router.cpp.
is_replica_healthy()
auto muscovite::dba::ReadReplicaRouter::is_replica_healthy () const -> bool nodiscard noexcept
Check if read replica is currently healthy.
Definition at line 119 of file read_replica_router.cpp.
primary_pool()
auto muscovite::dba::ReadReplicaRouter::primary_pool () const -> std::shared_ptr< ConnectionPool > nodiscard noexcept
Get the primary connection pool (for direct access if needed).
Definition at line 127 of file read_replica_router.cpp.
replica_lag_ms()
auto muscovite::dba::ReadReplicaRouter::replica_lag_ms () const -> std::optional< std::chrono::milliseconds > nodiscard
Get replica lag in milliseconds (if measurable)
Returns
Lag in ms, or nullopt if not measurable
Definition at line 135 of file read_replica_router.cpp.
replica_pool()
auto muscovite::dba::ReadReplicaRouter::replica_pool () const -> std::shared_ptr< ConnectionPool > nodiscard noexcept
Get the replica connection pool (nullptr if not configured).
Definition at line 131 of file read_replica_router.cpp.
shutdown()
void muscovite::dba::ReadReplicaRouter::shutdown ()
Shutdown both pools.
Definition at line 193 of file read_replica_router.cpp.
The documentation for this class was generated from the following files:
framework/dba/include/muscovite/dba/read_replica_router.hpp
framework/dba/src/read_replica_router.cpp