Muscovite C++ Framework: muscovite::search::SearchQuery Class Reference
muscovite::search::SearchQuery Class Reference
Fluent builder for OpenSearch query DSL.
#include <search_query.hpp>
Public Member Functions
SearchQuery & aggregate (const std::string &name, const std::string &field, std::int32_t size=10)
Add a terms aggregation (facet).
SearchQuery & fields (const std::vector< std::string > &field_names)
Set the fields for full-text search.
SearchQuery & filter_range (const std::string &field, const RangeBounds &bounds)
Add a range filter.
SearchQuery & filter_term (const std::string &field, const std::string &value)
Add an exact term filter.
SearchQuery & highlight (const std::vector< std::string > &field_names)
Enable highlighting for specified fields.
SearchQuery & match (const std::string &field, const std::string &text)
Add a match clause (single-field full-text).
SearchQuery & min_score (double score)
Set minimum relevance score threshold.
SearchQuery & must_not_term (const std::string &field, const std::string &value)
Add a must_not term clause (exclusion filter).
std::int32_t page () const noexcept
Get the configured page number (1-based).
std::int32_t page_size () const noexcept
Get the configured page size.
SearchQuery & paginate (std::int32_t page, std::int32_t page_size=20)
Set pagination parameters.
SearchQuery & sort (const std::string &field, SortOrder order)
Add a sort clause.
nlohmann::json to_json () const
Build the OpenSearch query JSON.
Static Public Member Functions
static SearchQuery full_text (const std::string &text)
Create a full-text search query.
static SearchQuery match_all ()
Create an empty query builder (match_all by default).
Detailed Description
Fluent builder for OpenSearch query DSL.
Constructs valid OpenSearch JSON query bodies using a type-safe interface. The builder accumulates clauses and produces the final JSON via to_json().
Query types:
full_text() — multi_match across all searchable fields
match() — single-field match query
term() — exact term filter (not analyzed)
range() — range filter on date/numeric fields
bool_query() — explicit bool with must/should/filter/must_not
Modifiers:
paginate() — from/size pagination
highlight() — field highlighting with tags
sort() — field sort order
aggregate() — terms aggregation (facets)
min_score() — minimum relevance threshold
Thread safety: NOT thread-safe. Build the query on a single thread, then pass the resulting JSON to OpenSearchClient.
See also
OpenSearchClient::search — consumes to_json() output
PagedSearchResult — wraps the response
Definition at line 86 of file search_query.hpp.
Member Function Documentation
aggregate()
SearchQuery & muscovite::search::SearchQuery::aggregate (const std::string & name, const std::string & field, std::int32_t size = 10)
Add a terms aggregation (facet).
Parameters
name Aggregation name (appears in SearchFacet::name).
field Field name to aggregate on.
size Maximum number of buckets (default 10).
Returns
*this for chaining.
Definition at line 85 of file search_query.cpp.
fields()
SearchQuery & muscovite::search::SearchQuery::fields (const std::vector< std::string > & field_names)
Set the fields for full-text search.
Parameters
field_names List of field names to search.
Returns
*this for chaining.
Note
Only meaningful when the query was created via full_text(). These fields are used in the multi_match query.
Definition at line 44 of file search_query.cpp.
filter_range()
SearchQuery & muscovite::search::SearchQuery::filter_range (const std::string & field, const RangeBounds & bounds)
Add a range filter.
Parameters
field Field name (date or numeric).
bounds Range bounds (gte, gt, lte, lt).
Returns
*this for chaining.
Range filters are added to the bool query's filter clause.
Definition at line 55 of file search_query.cpp.
filter_term()
SearchQuery & muscovite::search::SearchQuery::filter_term (const std::string & field, const std::string & value)
Add an exact term filter.
Parameters
field Field name (not analyzed — use keyword subfield if needed).
value Exact value to match.
Returns
*this for chaining.
Term filters are added to the bool query's filter clause so they don't affect relevance scoring.
Definition at line 49 of file search_query.cpp.
full_text()
SearchQuery muscovite::search::SearchQuery::full_text (const std::string & text) static
Create a full-text search query.
Parameters
text Query text to search across all @searchable fields.
Returns
SearchQuery builder for chaining.
Generates a multi_match query with type "best_fields". The fields list is typically set via fields() or left empty to search all indexed fields.
Definition at line 22 of file search_query.cpp.
highlight()
SearchQuery & muscovite::search::SearchQuery::highlight (const std::vector< std::string > & field_names)
Enable highlighting for specified fields.
Parameters
field_names Fields to highlight.
Returns
*this for chaining.
Highlighted fragments are returned in SearchHit::highlights with tags around matching terms.
Definition at line 74 of file search_query.cpp.
match()
SearchQuery & muscovite::search::SearchQuery::match (const std::string & field, const std::string & text)
Add a match clause (single-field full-text).
Parameters
field Field name to match against.
text Query text.
Returns
*this for chaining.
Definition at line 38 of file search_query.cpp.
match_all()
SearchQuery muscovite::search::SearchQuery::match_all () static
Create an empty query builder (match_all by default).
Returns
SearchQuery builder for chaining.
Definition at line 28 of file search_query.cpp.
min_score()
SearchQuery & muscovite::search::SearchQuery::min_score (double score)
Set minimum relevance score threshold.
Parameters
score Minimum score (hits below this are excluded).
Returns
*this for chaining.
Definition at line 92 of file search_query.cpp.
must_not_term()
SearchQuery & muscovite::search::SearchQuery::must_not_term (const std::string & field, const std::string & value)
Add a must_not term clause (exclusion filter).
Parameters
field Field name.
value Value to exclude.
Returns
*this for chaining.
Definition at line 61 of file search_query.cpp.
page()
std::int32_t muscovite::search::SearchQuery::page () const inline nodiscard noexcept
Get the configured page number (1-based).
Definition at line 184 of file search_query.hpp.
Referenced by paginate().
page_size()
std::int32_t muscovite::search::SearchQuery::page_size () const inline nodiscard noexcept
Get the configured page size.
Definition at line 187 of file search_query.hpp.
Referenced by paginate().
paginate()
SearchQuery & muscovite::search::SearchQuery::paginate (std::int32_t page, std::int32_t page_size = 20)
Set pagination parameters.
Parameters
page Page number (1-based, converted to from/size internally).
page_size Number of results per page (default 20).
Returns
*this for chaining.
Definition at line 67 of file search_query.cpp.
References page(), and page_size().
sort()
SearchQuery & muscovite::search::SearchQuery::sort (const std::string & field, SortOrder order)
Add a sort clause.
Parameters
field Field name to sort by.
order Sort direction (Asc or Desc).
Returns
*this for chaining.
Multiple sort clauses are applied in order of addition.
Definition at line 80 of file search_query.cpp.
to_json()
nlohmann::json muscovite::search::SearchQuery::to_json () const nodiscard
Build the OpenSearch query JSON.
Returns
Valid OpenSearch query body as nlohmann::json.
This is the final step — pass the result to OpenSearchClient::search().
Definition at line 101 of file search_query.cpp.
The documentation for this class was generated from the following files:
framework/search/include/muscovite/search/search_query.hpp
framework/search/src/search_query.cpp