Muscovite C++ Framework: muscovite::server::security::PasswordService Class Reference
muscovite::server::security::PasswordService Class Reference
Service for password hashing and verification using Argon2id.
#include <password_service.hpp>
Classes
struct Config
Configuration for Argon2id hashing.
struct ValidationResult
Password validation result.
Public Member Functions
PasswordService ()
Construct with default configuration.
PasswordService (const Config &config)
Construct with custom configuration.
PasswordService (const PasswordService &)=delete
PasswordService (PasswordService &&) noexcept
std::string hash_password (const std::string &password) const
Hash a password using Argon2id.
bool needs_rehash (const std::string &hash) const
Check if a password hash needs rehashing.
PasswordService & operator= (const PasswordService &)=delete
PasswordService & operator= (PasswordService &&) noexcept
ValidationResult validate_password_strength (const std::string &password, const std::optional< std::string > &username=std::nullopt) const
Validate password strength requirements.
bool verify_password (const std::string &password, const std::string &hash) const
Verify a password against a stored hash.
Detailed Description
Service for password hashing and verification using Argon2id.
This service implements secure password hashing following OWASP recommendations:
Algorithm: Argon2id (memory-hard, resistant to GPU/ASIC attacks)
Time cost: 3 iterations
Memory cost: 64 MB
Parallelism: 4 threads
Hash length: 32 bytes
Passwords are never stored in plaintext - only hashes are persisted.
Definition at line 29 of file password_service.hpp.
Constructor & Destructor Documentation
PasswordService() [1/2]
muscovite::server::security::PasswordService::PasswordService ()
Construct with default configuration.
Definition at line 244 of file password_service.cpp.
Referenced by hash_password().
PasswordService() [2/2]
muscovite::server::security::PasswordService::PasswordService (const Config & config) explicit
Construct with custom configuration.
Definition at line 247 of file password_service.cpp.
Member Function Documentation
hash_password()
std::string muscovite::server::security::PasswordService::hash_password (const std::string & password) const nodiscard
Hash a password using Argon2id.
Parameters
password The plaintext password to hash.
Returns
The encoded hash string (includes algorithm, params, salt, and hash).
Exceptions
std::runtime_error if hashing fails.
Definition at line 255 of file password_service.cpp.
References PasswordService(), and hash_password().
Referenced by hash_password().
needs_rehash()
bool muscovite::server::security::PasswordService::needs_rehash (const std::string & hash) const nodiscard
Check if a password hash needs rehashing.
This is useful when security parameters have been upgraded.
Parameters
hash The stored encoded hash string.
Returns
true if the hash should be regenerated with current parameters.
Definition at line 264 of file password_service.cpp.
validate_password_strength()
PasswordService::ValidationResult muscovite::server::security::PasswordService::validate_password_strength (const std::string & password, const std::optional< std::string > & username = std::nullopt) const nodiscard
Validate password strength requirements.
Requirements:
Minimum 12 characters
At least one uppercase letter
At least one lowercase letter
At least one digit
At least one special character
Not in common password list (top 10000)
Parameters
password The password to validate.
username Optional username to check for similarity.
Returns
Validation result with detailed message if invalid.
Definition at line 268 of file password_service.cpp.
verify_password()
bool muscovite::server::security::PasswordService::verify_password (const std::string & password, const std::string & hash) const nodiscard
Verify a password against a stored hash.
Parameters
password The plaintext password to verify.
hash The stored encoded hash string.
Returns
true if the password matches, false otherwise.
Definition at line 259 of file password_service.cpp.
The documentation for this class was generated from the following files:
framework/server/include/muscovite/server/security/password_service.hpp
framework/server/src/security/password_service.cpp