Muscovite C++ Framework: muscovite::search::DocumentMapper Class Reference
muscovite::search::DocumentMapper Class Reference abstract
Abstract interface for mapping domain entities to OpenSearch documents.
#include <document_mapper.hpp>
Public Member Functions
virtual auto entity_type () const -> std::string=0
Entity type name matching event aggregate_type.
virtual auto fetch_and_map (const std::string &entity_id) -> std::optional< nlohmann::json >=0
Fetch current entity state and map to search document.
virtual auto handled_event_types () const -> std::vector< std::string >
Event types this mapper handles.
virtual auto index_mapping () const -> nlohmann::json=0
OpenSearch index mapping definition.
virtual auto index_name () const -> std::string=0
OpenSearch index name for this entity type.
Detailed Description
Abstract interface for mapping domain entities to OpenSearch documents.
Generated implementations (one per searchable entity) provide:
Index name derivation from bounded context + entity name
Index mapping (field types, analyzers, keyword sub-fields)
Entity fetch + JSON serialization for document body
Invariant
Each DocumentMapper handles exactly one entity type
index_name() returns a stable, deterministic name
Example generated implementation:
class PatientDocumentMapper : public DocumentMapper {
    PatientQueryRepository& repo_;
public:
    std::string index_name() const override { return "patient_patient"; }
    std::string entity_type() const override { return "Patient"; }
    nlohmann::json index_mapping() const override { ... }
    std::optional<nlohmann::json> fetch_and_map(const std::string& id) override {
        auto patient = repo_.find_by_id(parse_uuid(id));
        if (!patient) return std::nullopt;
        return nlohmann::json{{"mrn", patient->mrn}, {"family_name", patient->family_name}};
    }
};
Definition at line 60 of file document_mapper.hpp.
Member Function Documentation
entity_type()
virtual auto muscovite::search::DocumentMapper::entity_type () const -> std::string nodiscard pure virtual
Entity type name matching event aggregate_type.
Must match the aggregate_type field in domain events (e.g., "Patient", "Encounter", "Observation").
Returns
PascalCase entity type name
References entity_type().
Referenced by entity_type(), and handled_event_types().
fetch_and_map()
virtual auto muscovite::search::DocumentMapper::fetch_and_map (const std::string & entity_id) -> std::optional< nlohmann::json > nodiscard pure virtual
Fetch current entity state and map to search document.
Called on *Created and *Updated events. The mapper should:
Fetch the entity from its QueryRepository by ID
Map all @searchable fields to a flat JSON document
Return nullopt if entity not found (deleted between event and processing)
Parameters
entity_id UUID string of the entity to fetch
Returns
JSON document for indexing, or nullopt if entity not found
References fetch_and_map().
Referenced by fetch_and_map().
handled_event_types()
virtual auto muscovite::search::DocumentMapper::handled_event_types () const -> std::vector< std::string > inline nodiscard virtual
Event types this mapper handles.
Returns the full set of event types that should be routed to this mapper. Default implementation returns common CRUD patterns: {EntityType}Created, {EntityType}Updated, {EntityType}Deleted
Returns
List of event type strings
Definition at line 108 of file document_mapper.hpp.
References entity_type(), and handled_event_types().
Referenced by handled_event_types().
index_mapping()
virtual auto muscovite::search::DocumentMapper::index_mapping () const -> nlohmann::json nodiscard pure virtual
OpenSearch index mapping definition.
Returns the mappings object for PUT /{index} API. Defines field types, analyzers, and keyword sub-fields for each @searchable field.
Returns
JSON mapping object (e.g., {"properties": {"mrn": {"type": "text"}}})
References index_mapping().
Referenced by index_mapping().
index_name()
virtual auto muscovite::search::DocumentMapper::index_name () const -> std::string nodiscard pure virtual
OpenSearch index name for this entity type.
Convention: {schema}_{table} (e.g., "patient_patient", "encounter_encounter") Matches the PostgreSQL schema.table naming.
Returns
Stable index name (lowercase, underscore-separated)
Referenced by muscovite::search::BulkDocumentMapper::estimated_count().
The documentation for this class was generated from the following file:
framework/search/include/muscovite/search/document_mapper.hpp