Muscovite C++ Framework: muscovite::qt::services::GeosciencesServiceClient Class Reference
muscovite::qt::services::GeosciencesServiceClient Class Reference
Example Geosciences service client.
#include <geosciences_service_client.hpp>
Public Slots
void createSample (const QString &name, const QString &description)
Create a new sample.
void deleteSample (const QString &id)
Delete a sample.
void fetchSamples ()
Fetch all samples from the backend.
void updateSample (const QString &id, const QString &name, const QString &description)
Update a sample.
Signals
void authenticationRequired ()
Emitted when authentication is required.
void sampleCreated (const Sample &sample)
Emitted when sample is created.
void sampleCreationFailed (const QString &error)
Emitted when sample creation fails.
void sampleDeleted (const QString &id)
Emitted when sample is deleted.
void sampleDeletionFailed (const QString &error)
Emitted when sample deletion fails.
void samplesLoaded (const QList< Sample > &samples)
Emitted when samples are successfully fetched.
void samplesLoadFailed (const QString &error)
Emitted when fetching samples fails.
void sampleUpdated (const Sample &sample)
Emitted when sample is updated.
void sampleUpdateFailed (const QString &error)
Emitted when sample update fails.
Public Member Functions
GeosciencesServiceClient (QObject *parent=nullptr)
Construct the service client.
void initialize (std::shared_ptr<::grpc::Channel > channel, AuthManager *authMgr)
Initialize with gRPC channel and auth manager.
Public Member Functions inherited from muscovite::qt::grpc::ServiceClientBase
ServiceClientBase (std::shared_ptr<::grpc::Channel > channel)
AuthManager * authManager () const
Get the authentication manager.
void setAuthManager (AuthManager *authMgr)
Set the authentication manager for adding auth headers.
Additional Inherited Members
Protected Member Functions inherited from muscovite::qt::grpc::ServiceClientBase
template<typename Request, typename Response, typename Callable>
QFuture< GrpcResult< Response > > callUnary (const Request &request, Callable &&callable, std::chrono::milliseconds deadline=std::chrono::seconds{10})
Execute a unary call asynchronously with optional authentication.
std::shared_ptr<::grpc::Channel > channel () const
void setChannel (std::shared_ptr<::grpc::Channel > channel)
Detailed Description
Example Geosciences service client.
Demonstrates how to create a service client that:
Inherits from ServiceClientBase for auth-aware gRPC calls
Makes unary calls with automatic authentication headers
Handles errors and retries
Emits signals for async results
Definition at line 34 of file geosciences_service_client.hpp.
Constructor & Destructor Documentation
GeosciencesServiceClient()
muscovite::qt::services::GeosciencesServiceClient::GeosciencesServiceClient (QObject * parent = nullptr) explicit
Construct the service client.
Parameters
parent Parent object
Definition at line 14 of file geosciences_service_client.cpp.
Member Function Documentation
createSample
void muscovite::qt::services::GeosciencesServiceClient::createSample (const QString & name, const QString & description) slot
Create a new sample.
Parameters
name Sample name
description Sample description
Definition at line 55 of file geosciences_service_client.cpp.
References authenticationRequired(), muscovite::qt::grpc::ServiceClientBase::authManager(), sampleCreated(), sampleCreationFailed(), and muscovite::qt::AuthManager::username.
deleteSample
void muscovite::qt::services::GeosciencesServiceClient::deleteSample (const QString & id) slot
Delete a sample.
Parameters
id Sample ID to delete
Definition at line 103 of file geosciences_service_client.cpp.
References authenticationRequired(), muscovite::qt::grpc::ServiceClientBase::authManager(), sampleDeleted(), sampleDeletionFailed(), and muscovite::qt::AuthManager::username.
fetchSamples
void muscovite::qt::services::GeosciencesServiceClient::fetchSamples () slot
Fetch all samples from the backend.
Definition at line 32 of file geosciences_service_client.cpp.
References authenticationRequired(), muscovite::qt::grpc::ServiceClientBase::authManager(), samplesLoaded(), and muscovite::qt::AuthManager::username.
initialize()
void muscovite::qt::services::GeosciencesServiceClient::initialize (std::shared_ptr<::grpc::Channel > channel, AuthManager * authMgr)
Initialize with gRPC channel and auth manager.
Parameters
channel gRPC channel
authMgr Authentication manager
Definition at line 18 of file geosciences_service_client.cpp.
References authenticationRequired(), muscovite::qt::grpc::ServiceClientBase::authManager(), muscovite::qt::AuthManager::authStateChanged(), and muscovite::qt::grpc::ServiceClientBase::setAuthManager().
sampleCreated
void muscovite::qt::services::GeosciencesServiceClient::sampleCreated (const Sample & sample) signal
Emitted when sample is created.
Parameters
sample The created sample
Referenced by createSample().
sampleCreationFailed
void muscovite::qt::services::GeosciencesServiceClient::sampleCreationFailed (const QString & error) signal
Emitted when sample creation fails.
Parameters
error Error message
Referenced by createSample().
sampleDeleted
void muscovite::qt::services::GeosciencesServiceClient::sampleDeleted (const QString & id) signal
Emitted when sample is deleted.
Parameters
id ID of deleted sample
Referenced by deleteSample().
sampleDeletionFailed
void muscovite::qt::services::GeosciencesServiceClient::sampleDeletionFailed (const QString & error) signal
Emitted when sample deletion fails.
Parameters
error Error message
Referenced by deleteSample().
samplesLoaded
void muscovite::qt::services::GeosciencesServiceClient::samplesLoaded (const QList< Sample > & samples) signal
Emitted when samples are successfully fetched.
Parameters
samples List of samples
Referenced by fetchSamples().
samplesLoadFailed
void muscovite::qt::services::GeosciencesServiceClient::samplesLoadFailed (const QString & error) signal
Emitted when fetching samples fails.
Parameters
error Error message
sampleUpdated
void muscovite::qt::services::GeosciencesServiceClient::sampleUpdated (const Sample & sample) signal
Emitted when sample is updated.
Parameters
sample The updated sample
Referenced by updateSample().
sampleUpdateFailed
void muscovite::qt::services::GeosciencesServiceClient::sampleUpdateFailed (const QString & error) signal
Emitted when sample update fails.
Parameters
error Error message
Referenced by updateSample().
updateSample
void muscovite::qt::services::GeosciencesServiceClient::updateSample (const QString & id, const QString & name, const QString & description) slot
Update a sample.
Parameters
id Sample ID
name New name
description New description
Definition at line 79 of file geosciences_service_client.cpp.
References authenticationRequired(), muscovite::qt::grpc::ServiceClientBase::authManager(), sampleUpdated(), sampleUpdateFailed(), and muscovite::qt::AuthManager::username.
The documentation for this class was generated from the following files:
framework/qt/include/muscovite/qt/services/geosciences_service_client.hpp
framework/qt/src/services/geosciences_service_client.cpp