Muscovite C++ Framework: muscovite::spatial::LineString Class Reference
muscovite::spatial::LineString Class Reference
Geographic line string (sequence of connected points) Represents a path or polyline on Earth.
#include <geometry.hpp>
Public Member Functions
LineString ()=default
Construct empty LineString.
LineString (std::vector< Point > points)
auto is_valid () const -> bool
auto length_km () const -> Distance
Calculate total length of the line.
auto length_m () const -> Distance
Calculate total length in meters.
auto points () const -> const std::vector< Point > &
auto size () const -> size_t
auto to_wkt () const -> std::string
Convert to WKT format.
Static Public Member Functions
static auto from_wkt (std::string_view wkt) -> std::optional< LineString >
Parse from WKT string Format: "LINESTRING(lon1 lat1, lon2 lat2, ...)".
Detailed Description
Geographic line string (sequence of connected points) Represents a path or polyline on Earth.
Definition at line 135 of file geometry.hpp.
Constructor & Destructor Documentation
LineString()
muscovite::spatial::LineString::LineString (std::vector< Point > points) inline explicit
Construct from vector of points
Parameters
points At least 2 points required
Definition at line 142 of file geometry.hpp.
Member Function Documentation
is_valid()
auto muscovite::spatial::LineString::is_valid () const -> bool inline nodiscard
Definition at line 154 of file geometry.hpp.
length_km()
auto muscovite::spatial::LineString::length_km () const -> Distance nodiscard
Calculate total length of the line.
Returns
Length in kilometers
Referenced by length_m().
length_m()
auto muscovite::spatial::LineString::length_m () const -> Distance inline nodiscard
Calculate total length in meters.
Definition at line 162 of file geometry.hpp.
References length_km(), and length_m().
Referenced by length_m().
points()
auto muscovite::spatial::LineString::points () const -> const std::vector< Point > & inline nodiscard
Definition at line 152 of file geometry.hpp.
size()
auto muscovite::spatial::LineString::size () const -> size_t inline nodiscard
Definition at line 153 of file geometry.hpp.
The documentation for this class was generated from the following file:
framework/spatial/include/muscovite/spatial/geometry.hpp