Muscovite C++ Framework: muscovite::qt::widgets::RadiusInput Class Reference
muscovite::qt::widgets::RadiusInput Class Reference
Distance input widget for radius-based spatial queries.
#include <spatial_widgets.hpp>
Signals
void radiusChanged (double kilometers)
Emitted when radius value changes.
void validityChanged (bool isValid)
Emitted when validity changes.
Public Member Functions
RadiusInput (const QString &label="Radius", QWidget *parent=nullptr)
bool isValid () const
Check if current radius is valid.
double radius () const
Get current radius value in kilometers.
double radiusMeters () const
Get radius in meters.
void setEnabled (bool enabled)
Enable/disable the radius input.
void setRadius (double kilometers)
Set radius value in kilometers.
void setRadiusMeters (double meters)
Set radius from meters.
validation::ValidationResult validate () const
Get validation results.
Detailed Description
Distance input widget for radius-based spatial queries.
Features:
Single QDoubleSpinBox for distance in kilometers
Range: 0.001 km (1 meter) to 40,075 km (Earth circumference)
Clear labeling: "Radius" or custom label
Automatic validation
Layout: [ Radius | spinbox ] km
Definition at line 234 of file spatial_widgets.hpp.
Constructor & Destructor Documentation
RadiusInput()
muscovite::qt::widgets::RadiusInput::RadiusInput (const QString & label = "Radius", QWidget * parent = nullptr) explicit
Definition at line 259 of file spatial_widgets.cpp.
Member Function Documentation
isValid()
bool muscovite::qt::widgets::RadiusInput::isValid () const nodiscard
Check if current radius is valid.
Definition at line 317 of file spatial_widgets.cpp.
References radius().
Referenced by validityChanged().
radius()
double muscovite::qt::widgets::RadiusInput::radius () const nodiscard
Get current radius value in kilometers.
Definition at line 297 of file spatial_widgets.cpp.
Referenced by isValid(), radiusMeters(), and validate().
radiusMeters()
double muscovite::qt::widgets::RadiusInput::radiusMeters () const nodiscard
Get radius in meters.
Definition at line 307 of file spatial_widgets.cpp.
References radius().
setEnabled()
void muscovite::qt::widgets::RadiusInput::setEnabled (bool enabled)
Enable/disable the radius input.
Definition at line 334 of file spatial_widgets.cpp.
setRadius()
void muscovite::qt::widgets::RadiusInput::setRadius (double kilometers)
Set radius value in kilometers.
Definition at line 302 of file spatial_widgets.cpp.
Referenced by setRadiusMeters().
setRadiusMeters()
void muscovite::qt::widgets::RadiusInput::setRadiusMeters (double meters)
Set radius from meters.
Definition at line 312 of file spatial_widgets.cpp.
References setRadius().
validate()
validation::ValidationResult muscovite::qt::widgets::RadiusInput::validate () const nodiscard
Get validation results.
Definition at line 322 of file spatial_widgets.cpp.
References radius().
The documentation for this class was generated from the following files:
framework/qt/include/muscovite/qt/widgets/spatial_widgets.hpp
framework/qt/src/widgets/spatial_widgets.cpp