Muscovite C++ Framework: muscovite::dba::EventConsumer Class Reference
muscovite::dba::EventConsumer Class Reference abstract
#include <event_consumer.hpp>
Public Member Functions
virtual auto events_failed () const -> std::uint64_t=0
Get number of events that failed (Nak or Term).
virtual auto events_processed () const -> std::uint64_t=0
Get number of events processed.
virtual auto is_running () const -> bool=0
Check if consumer is running.
virtual auto last_error () const -> std::string=0
Get the last error message (if any).
virtual void on (const std::string &event_type, EventHandler handler)=0
virtual void on_any (EventHandler handler)=0
virtual void on_error (ErrorHandler handler)=0
virtual auto start () -> bool=0
virtual void stop ()=0
Detailed Description
Abstract interface for event consumers
Implementations wrap specific message brokers (NATS, Kafka, etc.)
Definition at line 165 of file event_consumer.hpp.
Member Function Documentation
events_failed()
virtual auto muscovite::dba::EventConsumer::events_failed () const -> std::uint64_t nodiscard pure virtual
Get number of events that failed (Nak or Term).
Implemented in muscovite::dba::NatsEventConsumer.
References events_failed().
Referenced by events_failed().
events_processed()
virtual auto muscovite::dba::EventConsumer::events_processed () const -> std::uint64_t nodiscard pure virtual
Get number of events processed.
Implemented in muscovite::dba::NatsEventConsumer.
References events_processed().
Referenced by events_processed().
is_running()
virtual auto muscovite::dba::EventConsumer::is_running () const -> bool nodiscard pure virtual
Check if consumer is running.
Implemented in muscovite::dba::NatsEventConsumer.
last_error()
virtual auto muscovite::dba::EventConsumer::last_error () const -> std::string nodiscard pure virtual
Get the last error message (if any).
Implemented in muscovite::dba::NatsEventConsumer.
References last_error().
Referenced by last_error().
on()
virtual void muscovite::dba::EventConsumer::on (const std::string & event_type, EventHandler handler) pure virtual
Register a handler for a specific event type
Parameters
event_type Event type to handle (e.g., "PatientCreated")
handler Handler function to invoke
Implemented in muscovite::dba::NatsEventConsumer.
on_any()
virtual void muscovite::dba::EventConsumer::on_any (EventHandler handler) pure virtual
Register a catch-all handler for unmatched event types
Called when no specific handler is registered for an event type. If not set, unmatched events are automatically acknowledged.
Parameters
handler Catch-all handler function
Implemented in muscovite::dba::NatsEventConsumer.
on_error()
virtual void muscovite::dba::EventConsumer::on_error (ErrorHandler handler) pure virtual
Register an error handler for exceptions
Called when an event handler throws an exception. Default behavior is to Nak the message (retry later).
Parameters
handler Error handler function
Implemented in muscovite::dba::NatsEventConsumer.
start()
virtual auto muscovite::dba::EventConsumer::start () -> bool nodiscard pure virtual
Start consuming events
Connects to the message broker and begins receiving events. Handlers are invoked on a background thread.
Returns
true if started successfully, false on error
Implemented in muscovite::dba::NatsEventConsumer.
stop()
virtual void muscovite::dba::EventConsumer::stop () pure virtual
Stop consuming events
Gracefully stops the consumer, waiting for in-flight handlers. Unacknowledged messages will be redelivered on restart.
Implemented in muscovite::dba::NatsEventConsumer.
The documentation for this class was generated from the following file:
framework/dba/include/muscovite/dba/event_consumer.hpp