Muscovite C++ Framework: muscovite::qt::widgets::EntityEditDialogBase Class Reference
muscovite::qt::widgets::EntityEditDialogBase Class Reference abstract
Base class for entity edit dialogs.
#include <entity_edit_dialog.hpp>
Public Types
enum class Mode { Create , Edit }
Signals
void entitySaved (const QString &entityId)
void saveFailed (const QString &error)
Public Member Functions
EntityEditDialogBase (QWidget *parent=nullptr)
muscovite::qt::AuthManager * authManager () const
std::shared_ptr<::grpc::Channel > channel () const
QString entityId () const
Mode mode () const
void setAuthManager (muscovite::qt::AuthManager *mgr)
void setChannel (std::shared_ptr<::grpc::Channel > channel)
void setCreateMode ()
void setEditMode (const QString &entityId)
Protected Slots
void onCancelClicked ()
void onSaveClicked ()
void onValidationChanged (const validation::ValidationResult &result)
Protected Member Functions
QCheckBox * addCheckBox (const QString &label, const QString &fieldName)
QComboBox * addComboBox (const QString &label, const QString &fieldName, bool required=false)
QDateEdit * addDateEdit (const QString &label, const QString &fieldName, bool required=false)
QDateTimeEdit * addDateTimeEdit (const QString &label, const QString &fieldName, bool required=false)
QDoubleSpinBox * addDoubleSpinBox (const QString &label, const QString &fieldName, double min=0, double max=100, int decimals=2, bool required=false)
QLineEdit * addLineEdit (const QString &label, const QString &fieldName, bool required=false)
QComboBox * addNullableComboBox (const QString &label, const QString &fieldName)
QDateEdit * addNullableDateEdit (const QString &label, const QString &fieldName)
QDateTimeEdit * addNullableDateTimeEdit (const QString &label, const QString &fieldName)
QTimeEdit * addNullableTimeEdit (const QString &label, const QString &fieldName)
QSpinBox * addSpinBox (const QString &label, const QString &fieldName, int min=0, int max=100, bool required=false)
QTextEdit * addTextEdit (const QString &label, const QString &fieldName, bool required=false)
QTimeEdit * addTimeEdit (const QString &label, const QString &fieldName, bool required=false)
QDialogButtonBox * buttonBox () const
void clearAllErrors ()
void clearError ()
void clearFieldError (QWidget *field)
virtual QString dialogTitleCreate () const
virtual QString dialogTitleEdit () const
virtual QString entityDisplayName () const
QFormLayout * formLayout () const
template<typename Response>
bool handleGrpcResult (const grpc::GrpcResult< Response > &result)
Handle a gRPC result that may contain validation errors.
bool handleValidationError (const ::grpc::ClientContext &ctx, const ::grpc::Status &status)
Handle validation errors from a synchronous gRPC call.
bool isLoading () const
std::unique_ptr<::grpc::ClientContext > makeContext (std::chrono::milliseconds deadline=std::chrono::seconds{10}) const
std::shared_ptr<::grpc::ClientContext > makeSharedContext (std::chrono::milliseconds deadline=std::chrono::seconds{10}) const
Create a shared gRPC context for async calls (GrpcCallTask pattern). The shared_ptr lifetime spans both the call lambda and done handler, allowing handleValidationError() to read trailing metadata after the call.
void markRequired (QWidget *field, const QString &displayLabel={})
virtual void populateFromEntity (const QString &entityId)=0
virtual void saveEntity ()=0
void setContentWidget (QWidget *widget)
void setError (const QString &error)
void setFieldError (QWidget *field, const QString &error)
void setLoading (bool loading)
virtual void setupFields ()=0
void showValidationResult (const validation::ValidationResult &result)
validation::EntityDialogStateMachine * stateMachine () const
virtual QString toJson () const
virtual bool validateFields ()
validation::ValidationDisplayWidget * validationDisplay () const
Detailed Description
Base class for entity edit dialogs.
Provides a modal dialog with:
QFormLayout for field editors (generated per-entity)
QDialogButtonBox with Save/Cancel buttons
Validation framework with field-level error display
Loading state during gRPC save operations
Support for both create (new entity) and edit (existing entity) modes
Subclasses (generated per-entity) must implement:
setupFields() - add field editors to the form layout
populateFromEntity(const QString& id) - load entity data for editing
collectToRequest() - gather field values into gRPC request
saveEntity() - call gRPC Create or Update method
Usage: auto* dialog = new ChemicalElementEditDialog(channel, authMgr, this); dialog->setEditMode(entityId); // or dialog->setCreateMode(); if (dialog->exec() == QDialog::Accepted) { listWidget->refresh(); }
Definition at line 66 of file entity_edit_dialog.hpp.
Member Enumeration Documentation
Mode
enum class muscovite::qt::widgets::EntityEditDialogBase::Mode strong
Definition at line 70 of file entity_edit_dialog.hpp.
Constructor & Destructor Documentation
EntityEditDialogBase()
muscovite::qt::widgets::EntityEditDialogBase::EntityEditDialogBase (QWidget * parent = nullptr) explicit
Definition at line 21 of file entity_edit_dialog.cpp.
Member Function Documentation
addCheckBox()
QCheckBox * muscovite::qt::widgets::EntityEditDialogBase::addCheckBox (const QString & label, const QString & fieldName) protected
Definition at line 173 of file entity_edit_dialog.cpp.
addComboBox()
QComboBox * muscovite::qt::widgets::EntityEditDialogBase::addComboBox (const QString & label, const QString & fieldName, bool required = false) protected
Definition at line 215 of file entity_edit_dialog.cpp.
addDateEdit()
QDateEdit * muscovite::qt::widgets::EntityEditDialogBase::addDateEdit (const QString & label, const QString & fieldName, bool required = false) protected
Definition at line 180 of file entity_edit_dialog.cpp.
addDateTimeEdit()
QDateTimeEdit * muscovite::qt::widgets::EntityEditDialogBase::addDateTimeEdit (const QString & label, const QString & fieldName, bool required = false) protected
Definition at line 192 of file entity_edit_dialog.cpp.
addDoubleSpinBox()
QDoubleSpinBox * muscovite::qt::widgets::EntityEditDialogBase::addDoubleSpinBox (const QString & label, const QString & fieldName, double min = 0, double max = 100, int decimals = 2, bool required = false) protected
Definition at line 161 of file entity_edit_dialog.cpp.
addLineEdit()
QLineEdit * muscovite::qt::widgets::EntityEditDialogBase::addLineEdit (const QString & label, const QString & fieldName, bool required = false) protected
Definition at line 140 of file entity_edit_dialog.cpp.
addNullableComboBox()
QComboBox * muscovite::qt::widgets::EntityEditDialogBase::addNullableComboBox (const QString & label, const QString & fieldName) protected
Definition at line 319 of file entity_edit_dialog.cpp.
addNullableDateEdit()
QDateEdit * muscovite::qt::widgets::EntityEditDialogBase::addNullableDateEdit (const QString & label, const QString & fieldName) protected
Definition at line 236 of file entity_edit_dialog.cpp.
addNullableDateTimeEdit()
QDateTimeEdit * muscovite::qt::widgets::EntityEditDialogBase::addNullableDateTimeEdit (const QString & label, const QString & fieldName) protected
Definition at line 264 of file entity_edit_dialog.cpp.
addNullableTimeEdit()
QTimeEdit * muscovite::qt::widgets::EntityEditDialogBase::addNullableTimeEdit (const QString & label, const QString & fieldName) protected
Definition at line 292 of file entity_edit_dialog.cpp.
addSpinBox()
QSpinBox * muscovite::qt::widgets::EntityEditDialogBase::addSpinBox (const QString & label, const QString & fieldName, int min = 0, int max = 100, bool required = false) protected
Definition at line 150 of file entity_edit_dialog.cpp.
addTextEdit()
QTextEdit * muscovite::qt::widgets::EntityEditDialogBase::addTextEdit (const QString & label, const QString & fieldName, bool required = false) protected
Definition at line 225 of file entity_edit_dialog.cpp.
addTimeEdit()
QTimeEdit * muscovite::qt::widgets::EntityEditDialogBase::addTimeEdit (const QString & label, const QString & fieldName, bool required = false) protected
Definition at line 204 of file entity_edit_dialog.cpp.
authManager()
muscovite::qt::AuthManager * muscovite::qt::widgets::EntityEditDialogBase::authManager () const inline
Definition at line 86 of file entity_edit_dialog.hpp.
buttonBox()
QDialogButtonBox * muscovite::qt::widgets::EntityEditDialogBase::buttonBox () const inline protected
Definition at line 106 of file entity_edit_dialog.hpp.
channel()
std::shared_ptr<::grpc::Channel > muscovite::qt::widgets::EntityEditDialogBase::channel () const inline
Definition at line 83 of file entity_edit_dialog.hpp.
clearAllErrors()
void muscovite::qt::widgets::EntityEditDialogBase::clearAllErrors () protected
Definition at line 419 of file entity_edit_dialog.cpp.
clearError()
void muscovite::qt::widgets::EntityEditDialogBase::clearError () protected
Definition at line 522 of file entity_edit_dialog.cpp.
clearFieldError()
void muscovite::qt::widgets::EntityEditDialogBase::clearFieldError (QWidget * field) protected
Definition at line 408 of file entity_edit_dialog.cpp.
dialogTitleCreate()
virtual QString muscovite::qt::widgets::EntityEditDialogBase::dialogTitleCreate () const inline protected virtual
Definition at line 101 of file entity_edit_dialog.hpp.
dialogTitleEdit()
virtual QString muscovite::qt::widgets::EntityEditDialogBase::dialogTitleEdit () const inline protected virtual
Definition at line 102 of file entity_edit_dialog.hpp.
entityDisplayName()
virtual QString muscovite::qt::widgets::EntityEditDialogBase::entityDisplayName () const inline protected virtual
Definition at line 100 of file entity_edit_dialog.hpp.
entityId()
QString muscovite::qt::widgets::EntityEditDialogBase::entityId () const inline
Definition at line 79 of file entity_edit_dialog.hpp.
formLayout()
QFormLayout * muscovite::qt::widgets::EntityEditDialogBase::formLayout () const inline protected
Definition at line 105 of file entity_edit_dialog.hpp.
handleGrpcResult()
template<typename Response> bool muscovite::qt::widgets::EntityEditDialogBase::handleGrpcResult (const grpc::GrpcResult< Response > & result) inline protected
Handle a gRPC result that may contain validation errors.
If the result has a validation error, extracts it, converts to ValidationResult, and shows it in the validation display. Also maps field errors to inline field displays.
Template Parameters
Response gRPC response type
Parameters
result The result from a gRPC call
Returns
true if no validation error, false if validation error was shown
Definition at line 179 of file entity_edit_dialog.hpp.
References muscovite::qt::grpc::GrpcResult< Response >::hasValidationError().
handleValidationError()
bool muscovite::qt::widgets::EntityEditDialogBase::handleValidationError (const ::grpc::ClientContext & ctx, const ::grpc::Status & status) inline protected
Handle validation errors from a synchronous gRPC call.
Extracts validation metadata from the ClientContext's trailing metadata and shows any validation errors in the dialog's validation display.
Parameters
ctx The ClientContext after the gRPC call (must be called after stub->Method())
status The gRPC status returned from the call
Returns
true if no validation error (call succeeded or failed without validation), false if a validation error was extracted and shown
Example usage in generated code:
auto status = stub->CreateEntity(ctx.get(), request, &response);
if (!handleValidationError(*ctx, status)) return;  // Validation error shown
Definition at line 210 of file entity_edit_dialog.hpp.
isLoading()
bool muscovite::qt::widgets::EntityEditDialogBase::isLoading () const inline protected
Definition at line 133 of file entity_edit_dialog.hpp.
makeContext()
std::unique_ptr<::grpc::ClientContext > muscovite::qt::widgets::EntityEditDialogBase::makeContext (std::chrono::milliseconds deadline = std::chrono::seconds{10}) const protected
Definition at line 526 of file entity_edit_dialog.cpp.
makeSharedContext()
std::shared_ptr<::grpc::ClientContext > muscovite::qt::widgets::EntityEditDialogBase::makeSharedContext (std::chrono::milliseconds deadline = std::chrono::seconds{10}) const protected
Create a shared gRPC context for async calls (GrpcCallTask pattern). The shared_ptr lifetime spans both the call lambda and done handler, allowing handleValidationError() to read trailing metadata after the call.
See also
ADR 20260303-tasktree-adoption, FTR-194
Definition at line 539 of file entity_edit_dialog.cpp.
References makeSharedContext().
Referenced by makeSharedContext().
markRequired()
void muscovite::qt::widgets::EntityEditDialogBase::markRequired (QWidget * field, const QString & displayLabel = {}) protected
Definition at line 343 of file entity_edit_dialog.cpp.
mode()
Mode muscovite::qt::widgets::EntityEditDialogBase::mode () const inline
Definition at line 78 of file entity_edit_dialog.hpp.
onCancelClicked
void muscovite::qt::widgets::EntityEditDialogBase::onCancelClicked () protected slot
Definition at line 561 of file entity_edit_dialog.cpp.
onSaveClicked
void muscovite::qt::widgets::EntityEditDialogBase::onSaveClicked () protected slot
Definition at line 552 of file entity_edit_dialog.cpp.
onValidationChanged
void muscovite::qt::widgets::EntityEditDialogBase::onValidationChanged (const validation::ValidationResult & result) protected slot
Definition at line 587 of file entity_edit_dialog.cpp.
setAuthManager()
void muscovite::qt::widgets::EntityEditDialogBase::setAuthManager (muscovite::qt::AuthManager * mgr) inline
Definition at line 85 of file entity_edit_dialog.hpp.
setChannel()
void muscovite::qt::widgets::EntityEditDialogBase::setChannel (std::shared_ptr<::grpc::Channel > channel) inline
Definition at line 82 of file entity_edit_dialog.hpp.
setContentWidget()
void muscovite::qt::widgets::EntityEditDialogBase::setContentWidget (QWidget * widget) protected
Definition at line 372 of file entity_edit_dialog.cpp.
setCreateMode()
void muscovite::qt::widgets::EntityEditDialogBase::setCreateMode ()
Definition at line 117 of file entity_edit_dialog.cpp.
setEditMode()
void muscovite::qt::widgets::EntityEditDialogBase::setEditMode (const QString & entityId)
Definition at line 124 of file entity_edit_dialog.cpp.
setError()
void muscovite::qt::widgets::EntityEditDialogBase::setError (const QString & error) protected
Definition at line 513 of file entity_edit_dialog.cpp.
setFieldError()
void muscovite::qt::widgets::EntityEditDialogBase::setFieldError (QWidget * field, const QString & error) protected
Definition at line 385 of file entity_edit_dialog.cpp.
setLoading()
void muscovite::qt::widgets::EntityEditDialogBase::setLoading (bool loading) protected
Definition at line 501 of file entity_edit_dialog.cpp.
showValidationResult()
void muscovite::qt::widgets::EntityEditDialogBase::showValidationResult (const validation::ValidationResult & result) protected
Definition at line 576 of file entity_edit_dialog.cpp.
stateMachine()
validation::EntityDialogStateMachine * muscovite::qt::widgets::EntityEditDialogBase::stateMachine () const inline protected
Definition at line 159 of file entity_edit_dialog.hpp.
toJson()
virtual QString muscovite::qt::widgets::EntityEditDialogBase::toJson () const inline protected virtual
Definition at line 152 of file entity_edit_dialog.hpp.
validateFields()
bool muscovite::qt::widgets::EntityEditDialogBase::validateFields () protected virtual
Definition at line 429 of file entity_edit_dialog.cpp.
validationDisplay()
validation::ValidationDisplayWidget * muscovite::qt::widgets::EntityEditDialogBase::validationDisplay () const inline protected
Definition at line 162 of file entity_edit_dialog.hpp.
The documentation for this class was generated from the following files:
framework/qt/include/muscovite/qt/widgets/entity_edit_dialog.hpp
framework/qt/src/widgets/entity_edit_dialog.cpp