Muscovite C++ Framework: muscovite::geo::Polygon< Srid > Class Template Reference
muscovite::geo::Polygon< Srid > Class Template Reference
Geographic polygon (closed ring, optionally with holes).
#include <geography.hpp>
Public Types
using point_type = Point<Srid>
using srid_tag = Srid
Public Member Functions
Polygon ()=default
Default constructor (empty polygon).
Polygon (const std::vector< point_type > &outer_ring)
Construct outer ring from vector of points.
Polygon (std::initializer_list< point_type > outer_ring)
Construct from initializer list.
void add_hole (const std::vector< point_type > &hole)
Add a hole (interior ring).
double area_sq_meters () const
Calculate area in square meters (geodetic).
BoundingBox< Srid > bounds () const
Get bounding box of this polygon.
bool contains (const point_type &point) const
Check if a point is within this polygon.
bool empty () const noexcept
Check if polygon is empty.
const bg_polygon & native () const noexcept
Access underlying Boost.Geometry polygon.
bg_polygon & native () noexcept
std::size_t num_holes () const noexcept
Number of holes.
std::size_t outer_size () const noexcept
Number of points in outer ring.
std::string to_ewkt () const
Convert to EWKT.
std::string to_wkt () const
Convert to WKT.
Static Public Attributes
static constexpr int srid = Srid::value
Detailed Description
template<SridTag Srid>
class muscovite::geo::Polygon< Srid >
Geographic polygon (closed ring, optionally with holes).
Template Parameters
Srid SRID tag type
Definition at line 507 of file geography.hpp.
Member Typedef Documentation
point_type
template<SridTag Srid> using muscovite::geo::Polygon< Srid >::point_type = Point<Srid>
Definition at line 511 of file geography.hpp.
srid_tag
template<SridTag Srid> using muscovite::geo::Polygon< Srid >::srid_tag = Srid
Definition at line 509 of file geography.hpp.
Constructor & Destructor Documentation
Polygon() [1/2]
template<SridTag Srid> muscovite::geo::Polygon< Srid >::Polygon (const std::vector< point_type > & outer_ring) inline explicit
Construct outer ring from vector of points.
Note
First and last point should be the same (closed ring)
Definition at line 524 of file geography.hpp.
Polygon() [2/2]
template<SridTag Srid> muscovite::geo::Polygon< Srid >::Polygon (std::initializer_list< point_type > outer_ring) inline
Construct from initializer list.
Definition at line 531 of file geography.hpp.
Member Function Documentation
add_hole()
template<SridTag Srid> void muscovite::geo::Polygon< Srid >::add_hole (const std::vector< point_type > & hole) inline
Add a hole (interior ring).
Definition at line 538 of file geography.hpp.
area_sq_meters()
template<SridTag Srid> double muscovite::geo::Polygon< Srid >::area_sq_meters () const inline nodiscard
Calculate area in square meters (geodetic).
Definition at line 565 of file geography.hpp.
Referenced by muscovite::geo::MultiPolygon< srid_4326 >::total_area_sq_meters().
bounds()
template<SridTag Srid> BoundingBox< Srid > muscovite::geo::Polygon< Srid >::bounds () const inline nodiscard
Get bounding box of this polygon.
Definition at line 608 of file geography.hpp.
contains()
template<SridTag Srid> bool muscovite::geo::Polygon< Srid >::contains (const point_type & point) const inline nodiscard
Check if a point is within this polygon.
Definition at line 571 of file geography.hpp.
Referenced by muscovite::geo::MultiPolygon< srid_4326 >::contains().
empty()
template<SridTag Srid> bool muscovite::geo::Polygon< Srid >::empty () const inline nodiscard noexcept
Check if polygon is empty.
Definition at line 556 of file geography.hpp.
Referenced by muscovite::geo::Polygon< srid_4326 >::bounds(), and muscovite::geo::Polygon< srid_4326 >::to_wkt().
native() [1/2]
template<SridTag Srid> const bg_polygon & muscovite::geo::Polygon< Srid >::native () const inline nodiscard noexcept
Access underlying Boost.Geometry polygon.
Definition at line 561 of file geography.hpp.
native() [2/2]
template<SridTag Srid> bg_polygon & muscovite::geo::Polygon< Srid >::native () inline nodiscard noexcept
Definition at line 562 of file geography.hpp.
num_holes()
template<SridTag Srid> std::size_t muscovite::geo::Polygon< Srid >::num_holes () const inline nodiscard noexcept
Number of holes.
Definition at line 551 of file geography.hpp.
outer_size()
template<SridTag Srid> std::size_t muscovite::geo::Polygon< Srid >::outer_size () const inline nodiscard noexcept
Number of points in outer ring.
Definition at line 546 of file geography.hpp.
to_ewkt()
template<SridTag Srid> std::string muscovite::geo::Polygon< Srid >::to_ewkt () const inline nodiscard
Convert to EWKT.
Definition at line 603 of file geography.hpp.
to_wkt()
template<SridTag Srid> std::string muscovite::geo::Polygon< Srid >::to_wkt () const inline nodiscard
Convert to WKT.
Definition at line 577 of file geography.hpp.
Referenced by muscovite::geo::Polygon< srid_4326 >::to_ewkt().
Member Data Documentation
srid
template<SridTag Srid> int muscovite::geo::Polygon< Srid >::srid = Srid::value static constexpr
Definition at line 510 of file geography.hpp.
The documentation for this class was generated from the following file:
framework/geo/include/muscovite/geo/geography.hpp