Muscovite C++ Framework: muscovite::qt::QtEmail Class Reference
muscovite::qt::QtEmail Class Reference
Public Member Functions
auto domain () const -> QString
Extract domain part (after).
auto localPart () const -> QString
Extract local part (before).
QtTypeBase ()=default
Default constructor creates empty value.
QtTypeBase (const char *value)
Construct from C string with validation.
QtTypeBase (const QString &value)
Construct with validation.
QtTypeBase (const std::string &value)
Construct from std::string with validation.
Public Member Functions inherited from muscovite::qt::QtTypeBase< QtEmail >
QtTypeBase ()=default
Default constructor creates empty value.
auto isEmpty () const noexcept -> bool
Check if empty.
auto operator!= (const QtTypeBase &other) const noexcept -> bool
Inequality comparison.
auto operator< (const QtTypeBase &other) const noexcept -> bool
Less-than for sorting.
auto operator== (const QtTypeBase &other) const noexcept -> bool
Equality comparison.
auto toStdString () const -> std::string
Convert to std::string.
auto toString () const noexcept -> QString
Convert to QString (alias for value()).
auto toVariant () const -> QVariant
Convert to QVariant for model/view.
auto value () const noexcept -> const QString &
Get the underlying QString value.
Static Public Member Functions
static auto isValid (QStringView value) -> bool
Validate email format.
static auto pattern () -> QString
Validation pattern (matches PostgreSQL CHECK).
static auto typeName () -> QString
Type name for error messages.
Static Public Member Functions inherited from muscovite::qt::QtTypeBase< QtEmail >
static auto fromTrusted (QString value) noexcept -> QtEmail
Construct from trusted source without validation.
Additional Inherited Members
Protected Attributes inherited from muscovite::qt::QtTypeBase< QtEmail >
QString value_
Detailed Description
Examples
/home/jolo/muscovite/framework/qt/include/muscovite/qt/types/qt_email.hpp.
Definition at line 27 of file qt_email.hpp.
Member Function Documentation
domain()
auto muscovite::qt::QtEmail::domain () const -> QString inline nodiscard
Extract domain part (after).
Examples
/home/jolo/muscovite/framework/qt/include/muscovite/qt/types/qt_email.hpp.
Definition at line 56 of file qt_email.hpp.
isValid()
auto muscovite::qt::QtEmail::isValid (QStringView value) -> bool inline static nodiscard
Validate email format.
Examples
/home/jolo/muscovite/framework/qt/include/muscovite/qt/types/qt_email.hpp.
Definition at line 42 of file qt_email.hpp.
References pattern(), and muscovite::qt::QtTypeBase< QtEmail >::value().
localPart()
auto muscovite::qt::QtEmail::localPart () const -> QString inline nodiscard
Extract local part (before).
Examples
/home/jolo/muscovite/framework/qt/include/muscovite/qt/types/qt_email.hpp.
Definition at line 49 of file qt_email.hpp.
pattern()
auto muscovite::qt::QtEmail::pattern () -> QString inline static nodiscard
Validation pattern (matches PostgreSQL CHECK).
Examples
/home/jolo/muscovite/framework/qt/include/muscovite/qt/types/qt_email.hpp.
Definition at line 37 of file qt_email.hpp.
Referenced by isValid().
QtTypeBase() [1/3]
muscovite::qt::QtTypeBase< Derived >::QtTypeBase (const char * value) inline explicit
Construct from C string with validation.
Definition at line 61 of file qt_type_base.hpp.
QtTypeBase() [2/3]
muscovite::qt::QtTypeBase< Derived >::QtTypeBase (const QString & value) inline explicit
Construct with validation.
Parameters
value The string value to wrap
Exceptions
std::invalid_argument if validation fails
Definition at line 47 of file qt_type_base.hpp.
QtTypeBase() [3/3]
muscovite::qt::QtTypeBase< Derived >::QtTypeBase (const std::string & value) inline explicit
Construct from std::string with validation.
Definition at line 57 of file qt_type_base.hpp.
typeName()
auto muscovite::qt::QtEmail::typeName () -> QString inline static nodiscard
Type name for error messages.
Examples
/home/jolo/muscovite/framework/qt/include/muscovite/qt/types/qt_email.hpp.
Definition at line 32 of file qt_email.hpp.
The documentation for this class was generated from the following file:
framework/qt/include/muscovite/qt/types/qt_email.hpp