Muscovite C++ Framework: muscovite::qt::validation::EntityValidator Class Reference
muscovite::qt::validation::EntityValidator Class Reference
Base class for entity validators. Generated validators inherit this and override buildFieldRules().
#include <entity_validator.hpp>
Signals
void allAsyncCompleted ()
void asyncValidationCompleted (const QString &_t1, bool _t2)
void asyncValidationStarted (const QString &_t1)
void validationChanged (const ValidationResult &_t1)
Public Member Functions
EntityValidator (QObject *parent=nullptr)
const ValidationResult & currentResult () const
Get the current validation result.
bool hasAsyncPending () const
Check if async validations are pending.
bool hasWarnings () const
Check if the form has warnings.
void initialize ()
Initialize validator with widgets. Calls buildFieldRules() and wires signals.
bool isValid () const
Check if the form is valid (no errors, no pending async).
QSet< QString > pendingAsyncFields () const
Get list of fields with pending async validation.
ValidationResult validateAll ()
Validate all fields including arc constraints.
ValidationResult validateField (const QString &fieldId)
Validate a specific field by ID.
Protected Member Functions
virtual void addCustomValidations ()
Override to add custom application-specific validations.
virtual QList< FieldValidationRule > buildFieldRules () const
Override to define field validation rules (called during initialize).
ValidationResult & result ()
Access to the current result for custom validations.
Static Protected Member Functions
static QString getWidgetValue (QWidget *widget)
Helper to get text value from any widget.
static bool widgetHasValue (QWidget *widget)
Helper to check if a widget has content.
Detailed Description
Base class for entity validators. Generated validators inherit this and override buildFieldRules().
Definition at line 27 of file entity_validator.hpp.
Constructor & Destructor Documentation
EntityValidator()
muscovite::qt::validation::EntityValidator::EntityValidator (QObject * parent = nullptr) explicit
Definition at line 28 of file entity_validator.cpp.
Member Function Documentation
addCustomValidations()
virtual void muscovite::qt::validation::EntityValidator::addCustomValidations () inline protected virtual
Override to add custom application-specific validations.
Definition at line 61 of file entity_validator.hpp.
Referenced by validateAll().
buildFieldRules()
virtual QList< FieldValidationRule > muscovite::qt::validation::EntityValidator::buildFieldRules () const inline nodiscard protected virtual
Override to define field validation rules (called during initialize).
Definition at line 59 of file entity_validator.hpp.
Referenced by initialize().
currentResult()
const ValidationResult & muscovite::qt::validation::EntityValidator::currentResult () const inline nodiscard
Get the current validation result.
Definition at line 41 of file entity_validator.hpp.
getWidgetValue()
QString muscovite::qt::validation::EntityValidator::getWidgetValue (QWidget * widget) static protected
Helper to get text value from any widget.
Definition at line 327 of file entity_validator.cpp.
References getWidgetValue().
Referenced by getWidgetValue().
hasAsyncPending()
bool muscovite::qt::validation::EntityValidator::hasAsyncPending () const inline nodiscard
Check if async validations are pending.
Definition at line 43 of file entity_validator.hpp.
Referenced by isValid().
hasWarnings()
bool muscovite::qt::validation::EntityValidator::hasWarnings () const inline nodiscard
Check if the form has warnings.
Definition at line 49 of file entity_validator.hpp.
initialize()
void muscovite::qt::validation::EntityValidator::initialize ()
Initialize validator with widgets. Calls buildFieldRules() and wires signals.
Definition at line 33 of file entity_validator.cpp.
References buildFieldRules(), and initialize().
Referenced by initialize().
isValid()
bool muscovite::qt::validation::EntityValidator::isValid () const inline nodiscard
Check if the form is valid (no errors, no pending async).
Definition at line 47 of file entity_validator.hpp.
References hasAsyncPending().
pendingAsyncFields()
QSet< QString > muscovite::qt::validation::EntityValidator::pendingAsyncFields () const inline nodiscard
Get list of fields with pending async validation.
Definition at line 45 of file entity_validator.hpp.
result()
ValidationResult & muscovite::qt::validation::EntityValidator::result () inline protected
Access to the current result for custom validations.
Definition at line 63 of file entity_validator.hpp.
validateAll()
ValidationResult muscovite::qt::validation::EntityValidator::validateAll ()
Validate all fields including arc constraints.
Definition at line 138 of file entity_validator.cpp.
References addCustomValidations(), and validateAll().
Referenced by validateAll().
validateField()
ValidationResult muscovite::qt::validation::EntityValidator::validateField (const QString & fieldId)
Validate a specific field by ID.
Definition at line 155 of file entity_validator.cpp.
References validateField().
Referenced by validateField().
widgetHasValue()
bool muscovite::qt::validation::EntityValidator::widgetHasValue (QWidget * widget) static protected
Helper to check if a widget has content.
Definition at line 355 of file entity_validator.cpp.
References widgetHasValue().
Referenced by widgetHasValue().
The documentation for this class was generated from the following files:
framework/qt/include/muscovite/qt/validation/entity_validator.hpp
framework/qt/src/validation/entity_validator.cpp