Muscovite C++ Framework: muscovite::search::SearchReindexer Class Reference
muscovite::search::SearchReindexer Class Reference
Bulk reindexer for OpenSearch.
#include <search_reindexer.hpp>
Public Member Functions
SearchReindexer (const SearchReindexer &)=delete
SearchReindexer (OpenSearchClient &client)
Construct a reindexer with an OpenSearch client.
SearchReindexer (SearchReindexer &&)=delete
SearchReindexer & operator= (const SearchReindexer &)=delete
SearchReindexer & operator= (SearchReindexer &&)=delete
void register_mapper (std::shared_ptr< BulkDocumentMapper > mapper)
Register a bulk document mapper for reindexing.
auto registered_types () const -> std::vector< std::string >
List registered entity types.
auto reindex_all (const ReindexConfig &config={}, const ReindexProgressCallback &on_progress=nullptr) -> ReindexResult
Reindex all registered entity types.
auto reindex_entity (const std::string &entity_type, const ReindexConfig &config={}, const ReindexProgressCallback &on_progress=nullptr) -> ReindexEntityResult
Reindex a single entity type.
Detailed Description
Bulk reindexer for OpenSearch.
Iterates all registered BulkDocumentMappers, fetches pages of entities, and submits them to OpenSearch via the _bulk API. Supports progress callbacks for CLI reporting.
Usage:
OpenSearchClient client(config);
SearchReindexer reindexer(client);
auto mapper = std::make_shared<PatientBulkMapper>(query_repo);
reindexer.register_mapper(mapper);
auto result = reindexer.reindex_all(ReindexConfig{.batch_size = 500},
    [](auto& type, auto processed, auto total) {
        spdlog::info("Reindexing {}: {}/{}", type, processed, total);
    });
See also
BulkDocumentMapper for entity-specific bulk fetch
OpenSearchClient::bulk() for NDJSON submission
Definition at line 174 of file search_reindexer.hpp.
Constructor & Destructor Documentation
SearchReindexer()
muscovite::search::SearchReindexer::SearchReindexer (OpenSearchClient & client) explicit
Construct a reindexer with an OpenSearch client.
Parameters
client Reference to OpenSearchClient (must outlive the reindexer)
Definition at line 71 of file search_reindexer.cpp.
Member Function Documentation
register_mapper()
void muscovite::search::SearchReindexer::register_mapper (std::shared_ptr< BulkDocumentMapper > mapper)
Register a bulk document mapper for reindexing.
Parameters
mapper Shared pointer to BulkDocumentMapper
Exceptions
std::logic_error if mapper for this entity type already registered
Definition at line 78 of file search_reindexer.cpp.
registered_types()
auto muscovite::search::SearchReindexer::registered_types () const -> std::vector< std::string > nodiscard
List registered entity types.
Definition at line 201 of file search_reindexer.cpp.
Referenced by reindex_all().
reindex_all()
auto muscovite::search::SearchReindexer::reindex_all (const ReindexConfig & config = {}, const ReindexProgressCallback & on_progress = nullptr) -> ReindexResult
Reindex all registered entity types.
For each mapper:
Drop index (if recreate_indexes=true and index exists)
Create index with mapper's mapping
Paginated fetch → NDJSON bulk → submit
Report progress via callback
Errors for one entity type do not prevent reindexing others.
Parameters
config Reindex configuration (batch size, recreate flag)
on_progress Optional progress callback
Returns
Aggregate result with per-entity details
Definition at line 94 of file search_reindexer.cpp.
References muscovite::search::ReindexResult::entity_results, registered_types(), reindex_entity(), muscovite::search::ReindexResult::total_failed(), and muscovite::search::ReindexResult::total_indexed().
reindex_entity()
auto muscovite::search::SearchReindexer::reindex_entity (const std::string & entity_type, const ReindexConfig & config = {}, const ReindexProgressCallback & on_progress = nullptr) -> ReindexEntityResult
Reindex a single entity type.
Parameters
entity_type Entity type to reindex (must have registered mapper)
config Reindex configuration
on_progress Optional progress callback
Returns
Result for this entity type
Exceptions
std::invalid_argument if no mapper for entity_type
Definition at line 113 of file search_reindexer.cpp.
References muscovite::search::ReindexEntityResult::batches, muscovite::search::ReindexEntityResult::documents_failed, muscovite::search::ReindexEntityResult::documents_indexed, muscovite::search::ReindexEntityResult::entity_type, muscovite::search::ReindexEntityResult::error, muscovite::search::ReindexEntityResult::index_name, and muscovite::search::ReindexEntityResult::success.
Referenced by reindex_all().
The documentation for this class was generated from the following files:
framework/search/include/muscovite/search/search_reindexer.hpp
framework/search/src/search_reindexer.cpp