Muscovite C++ Framework: muscovite::messaging::NatsPublisher Class Reference
muscovite::messaging::NatsPublisher Class Reference final
#include <nats_publisher.hpp>
Public Member Functions
NatsPublisher (const NatsPublisher &)=delete
NatsPublisher (NatsPublisher &&) noexcept
NatsPublisher (NatsPublisherConfig config)
Create a NATS publisher.
auto connect () -> bool override
Connect to NATS and initialize JetStream context.
void disconnect () override
Disconnect from NATS.
auto ensure_infrastructure (const std::string &stream_name, const std::string &subject_prefix) -> bool override
Ensure JetStream stream exists.
auto is_connected () const -> bool override
Check connection status.
auto last_error () const -> std::string override
Get last error.
auto messages_published () const -> std::uint64_t override
Get published message count.
NatsPublisher & operator= (const NatsPublisher &)=delete
NatsPublisher & operator= (NatsPublisher &&) noexcept
auto publish (const MessageEnvelope &envelope) -> PublishResult override
Publish message to JetStream.
auto publish_acked (const MessageEnvelope &envelope) -> std::optional< PublishAck > override
Publish with acknowledgment details.
Detailed Description
NATS JetStream publisher implementation
Thread-safe. Multiple threads can call publish() concurrently. Automatically reconnects on connection loss.
See also
muscovite::dba::NatsMessageBroker for the DBA-layer outbox publisher
Definition at line 56 of file nats_publisher.hpp.
Constructor & Destructor Documentation
NatsPublisher() [1/2]
muscovite::messaging::NatsPublisher::NatsPublisher (NatsPublisherConfig config) explicit
Create a NATS publisher.
Parameters
config Connection configuration
Definition at line 18 of file nats_publisher.cpp.
~NatsPublisher()
muscovite::messaging::NatsPublisher::~NatsPublisher () override
Definition at line 21 of file nats_publisher.cpp.
NatsPublisher() [2/2]
muscovite::messaging::NatsPublisher::NatsPublisher (NatsPublisher && other) noexcept
Definition at line 25 of file nats_publisher.cpp.
Member Function Documentation
connect()
auto muscovite::messaging::NatsPublisher::connect () -> bool nodiscard override virtual
Connect to NATS and initialize JetStream context.
Implements muscovite::messaging::Publisher.
Definition at line 52 of file nats_publisher.cpp.
disconnect()
void muscovite::messaging::NatsPublisher::disconnect () override virtual
Disconnect from NATS.
Implements muscovite::messaging::Publisher.
Definition at line 105 of file nats_publisher.cpp.
ensure_infrastructure()
auto muscovite::messaging::NatsPublisher::ensure_infrastructure (const std::string & stream_name, const std::string & subject_prefix) -> bool nodiscard override virtual
Ensure JetStream stream exists.
Parameters
stream_name Stream name
subject_prefix Subject prefix (e.g., "muscovite.patient")
Returns
true if stream ready, false on error
Implements muscovite::messaging::Publisher.
Definition at line 179 of file nats_publisher.cpp.
is_connected()
auto muscovite::messaging::NatsPublisher::is_connected () const -> bool nodiscard override virtual
Check connection status.
Implements muscovite::messaging::Publisher.
Definition at line 109 of file nats_publisher.cpp.
Referenced by publish().
last_error()
auto muscovite::messaging::NatsPublisher::last_error () const -> std::string nodiscard override virtual
Get last error.
Implements muscovite::messaging::Publisher.
Definition at line 234 of file nats_publisher.cpp.
messages_published()
auto muscovite::messaging::NatsPublisher::messages_published () const -> std::uint64_t nodiscard override virtual
Get published message count.
Implements muscovite::messaging::Publisher.
Definition at line 238 of file nats_publisher.cpp.
operator=()
NatsPublisher & muscovite::messaging::NatsPublisher::operator= (NatsPublisher && other) noexcept
Definition at line 37 of file nats_publisher.cpp.
publish()
auto muscovite::messaging::NatsPublisher::publish (const MessageEnvelope & envelope) -> PublishResult nodiscard override virtual
Publish message to JetStream.
Parameters
envelope Message envelope with subject, payload, and metadata
Returns
PublishResult indicating success or error type
Implements muscovite::messaging::Publisher.
Definition at line 116 of file nats_publisher.cpp.
References is_connected(), and publish_acked().
publish_acked()
auto muscovite::messaging::NatsPublisher::publish_acked (const MessageEnvelope & envelope) -> std::optional< PublishAck > nodiscard override virtual
Publish with acknowledgment details.
Parameters
envelope Message to publish
Returns
PublishAck on success, nullopt on error
Implements muscovite::messaging::Publisher.
Definition at line 130 of file nats_publisher.cpp.
Referenced by publish().
The documentation for this class was generated from the following files:
framework/messaging/include/muscovite/messaging/nats_publisher.hpp
framework/messaging/src/nats_publisher.cpp