Muscovite C++ Framework: muscovite::types::PositiveDecimal Class Reference
muscovite::types::PositiveDecimal Class Reference
Public Member Functions
PositiveDecimal (double value)
Construct from numeric value.
strong_type_base ()=default
Default constructor creates empty value.
strong_type_base (std::string_view value)
Construct with validation.
auto to_double () const -> double
Convert to double (may lose precision for very large values).
Public Member Functions inherited from muscovite::types::strong_type_base< PositiveDecimal >
strong_type_base ()=default
Default constructor creates empty value.
auto empty () const noexcept -> bool
Check if empty.
operator std::string_view () const noexcept
Implicit conversion to string_view for compatibility.
auto operator<=> (const strong_type_base &other) const noexcept=default
Three-way comparison.
auto operator== (const strong_type_base &other) const noexcept -> bool=default
Equality comparison.
auto value () const noexcept -> const std::string &
Get the underlying string value.
Static Public Member Functions
static auto is_valid (std::string_view value) noexcept -> bool
Validate positive decimal format.
static constexpr auto pattern () noexcept -> std::string_view
Validation pattern (numeric with optional decimal point).
static constexpr auto type_name () noexcept -> std::string_view
Type name for error messages.
Static Public Member Functions inherited from muscovite::types::strong_type_base< PositiveDecimal >
static auto from_trusted (std::string value) noexcept -> PositiveDecimal
Construct from trusted source without validation.
Additional Inherited Members
Protected Attributes inherited from muscovite::types::strong_type_base< PositiveDecimal >
std::string value_
Detailed Description
Definition at line 36 of file positive_decimal.hpp.
Constructor & Destructor Documentation
PositiveDecimal()
muscovite::types::PositiveDecimal::PositiveDecimal (double value) inline explicit
Construct from numeric value.
Parameters
value Positive numeric value
Exceptions
invalid_value_error if value <= 0
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/positive_decimal.hpp.
Definition at line 86 of file positive_decimal.hpp.
References strong_type_base(), type_name(), and muscovite::types::strong_type_base< PositiveDecimal >::value().
Member Function Documentation
is_valid()
auto muscovite::types::PositiveDecimal::is_valid (std::string_view value) -> bool inline static nodiscard noexcept
Validate positive decimal format.
Parameters
value String to validate
Returns
true if valid positive decimal
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/positive_decimal.hpp.
Definition at line 53 of file positive_decimal.hpp.
References pattern(), and muscovite::types::strong_type_base< PositiveDecimal >::value().
pattern()
constexpr auto muscovite::types::PositiveDecimal::pattern () -> std::string_view inline static nodiscard constexpr noexcept
Validation pattern (numeric with optional decimal point).
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/positive_decimal.hpp.
Definition at line 46 of file positive_decimal.hpp.
References muscovite::types::strong_type_base< PositiveDecimal >::operator std::string_view().
Referenced by is_valid().
strong_type_base()
muscovite::types::strong_type_base< Derived >::strong_type_base (std::string_view value) inline explicit
Construct with validation.
Parameters
value The string value to wrap
Exceptions
invalid_value_error if validation fails
Definition at line 71 of file strong_type_base.hpp.
to_double()
auto muscovite::types::PositiveDecimal::to_double () const -> double inline nodiscard
Convert to double (may lose precision for very large values).
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/positive_decimal.hpp.
Definition at line 77 of file positive_decimal.hpp.
type_name()
constexpr auto muscovite::types::PositiveDecimal::type_name () -> std::string_view inline static nodiscard constexpr noexcept
Type name for error messages.
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/positive_decimal.hpp.
Definition at line 41 of file positive_decimal.hpp.
References muscovite::types::strong_type_base< PositiveDecimal >::operator std::string_view().
Referenced by PositiveDecimal().
The documentation for this class was generated from the following file:
framework/types/include/muscovite/types/positive_decimal.hpp