Muscovite C++ Framework: muscovite::server::security::AuthInterceptorFactory Class Reference
muscovite::server::security::AuthInterceptorFactory Class Reference
Factory for creating auth interceptors.
#include <auth_interceptor.hpp>
Public Member Functions
AuthInterceptorFactory (std::shared_ptr< AuthenticationService > auth_service, std::shared_ptr< AuthorizationService > authz_service)
Construct the factory.
AuthInterceptorFactory & add_public_method (const std::string &method)
Add a public method (no authentication required).
AuthInterceptorFactory & add_public_methods (const std::vector< std::string > &methods)
Add multiple public methods.
std::unique_ptr< AuthInterceptor > build ()
Build an interceptor configured with current settings.
std::vector< std::unique_ptr< grpc::experimental::ServerInterceptorFactoryInterface > > build_interceptor_creators ()
Build creators usable with gRPC server options.
grpc::experimental::Interceptor * CreateServerInterceptor (grpc::experimental::ServerRpcInfo *info) override
AuthInterceptorFactory & require_any_privilege (const std::string &method, const std::vector< std::string > &privileges)
Require any of the provided privileges for a specific method.
AuthInterceptorFactory & require_privilege (const std::string &method, const std::string &privilege)
Require a privilege for a specific method.
Detailed Description
Factory for creating auth interceptors.
Definition at line 75 of file auth_interceptor.hpp.
Constructor & Destructor Documentation
AuthInterceptorFactory()
muscovite::server::security::AuthInterceptorFactory::AuthInterceptorFactory (std::shared_ptr< AuthenticationService > auth_service, std::shared_ptr< AuthorizationService > authz_service)
Construct the factory.
Parameters
auth_service Authentication service.
authz_service Authorization service.
Definition at line 192 of file auth_interceptor.cpp.
Referenced by add_public_method(), add_public_methods(), require_any_privilege(), and require_privilege().
Member Function Documentation
add_public_method()
AuthInterceptorFactory & muscovite::server::security::AuthInterceptorFactory::add_public_method (const std::string & method)
Add a public method (no authentication required).
Parameters
method Full method name (e.g., "/muscovite.security.AuthService/Login").
Definition at line 198 of file auth_interceptor.cpp.
References AuthInterceptorFactory().
add_public_methods()
AuthInterceptorFactory & muscovite::server::security::AuthInterceptorFactory::add_public_methods (const std::vector< std::string > & methods)
Add multiple public methods.
Definition at line 203 of file auth_interceptor.cpp.
References AuthInterceptorFactory().
build()
std::unique_ptr< AuthInterceptor > muscovite::server::security::AuthInterceptorFactory::build () nodiscard
Build an interceptor configured with current settings.
Definition at line 227 of file auth_interceptor.cpp.
Referenced by build_interceptor_creators().
build_interceptor_creators()
std::vector< std::unique_ptr< grpc::experimental::ServerInterceptorFactoryInterface > > muscovite::server::security::AuthInterceptorFactory::build_interceptor_creators () nodiscard
Build creators usable with gRPC server options.
Definition at line 242 of file auth_interceptor.cpp.
References build().
CreateServerInterceptor()
grpc::experimental::Interceptor * muscovite::server::security::AuthInterceptorFactory::CreateServerInterceptor (grpc::experimental::ServerRpcInfo * info) override
Definition at line 235 of file auth_interceptor.cpp.
require_any_privilege()
AuthInterceptorFactory & muscovite::server::security::AuthInterceptorFactory::require_any_privilege (const std::string & method, const std::vector< std::string > & privileges)
Require any of the provided privileges for a specific method.
Definition at line 218 of file auth_interceptor.cpp.
References AuthInterceptorFactory().
require_privilege()
AuthInterceptorFactory & muscovite::server::security::AuthInterceptorFactory::require_privilege (const std::string & method, const std::string & privilege)
Require a privilege for a specific method.
Definition at line 211 of file auth_interceptor.cpp.
References AuthInterceptorFactory().
The documentation for this class was generated from the following files:
framework/server/include/muscovite/server/security/auth_interceptor.hpp
framework/server/src/security/auth_interceptor.cpp