Muscovite C++ Framework: muscovite::server::security::JwtService Class Reference
muscovite::server::security::JwtService Class Reference
Service for JWT token generation and validation.
#include <jwt_service.hpp>
Classes
struct Config
Configuration for JWT service.
Public Types
enum class Algorithm { HS256 , RS256 }
Supported signing algorithms.
Public Member Functions
JwtService (const Config &config)
Construct JWT service with configuration.
JwtService (const JwtService &)=delete
JwtService (JwtService &&) noexcept
std::chrono::seconds access_token_lifetime () const
Get the configured access token lifetime.
std::string generate_access_token (const JwtClaims &claims) const
Generate an access token for the given claims.
std::string generate_refresh_token () const
Generate a refresh token.
std::string hash_refresh_token (const std::string &refresh_token) const
Hash a refresh token for storage.
JwtService & operator= (const JwtService &)=delete
JwtService & operator= (JwtService &&) noexcept
std::chrono::seconds refresh_token_lifetime () const
Get the configured refresh token lifetime.
std::optional< JwtClaims > validate_access_token (const std::string &token) const
Validate and decode an access token.
Detailed Description
Service for JWT token generation and validation.
Supports both HMAC-SHA256 (HS256) and RSA-SHA256 (RS256) algorithms. Access tokens are short-lived (15 min default), refresh tokens are long-lived (7 days default).
Definition at line 48 of file jwt_service.hpp.
Member Enumeration Documentation
Algorithm
enum class muscovite::server::security::JwtService::Algorithm strong
Supported signing algorithms.
Enumerator
HS256
HMAC-SHA256 (symmetric key).
RS256
RSA-SHA256 (asymmetric keys).
Definition at line 53 of file jwt_service.hpp.
Constructor & Destructor Documentation
JwtService()
muscovite::server::security::JwtService::JwtService (const Config & config) explicit
Construct JWT service with configuration.
Definition at line 203 of file jwt_service.cpp.
References JwtService().
Referenced by JwtService(), and generate_access_token().
Member Function Documentation
access_token_lifetime()
std::chrono::seconds muscovite::server::security::JwtService::access_token_lifetime () const nodiscard
Get the configured access token lifetime.
Definition at line 227 of file jwt_service.cpp.
generate_access_token()
std::string muscovite::server::security::JwtService::generate_access_token (const JwtClaims & claims) const nodiscard
Generate an access token for the given claims.
Parameters
claims The JWT claims to encode.
Returns
The signed JWT access token.
Definition at line 211 of file jwt_service.cpp.
References JwtService(), and generate_access_token().
Referenced by generate_access_token().
generate_refresh_token()
std::string muscovite::server::security::JwtService::generate_refresh_token () const nodiscard
Generate a refresh token.
Refresh tokens are opaque random strings (not JWTs) stored hashed in the database.
Returns
A cryptographically secure random refresh token.
Definition at line 215 of file jwt_service.cpp.
hash_refresh_token()
std::string muscovite::server::security::JwtService::hash_refresh_token (const std::string & refresh_token) const nodiscard
Hash a refresh token for storage.
Parameters
refresh_token The plaintext refresh token.
Returns
SHA-256 hash of the token.
Definition at line 219 of file jwt_service.cpp.
refresh_token_lifetime()
std::chrono::seconds muscovite::server::security::JwtService::refresh_token_lifetime () const nodiscard
Get the configured refresh token lifetime.
Definition at line 231 of file jwt_service.cpp.
validate_access_token()
std::optional< JwtClaims > muscovite::server::security::JwtService::validate_access_token (const std::string & token) const nodiscard
Validate and decode an access token.
Parameters
token The JWT access token to validate.
Returns
The decoded claims if valid, std::nullopt if invalid or expired.
Definition at line 223 of file jwt_service.cpp.
The documentation for this class was generated from the following files:
framework/server/include/muscovite/server/security/jwt_service.hpp
framework/server/src/security/jwt_service.cpp