Muscovite C++ Framework: muscovite::grpc::oauth2::OAuth2Interceptor Class Reference
muscovite::grpc::oauth2::OAuth2Interceptor Class Reference
#include <oauth2_interceptor.hpp>
Public Member Functions
OAuth2Interceptor (std::shared_ptr< AuthorizationCodeFlow > flow)
void authenticateBuiltIn (const std::string &username, const std::string &password)
void completeOAuth2Flow (const std::string &authorization_code)
std::optional< std::string > getAccessToken () const
Get current access token (for debugging).
::grpc::Status GetMetadata (::grpc::string_ref service_url, ::grpc::string_ref method_name, const ::grpc::AuthContext &channel_auth_context, std::multimap<::grpc::string, ::grpc::string > *metadata) override
std::optional< std::string > getUsername () const
Get current username.
bool isAuthenticated () const
Check if currently authenticated.
void logout ()
std::string startOAuth2Flow ()
Detailed Description
OAuth2 Interceptor for gRPC channels.
Implements ::grpc::MetadataCredentialsPlugin to automatically add Authorization header with bearer token to every gRPC call.
Supports both built-in authentication (muscoviteserver security module) and external OAuth2 providers (Keycloak, Auth0, Azure AD).
Features:
Automatic token refresh before expiry
Dual-mode authentication (built-in + OAuth2)
Secure token storage (memory for access, keychain for refresh)
Token revocation on logout
Definition at line 43 of file oauth2_interceptor.hpp.
Constructor & Destructor Documentation
OAuth2Interceptor()
muscovite::grpc::oauth2::OAuth2Interceptor::OAuth2Interceptor (std::shared_ptr< AuthorizationCodeFlow > flow) explicit
Definition at line 13 of file oauth2_interceptor.cpp.
Member Function Documentation
authenticateBuiltIn()
void muscovite::grpc::oauth2::OAuth2Interceptor::authenticateBuiltIn (const std::string & username, const std::string & password)
Authenticate user with username/password (built-in mode).
Exchanges credentials against muscoviteserver security module for access token (no refresh token needed for built-in mode).
Parameters
username User username
password User password
Exceptions
std::runtime_error on authentication failure
Definition at line 18 of file oauth2_interceptor.cpp.
References authenticateBuiltIn().
Referenced by authenticateBuiltIn().
completeOAuth2Flow()
void muscovite::grpc::oauth2::OAuth2Interceptor::completeOAuth2Flow (const std::string & authorization_code)
Complete OAuth2 authentication flow.
Called after user authenticates at external provider and redirect_uri is reached with authorization code.
Exchanges code for tokens and enables OAuth2 mode for subsequent calls.
Parameters
authorization_code Code from redirect_uri parameter
Exceptions
std::runtime_error on code exchange failure
Definition at line 38 of file oauth2_interceptor.cpp.
References completeOAuth2Flow(), muscovite::grpc::oauth2::JWT::extractClaims(), and muscovite::grpc::oauth2::JWT::extractSubject().
Referenced by completeOAuth2Flow().
getAccessToken()
std::optional< std::string > muscovite::grpc::oauth2::OAuth2Interceptor::getAccessToken () const
Get current access token (for debugging).
Definition at line 124 of file oauth2_interceptor.cpp.
References getAccessToken().
Referenced by getAccessToken().
GetMetadata()
grpc::Status muscovite::grpc::oauth2::OAuth2Interceptor::GetMetadata (::grpc::string_ref service_url, ::grpc::string_ref method_name, const ::grpc::AuthContext & channel_auth_context, std::multimap<::grpc::string, ::grpc::string > * metadata) override
gRPC metadata plugin interface.
Called by gRPC for every RPC call. Adds Authorization header with bearer token (with automatic refresh if needed).
This is automatically called by gRPC runtime, not user code.
Definition at line 60 of file oauth2_interceptor.cpp.
References GetMetadata().
Referenced by GetMetadata().
getUsername()
std::optional< std::string > muscovite::grpc::oauth2::OAuth2Interceptor::getUsername () const
Get current username.
Definition at line 132 of file oauth2_interceptor.cpp.
References getUsername().
Referenced by getUsername().
isAuthenticated()
bool muscovite::grpc::oauth2::OAuth2Interceptor::isAuthenticated () const
Check if currently authenticated.
Definition at line 119 of file oauth2_interceptor.cpp.
References isAuthenticated().
Referenced by isAuthenticated().
logout()
void muscovite::grpc::oauth2::OAuth2Interceptor::logout ()
Logout and revoke tokens.
Revokes current tokens with identity provider and clears local storage.
Exceptions
std::runtime_error on revocation error (non-fatal if provider unreachable)
Definition at line 88 of file oauth2_interceptor.cpp.
References logout().
Referenced by logout().
startOAuth2Flow()
std::string muscovite::grpc::oauth2::OAuth2Interceptor::startOAuth2Flow ()
Start OAuth2 authentication flow (external provider mode).
Returns authorization URL for user to open in browser. After user authenticates, call completeOAuth2Flow() with returned code.
Returns
Authorization URL for user to open
Definition at line 34 of file oauth2_interceptor.cpp.
References startOAuth2Flow().
Referenced by startOAuth2Flow().
The documentation for this class was generated from the following files:
framework/grpc/include/muscovite/grpc/oauth2/oauth2_interceptor.hpp
framework/grpc/src/oauth2/oauth2_interceptor.cpp