Muscovite C++ Framework: muscovite::search::OpenSearchClient Class Reference
muscovite::search::OpenSearchClient Class Reference
Low-level REST client for OpenSearch.
#include <opensearch_client.hpp>
Public Member Functions
OpenSearchClient (const OpenSearchClient &)=delete
OpenSearchClient (OpenSearchClient &&) noexcept
OpenSearchClient (SearchConfig config)
Construct a client with the given configuration.
~OpenSearchClient ()
Destructor (releases CURL handle).
BulkResponse bulk (const std::string &ndjson)
Execute a bulk request.
const SearchConfig & config () const noexcept
Get the underlying configuration.
IndexResponse create_index (const std::string &index_name, const nlohmann::json &mapping)
Create an index with the given mapping.
DocumentResponse delete_document (const std::string &index_name, const std::string &document_id)
Delete a document by ID.
IndexResponse delete_index (const std::string &index_name)
Delete an index.
DocumentResponse index_document (const std::string &index_name, const std::string &document_id, const nlohmann::json &document)
Index (upsert) a document.
bool index_exists (const std::string &index_name) const
Check if an index exists.
bool is_healthy () const noexcept
Check cluster health.
std::vector< SearchResult > multi_search (const std::vector< std::string > &index_names, const std::vector< nlohmann::json > &queries) const
Execute a multi-search request.
OpenSearchClient & operator= (const OpenSearchClient &)=delete
OpenSearchClient & operator= (OpenSearchClient &&) noexcept
SearchResult search (const std::vector< std::string > &index_names, const nlohmann::json &query) const
Execute a search query.
Detailed Description
Low-level REST client for OpenSearch.
Provides typed methods for index management, document CRUD, search queries, and bulk operations. Uses libcurl internally (hidden behind PIMPL).
Thread safety: NOT thread-safe. Each thread should have its own client instance or use external synchronization. CURL handles are not shared across threads.
SearchConfig config;
config.host = "localhost";
config.port = 9200;
OpenSearchClient client(config);
// Create an index
auto idx_resp = client.create_index("patients", mapping_json);
// Index a document
auto doc_resp = client.index_document("patients", patient_id, patient_json);
// Search
auto result = client.search({"patients"}, query_json);
for (const auto& hit : result.hits) {
    // process hit.source
}
See also
SearchConfig — connection configuration
SearchError — exception hierarchy
SearchResult — typed search results
Definition at line 65 of file opensearch_client.hpp.
Constructor & Destructor Documentation
OpenSearchClient()
muscovite::search::OpenSearchClient::OpenSearchClient (SearchConfig config) explicit
Construct a client with the given configuration.
Parameters
config Connection configuration (host, port, auth, timeouts).
Exceptions
SearchConnectionError if initial CURL setup fails.
Definition at line 250 of file opensearch_client.cpp.
References config().
Referenced by ~OpenSearchClient(), and is_healthy().
Member Function Documentation
bulk()
BulkResponse muscovite::search::OpenSearchClient::bulk (const std::string & ndjson)
Execute a bulk request.
Parameters
ndjson Newline-delimited JSON string (action + source pairs).
Returns
BulkResponse with per-item success/failure counts.
Exceptions
SearchQueryError if the bulk request is malformed.
SearchConnectionError if cluster is unreachable.
Note
Callers should use the SearchBulkBuilder (FTR-116) to construct the NDJSON payload rather than building it manually.
Definition at line 422 of file opensearch_client.cpp.
Referenced by ~OpenSearchClient().
config()
const SearchConfig & muscovite::search::OpenSearchClient::config () const nodiscard noexcept
Get the underlying configuration.
Returns
Const reference to the SearchConfig used by this client.
Definition at line 436 of file opensearch_client.cpp.
Referenced by OpenSearchClient(), and ~OpenSearchClient().
create_index()
IndexResponse muscovite::search::OpenSearchClient::create_index (const std::string & index_name, const nlohmann::json & mapping)
Create an index with the given mapping.
Parameters
index_name Index name (lowercase, no special chars).
mapping Index mapping and settings as JSON.
Returns
IndexResponse with acknowledgement status.
Exceptions
SearchIndexError if index creation fails.
SearchConnectionError if cluster is unreachable.
Definition at line 273 of file opensearch_client.cpp.
Referenced by ~OpenSearchClient().
delete_document()
DocumentResponse muscovite::search::OpenSearchClient::delete_document (const std::string & index_name, const std::string & document_id)
Delete a document by ID.
Parameters
index_name Target index.
document_id Document ID to delete.
Returns
DocumentResponse with result ("deleted" or "not_found").
Exceptions
SearchIndexError if deletion fails.
SearchConnectionError if cluster is unreachable.
Definition at line 332 of file opensearch_client.cpp.
References muscovite::search::DocumentResponse::id, muscovite::search::DocumentResponse::index, muscovite::search::DocumentResponse::raw, and muscovite::search::DocumentResponse::result.
Referenced by ~OpenSearchClient().
delete_index()
IndexResponse muscovite::search::OpenSearchClient::delete_index (const std::string & index_name)
Delete an index.
Parameters
index_name Index name to delete.
Returns
IndexResponse with acknowledgement status.
Exceptions
SearchIndexError if index deletion fails (e.g., not found).
SearchConnectionError if cluster is unreachable.
Definition at line 288 of file opensearch_client.cpp.
Referenced by ~OpenSearchClient().
index_document()
DocumentResponse muscovite::search::OpenSearchClient::index_document (const std::string & index_name, const std::string & document_id, const nlohmann::json & document)
Index (upsert) a document.
Parameters
index_name Target index.
document_id Document ID (typically UUID string).
document Document body as JSON.
Returns
DocumentResponse with result ("created" or "updated").
Exceptions
SearchIndexError if indexing fails.
SearchConnectionError if cluster is unreachable.
Definition at line 314 of file opensearch_client.cpp.
Referenced by ~OpenSearchClient().
index_exists()
bool muscovite::search::OpenSearchClient::index_exists (const std::string & index_name) const nodiscard
Check if an index exists.
Parameters
index_name Index name to check.
Returns
true if the index exists, false otherwise.
Exceptions
SearchConnectionError if cluster is unreachable.
Definition at line 302 of file opensearch_client.cpp.
Referenced by ~OpenSearchClient().
is_healthy()
bool muscovite::search::OpenSearchClient::is_healthy () const nodiscard noexcept
Check cluster health.
Returns
true if cluster is reachable and status is green or yellow.
Note
Does not throw — returns false on any error.
Definition at line 258 of file opensearch_client.cpp.
References OpenSearchClient(), and is_healthy().
Referenced by ~OpenSearchClient(), and is_healthy().
multi_search()
std::vector< SearchResult > muscovite::search::OpenSearchClient::multi_search (const std::vector< std::string > & index_names, const std::vector< nlohmann::json > & queries) const nodiscard
Execute a multi-search request.
Parameters
index_names Default index names for all sub-queries.
queries Vector of query bodies (each is a JSON query DSL object).
Returns
Vector of SearchResult, one per query.
Exceptions
SearchQueryError if any query fails.
SearchConnectionError if cluster is unreachable.
Definition at line 383 of file opensearch_client.cpp.
Referenced by ~OpenSearchClient().
search()
SearchResult muscovite::search::OpenSearchClient::search (const std::vector< std::string > & index_names, const nlohmann::json & query) const nodiscard
Execute a search query.
Parameters
index_names List of index names to search (can use wildcards).
query OpenSearch query DSL as JSON.
Returns
SearchResult with typed hits and metadata.
Exceptions
SearchQueryError if the query is malformed or execution fails.
SearchConnectionError if cluster is unreachable.
Definition at line 361 of file opensearch_client.cpp.
Referenced by ~OpenSearchClient().
The documentation for this class was generated from the following files:
framework/search/include/muscovite/search/opensearch_client.hpp
framework/search/src/opensearch_client.cpp