Muscovite C++ Framework: muscovite::geo::Point< Srid > Class Template Reference
muscovite::geo::Point< Srid > Class Template Reference
2D geographic point (latitude, longitude)
#include <geography.hpp>
Public Types
using srid_tag = Srid
Public Member Functions
Point ()
Default constructor (0,0 origin).
Point (double lon, double lat)
Construct from longitude (X) and latitude (Y).
double latitude () const noexcept
Latitude (Y coordinate) in degrees.
double longitude () const noexcept
Longitude (X coordinate) in degrees.
const bg_point & native () const noexcept
Access underlying Boost.Geometry point.
bg_point & native () noexcept
bool operator== (const Point &other) const noexcept
Equality comparison (exact).
std::string to_ewkt () const
Convert to EWKT (Extended WKT with SRID).
std::string to_wkt () const
Convert to WKT (Well-Known Text) format.
double x () const noexcept
Alias for longitude (common in GIS).
double y () const noexcept
Alias for latitude (common in GIS).
Static Public Member Functions
static std::optional< Point > from_wkt (std::string_view wkt)
Parse from WKT string.
Static Public Attributes
static constexpr int srid = Srid::value
Detailed Description
template<SridTag Srid>
class muscovite::geo::Point< Srid >
2D geographic point (latitude, longitude)
Template Parameters
Srid SRID tag type (e.g., srid_4326)
Definition at line 98 of file geography.hpp.
Member Typedef Documentation
srid_tag
template<SridTag Srid> using muscovite::geo::Point< Srid >::srid_tag = Srid
Definition at line 100 of file geography.hpp.
Constructor & Destructor Documentation
Point() [1/2]
template<SridTag Srid> muscovite::geo::Point< Srid >::Point () inline
Default constructor (0,0 origin).
Definition at line 109 of file geography.hpp.
Referenced by muscovite::geo::Point< srid_4326 >::from_wkt().
Point() [2/2]
template<SridTag Srid> muscovite::geo::Point< Srid >::Point (double lon, double lat) inline
Construct from longitude (X) and latitude (Y).
Parameters
lon Longitude in degrees (-180 to 180)
lat Latitude in degrees (-90 to 90)
Exceptions
std::out_of_range if coordinates are invalid
Definition at line 115 of file geography.hpp.
Member Function Documentation
from_wkt()
template<SridTag Srid> std::optional< Point > muscovite::geo::Point< Srid >::from_wkt (std::string_view wkt) inline static nodiscard
Parse from WKT string.
Parameters
wkt WKT representation e.g. "POINT(-122.4194 37.7749)"
Returns
Optional containing point if valid, std::nullopt otherwise
Definition at line 157 of file geography.hpp.
latitude()
template<SridTag Srid> double muscovite::geo::Point< Srid >::latitude () const inline nodiscard noexcept
Latitude (Y coordinate) in degrees.
Definition at line 125 of file geography.hpp.
Referenced by muscovite::geo::Polygon< srid_4326 >::contains(), muscovite::geo::BoundingBox< srid_4326 >::expand(), muscovite::geo::Point< srid_4326 >::operator==(), muscovite::geo::LineString< srid_4326 >::push_back(), muscovite::geo::Point< srid_4326 >::to_ewkt(), muscovite::geo::Point< srid_4326 >::to_wkt(), and muscovite::geo::Point< srid_4326 >::y().
longitude()
template<SridTag Srid> double muscovite::geo::Point< Srid >::longitude () const inline nodiscard noexcept
Longitude (X coordinate) in degrees.
Definition at line 120 of file geography.hpp.
Referenced by muscovite::geo::Polygon< srid_4326 >::contains(), muscovite::geo::BoundingBox< srid_4326 >::expand(), muscovite::geo::Point< srid_4326 >::operator==(), muscovite::geo::LineString< srid_4326 >::push_back(), muscovite::geo::Point< srid_4326 >::to_ewkt(), muscovite::geo::Point< srid_4326 >::to_wkt(), and muscovite::geo::Point< srid_4326 >::x().
native() [1/2]
template<SridTag Srid> const bg_point & muscovite::geo::Point< Srid >::native () const inline nodiscard noexcept
Access underlying Boost.Geometry point.
Definition at line 136 of file geography.hpp.
native() [2/2]
template<SridTag Srid> bg_point & muscovite::geo::Point< Srid >::native () inline nodiscard noexcept
Definition at line 137 of file geography.hpp.
operator==()
template<SridTag Srid> bool muscovite::geo::Point< Srid >::operator== (const Point< Srid > & other) const inline nodiscard noexcept
Equality comparison (exact).
Definition at line 140 of file geography.hpp.
to_ewkt()
template<SridTag Srid> std::string muscovite::geo::Point< Srid >::to_ewkt () const inline nodiscard
Convert to EWKT (Extended WKT with SRID).
Definition at line 150 of file geography.hpp.
to_wkt()
template<SridTag Srid> std::string muscovite::geo::Point< Srid >::to_wkt () const inline nodiscard
Convert to WKT (Well-Known Text) format.
Definition at line 145 of file geography.hpp.
x()
template<SridTag Srid> double muscovite::geo::Point< Srid >::x () const inline nodiscard noexcept
Alias for longitude (common in GIS).
Definition at line 130 of file geography.hpp.
y()
template<SridTag Srid> double muscovite::geo::Point< Srid >::y () const inline nodiscard noexcept
Alias for latitude (common in GIS).
Definition at line 133 of file geography.hpp.
Member Data Documentation
srid
template<SridTag Srid> int muscovite::geo::Point< Srid >::srid = Srid::value static constexpr
Definition at line 101 of file geography.hpp.
The documentation for this class was generated from the following file:
framework/geo/include/muscovite/geo/geography.hpp