Muscovite C++ Framework: muscovite::types::PostalCode Class Reference
muscovite::types::PostalCode Class Reference
Public Member Functions
auto is_canadian () const noexcept -> bool
Check if Canadian postal code format.
auto is_us_zip () const noexcept -> bool
Check if US ZIP code format (5 or 9 digits).
strong_type_base ()=default
Default constructor creates empty value.
strong_type_base (std::string_view value)
Construct with validation.
Public Member Functions inherited from muscovite::types::strong_type_base< PostalCode >
strong_type_base ()=default
Default constructor creates empty value.
auto empty () const noexcept -> bool
Check if empty.
operator std::string_view () const noexcept
Implicit conversion to string_view for compatibility.
auto operator<=> (const strong_type_base &other) const noexcept=default
Three-way comparison.
auto operator== (const strong_type_base &other) const noexcept -> bool=default
Equality comparison.
auto value () const noexcept -> const std::string &
Get the underlying string value.
Static Public Member Functions
static auto is_valid (std::string_view value) noexcept -> bool
Validate postal code format.
static constexpr auto pattern () noexcept -> std::string_view
Validation pattern (matches PostgreSQL CHECK).
static constexpr auto type_name () noexcept -> std::string_view
Type name for error messages.
Static Public Member Functions inherited from muscovite::types::strong_type_base< PostalCode >
static auto from_trusted (std::string value) noexcept -> PostalCode
Construct from trusted source without validation.
Additional Inherited Members
Protected Attributes inherited from muscovite::types::strong_type_base< PostalCode >
std::string value_
Detailed Description
Definition at line 40 of file postal_code.hpp.
Member Function Documentation
is_canadian()
auto muscovite::types::PostalCode::is_canadian () const -> bool inline nodiscard noexcept
Check if Canadian postal code format.
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/postal_code.hpp.
Definition at line 78 of file postal_code.hpp.
is_us_zip()
auto muscovite::types::PostalCode::is_us_zip () const -> bool inline nodiscard noexcept
Check if US ZIP code format (5 or 9 digits).
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/postal_code.hpp.
Definition at line 68 of file postal_code.hpp.
is_valid()
auto muscovite::types::PostalCode::is_valid (std::string_view value) -> bool inline static nodiscard noexcept
Validate postal code format.
Parameters
value String to validate
Returns
true if valid postal code format
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/postal_code.hpp.
Definition at line 57 of file postal_code.hpp.
References pattern(), and muscovite::types::strong_type_base< PostalCode >::value().
pattern()
constexpr auto muscovite::types::PostalCode::pattern () -> std::string_view inline static nodiscard constexpr noexcept
Validation pattern (matches PostgreSQL CHECK).
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/postal_code.hpp.
Definition at line 50 of file postal_code.hpp.
References muscovite::types::strong_type_base< PostalCode >::operator std::string_view().
Referenced by is_valid().
strong_type_base()
muscovite::types::strong_type_base< Derived >::strong_type_base (std::string_view value) inline explicit
Construct with validation.
Parameters
value The string value to wrap
Exceptions
invalid_value_error if validation fails
Definition at line 71 of file strong_type_base.hpp.
type_name()
constexpr auto muscovite::types::PostalCode::type_name () -> std::string_view inline static nodiscard constexpr noexcept
Type name for error messages.
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/postal_code.hpp.
Definition at line 45 of file postal_code.hpp.
References muscovite::types::strong_type_base< PostalCode >::operator std::string_view().
The documentation for this class was generated from the following file:
framework/types/include/muscovite/types/postal_code.hpp