Muscovite C++ Framework: muscovite::qt::grpc::ServiceClientBase Class Reference
muscovite::qt::grpc::ServiceClientBase Class Reference
Base class providing a QFuture-oriented unary call helper with auth support.
#include <service_client_base.hpp>
Public Member Functions
ServiceClientBase (std::shared_ptr<::grpc::Channel > channel)
AuthManager * authManager () const
Get the authentication manager.
void setAuthManager (AuthManager *authMgr)
Set the authentication manager for adding auth headers.
Protected Member Functions
template<typename Request, typename Response, typename Callable>
QFuture< GrpcResult< Response > > callUnary (const Request &request, Callable &&callable, std::chrono::milliseconds deadline=std::chrono::seconds{10})
Execute a unary call asynchronously with optional authentication.
std::shared_ptr<::grpc::Channel > channel () const
void setChannel (std::shared_ptr<::grpc::Channel > channel)
Detailed Description
Base class providing a QFuture-oriented unary call helper with auth support.
Definition at line 82 of file service_client_base.hpp.
Constructor & Destructor Documentation
ServiceClientBase()
muscovite::qt::grpc::ServiceClientBase::ServiceClientBase (std::shared_ptr<::grpc::Channel > channel) inline explicit
Definition at line 85 of file service_client_base.hpp.
Member Function Documentation
authManager()
AuthManager * muscovite::qt::grpc::ServiceClientBase::authManager () const inline nodiscard
Get the authentication manager.
Returns
Pointer to AuthManager or nullptr if not set
Definition at line 97 of file service_client_base.hpp.
Referenced by muscovite::qt::services::GeosciencesServiceClient::createSample(), muscovite::qt::services::GeosciencesServiceClient::deleteSample(), muscovite::qt::services::GeosciencesServiceClient::fetchSamples(), muscovite::qt::services::GeosciencesServiceClient::initialize(), and muscovite::qt::services::GeosciencesServiceClient::updateSample().
callUnary()
template<typename Request, typename Response, typename Callable> QFuture< GrpcResult< Response > > muscovite::qt::grpc::ServiceClientBase::callUnary (const Request & request, Callable && callable, std::chrono::milliseconds deadline = std::chrono::seconds{10}) inline protected
Execute a unary call asynchronously with optional authentication.
Template Parameters
Request protobuf request type
Response protobuf response type
Callable callable signature: grpc::Status(grpc::ClientContext&, const Request&, Response&)
Definition at line 105 of file service_client_base.hpp.
channel()
std::shared_ptr<::grpc::Channel > muscovite::qt::grpc::ServiceClientBase::channel () const inline nodiscard protected
Definition at line 176 of file service_client_base.hpp.
setAuthManager()
void muscovite::qt::grpc::ServiceClientBase::setAuthManager (AuthManager * authMgr) inline
Set the authentication manager for adding auth headers.
Parameters
authMgr Pointer to AuthManager instance
Definition at line 91 of file service_client_base.hpp.
Referenced by muscovite::qt::services::GeosciencesServiceClient::initialize().
setChannel()
void muscovite::qt::grpc::ServiceClientBase::setChannel (std::shared_ptr<::grpc::Channel > channel) inline protected
Definition at line 172 of file service_client_base.hpp.
The documentation for this class was generated from the following file:
framework/qt/include/muscovite/qt/grpc/service_client_base.hpp