Muscovite C++ Framework: muscovite::types::BoundedDecimal< Min, Max > Class Template Reference
muscovite::types::BoundedDecimal< Min, Max > Class Template Reference
Public Types
using value_type = double
Public Member Functions
constexpr operator value_type () const noexcept
Implicit conversion to double.
constexpr auto operator<=> (const BoundedDecimal &) const noexcept=default
Three-way comparison.
constexpr auto operator== (const BoundedDecimal &) const noexcept -> bool=default
Equality.
constexpr auto value () const noexcept -> value_type
Get the underlying double value.
Static Public Member Functions
static constexpr auto from_trusted (value_type v) noexcept -> BoundedDecimal
Construct from trusted source without validation (DB loads).
static consteval auto has_lower_bound () noexcept -> bool
Check if the lower bound is specified.
static consteval auto has_upper_bound () noexcept -> bool
Check if the upper bound is specified.
static auto is_valid (value_type v) noexcept -> bool
Validate a value against the range constraints.
static auto try_from (std::string_view sv) -> std::expected< BoundedDecimal, std::string >
Try to construct from a string representation.
static auto try_from (value_type v) -> std::expected< BoundedDecimal, std::string >
Try to construct from a double value.
Detailed Description
template<StringLiteral Min, StringLiteral Max>
class muscovite::types::BoundedDecimal< Min, Max >
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/bounded_decimal.hpp.
Definition at line 63 of file bounded_decimal.hpp.
Member Typedef Documentation
value_type
template<StringLiteral Min, StringLiteral Max> using muscovite::types::BoundedDecimal< Min, Max >::value_type = double
Definition at line 65 of file bounded_decimal.hpp.
Member Function Documentation
from_trusted()
template<StringLiteral Min, StringLiteral Max> constexpr auto muscovite::types::BoundedDecimal< Min, Max >::from_trusted (value_type v) -> BoundedDecimal inline static nodiscard constexpr noexcept
Construct from trusted source without validation (DB loads).
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/bounded_decimal.hpp.
Definition at line 111 of file bounded_decimal.hpp.
has_lower_bound()
template<StringLiteral Min, StringLiteral Max> consteval auto muscovite::types::BoundedDecimal< Min, Max >::has_lower_bound () -> bool inline static nodiscard consteval noexcept
Check if the lower bound is specified.
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/bounded_decimal.hpp.
Definition at line 68 of file bounded_decimal.hpp.
Referenced by is_valid().
has_upper_bound()
template<StringLiteral Min, StringLiteral Max> consteval auto muscovite::types::BoundedDecimal< Min, Max >::has_upper_bound () -> bool inline static nodiscard consteval noexcept
Check if the upper bound is specified.
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/bounded_decimal.hpp.
Definition at line 73 of file bounded_decimal.hpp.
Referenced by is_valid().
is_valid()
template<StringLiteral Min, StringLiteral Max> auto muscovite::types::BoundedDecimal< Min, Max >::is_valid (value_type v) -> bool inline static nodiscard noexcept
Validate a value against the range constraints.
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/bounded_decimal.hpp.
Definition at line 78 of file bounded_decimal.hpp.
References has_lower_bound(), and has_upper_bound().
Referenced by try_from().
operator value_type()
template<StringLiteral Min, StringLiteral Max> muscovite::types::BoundedDecimal< Min, Max >::operator value_type () const inline nodiscard constexpr noexcept
Implicit conversion to double.
Definition at line 122 of file bounded_decimal.hpp.
try_from() [1/2]
template<StringLiteral Min, StringLiteral Max> auto muscovite::types::BoundedDecimal< Min, Max >::try_from (std::string_view sv) -> std::expected< BoundedDecimal, std::string > inline static nodiscard
Try to construct from a string representation.
Definition at line 100 of file bounded_decimal.hpp.
References try_from().
try_from() [2/2]
template<StringLiteral Min, StringLiteral Max> auto muscovite::types::BoundedDecimal< Min, Max >::try_from (value_type v) -> std::expected< BoundedDecimal, std::string > inline static nodiscard
Try to construct from a double value.
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/bounded_decimal.hpp.
Definition at line 91 of file bounded_decimal.hpp.
References is_valid().
Referenced by try_from().
value()
template<StringLiteral Min, StringLiteral Max> auto muscovite::types::BoundedDecimal< Min, Max >::value () const -> value_type inline nodiscard constexpr noexcept
Get the underlying double value.
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/bounded_decimal.hpp.
Definition at line 117 of file bounded_decimal.hpp.
The documentation for this class was generated from the following file:
framework/types/include/muscovite/types/bounded_decimal.hpp