Muscovite C++ Framework: muscovite::qt::models::GrpcItemModel< T > Class Template Reference
muscovite::qt::models::GrpcItemModel< T > Class Template Reference abstract
Base class for gRPC-backed Qt item models.
#include <grpc_item_model.hpp>
Signals
void errorChanged (const QString &_t1)
void fetchCompleted ()
void fetchFailed (const QString &_t1)
void loadingChanged (bool _t1)
Public Member Functions
GrpcItemModel (QObject *parent=nullptr)
GrpcItemModel (QObject *parent=nullptr)
muscovite::qt::AuthManager * authManager () const
std::shared_ptr<::grpc::Channel > channel () const
void clear ()
int columnCount (const QModelIndex &parent=QModelIndex()) const override
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
virtual QString entityIdAt (int row) const
Get the entity ID at the given row. Used by list widgets to identify selected entities for edit/delete.
QString error () const
virtual Q_INVOKABLE void fetch ()=0
Fetch data from gRPC backend. Subclasses must implement this to call the entity's List gRPC method. Should call setLoading(true) before the call and setLoading(false) after. On success, call setRows() with the converted data. On failure, call setError() with a user-friendly message.
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const override
bool isLoading () const
std::optional< T > itemAt (int row) const
const std::vector< T > & items () const
QHash< int, QByteArray > roleNames () const override
int rowCount (const QModelIndex &parent=QModelIndex()) const override
int rowCount (const QModelIndex &parent=QModelIndex()) const override
void setAuthManager (muscovite::qt::AuthManager *mgr)
void setChannel (std::shared_ptr<::grpc::Channel > channel)
void setItems (const std::vector< T > &items)
Protected Member Functions
const QStringList & headers () const
std::unique_ptr<::grpc::ClientContext > makeContext (std::chrono::milliseconds deadline=std::chrono::seconds{10}) const
std::shared_ptr<::grpc::ClientContext > makeSharedContext (std::chrono::milliseconds deadline=std::chrono::seconds{10}) const
Create a shared gRPC context for async calls (GrpcCallTask pattern).
void setError (const QString &error)
void setHeaders (const QStringList &headers)
void setLoading (bool loading)
void setRoleNames (const QHash< int, QByteArray > &roles)
void setRows (QVector< QVector< QVariant > > &&rows)
Static Protected Member Functions
static QByteArray normalizeRoleName (const QString &header)
Protected Attributes
std::vector< T > items_
Properties
QString error
bool loading
Detailed Description
template<typename T>
class muscovite::qt::models::GrpcItemModel< T >
Base class for gRPC-backed Qt item models.
Base class for gRPC-backed item models.
Provides:
QAbstractTableModel implementation for Qt Widgets (QTableView) and QML
gRPC channel and auth manager integration
Loading/error state management with signals
Column headers and Qt role names derived from DSL fields
Subclasses (generated per-entity) must implement:
fetch() to call gRPC List method and populate rows
Optionally override headerData() for custom column titles
Usage with QSortFilterProxyModel: auto* model = new ChemicalElementModel(this); auto* proxy = new QSortFilterProxyModel(this); proxy->setSourceModel(model); proxy->setSortRole(Qt::UserRole); // Sort by data, not display tableView->setModel(proxy);
Provides common functionality for QAbstractTableModel subclasses that display data from gRPC services.
Definition at line 48 of file grpc_item_model.hpp.
Constructor & Destructor Documentation
GrpcItemModel() [1/2]
template<typename T> muscovite::qt::models::GrpcItemModel< T >::GrpcItemModel (QObject * parent = nullptr) explicit
Definition at line 15 of file grpc_item_model.cpp.
GrpcItemModel() [2/2]
template<typename T> muscovite::qt::models::GrpcItemModel< T >::GrpcItemModel (QObject * parent = nullptr) inline explicit
Definition at line 28 of file grpc_item_model.hpp.
Member Function Documentation
authManager()
template<typename T> muscovite::qt::AuthManager * muscovite::qt::models::GrpcItemModel< T >::authManager () const inline nodiscard
Definition at line 73 of file grpc_item_model.hpp.
channel()
template<typename T> std::shared_ptr<::grpc::Channel > muscovite::qt::models::GrpcItemModel< T >::channel () const inline nodiscard
Definition at line 70 of file grpc_item_model.hpp.
clear()
template<typename T> void muscovite::qt::models::GrpcItemModel< T >::clear () inline
Definition at line 42 of file grpc_item_model.hpp.
columnCount()
template<typename T> int muscovite::qt::models::GrpcItemModel< T >::columnCount (const QModelIndex & parent = QModelIndex()) const nodiscard override
Definition at line 25 of file grpc_item_model.cpp.
data()
template<typename T> QVariant muscovite::qt::models::GrpcItemModel< T >::data (const QModelIndex & index, int role = Qt::DisplayRole) const nodiscard override
Definition at line 38 of file grpc_item_model.cpp.
entityIdAt()
template<typename T> QString muscovite::qt::models::GrpcItemModel< T >::entityIdAt (int row) const nodiscard virtual
Get the entity ID at the given row. Used by list widgets to identify selected entities for edit/delete.
Parameters
row Row index
Returns
Entity UUID as QString, or empty string if invalid
Definition at line 84 of file grpc_item_model.cpp.
References entityIdAt().
Referenced by entityIdAt().
error()
template<typename T> QString muscovite::qt::models::GrpcItemModel< T >::error () const inline nodiscard
Definition at line 66 of file grpc_item_model.hpp.
headerData()
template<typename T> QVariant muscovite::qt::models::GrpcItemModel< T >::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const nodiscard override
Definition at line 65 of file grpc_item_model.cpp.
headers()
template<typename T> const QStringList & muscovite::qt::models::GrpcItemModel< T >::headers () const inline nodiscard protected
Definition at line 115 of file grpc_item_model.hpp.
isLoading()
template<typename T> bool muscovite::qt::models::GrpcItemModel< T >::isLoading () const inline nodiscard
Definition at line 65 of file grpc_item_model.hpp.
itemAt()
template<typename T> std::optional< T > muscovite::qt::models::GrpcItemModel< T >::itemAt (int row) const inline
Definition at line 48 of file grpc_item_model.hpp.
items()
template<typename T> const std::vector< T > & muscovite::qt::models::GrpcItemModel< T >::items () const inline
Definition at line 55 of file grpc_item_model.hpp.
makeContext()
template<typename T> std::unique_ptr<::grpc::ClientContext > muscovite::qt::models::GrpcItemModel< T >::makeContext (std::chrono::milliseconds deadline = std::chrono::seconds{10}) const nodiscard protected
Definition at line 96 of file grpc_item_model.cpp.
makeSharedContext()
template<typename T> std::shared_ptr<::grpc::ClientContext > muscovite::qt::models::GrpcItemModel< T >::makeSharedContext (std::chrono::milliseconds deadline = std::chrono::seconds{10}) const nodiscard protected
Create a shared gRPC context for async calls (GrpcCallTask pattern).
See also
ADR 20260303-tasktree-adoption, FTR-194
Definition at line 109 of file grpc_item_model.cpp.
References makeSharedContext().
Referenced by makeSharedContext().
normalizeRoleName()
template<typename T> QByteArray muscovite::qt::models::GrpcItemModel< T >::normalizeRoleName (const QString & header) static protected
Definition at line 159 of file grpc_item_model.cpp.
roleNames()
template<typename T> QHash< int, QByteArray > muscovite::qt::models::GrpcItemModel< T >::roleNames () const nodiscard override
Definition at line 80 of file grpc_item_model.cpp.
rowCount() [1/2]
template<typename T> int muscovite::qt::models::GrpcItemModel< T >::rowCount (const QModelIndex & parent = QModelIndex()) const nodiscard override
Definition at line 18 of file grpc_item_model.cpp.
rowCount() [2/2]
template<typename T> int muscovite::qt::models::GrpcItemModel< T >::rowCount (const QModelIndex & parent = QModelIndex()) const inline override
Definition at line 31 of file grpc_item_model.hpp.
setAuthManager()
template<typename T> void muscovite::qt::models::GrpcItemModel< T >::setAuthManager (muscovite::qt::AuthManager * mgr) inline
Definition at line 72 of file grpc_item_model.hpp.
setChannel()
template<typename T> void muscovite::qt::models::GrpcItemModel< T >::setChannel (std::shared_ptr<::grpc::Channel > channel) inline
Definition at line 69 of file grpc_item_model.hpp.
setError()
template<typename T> void muscovite::qt::models::GrpcItemModel< T >::setError (const QString & error) protected
Definition at line 151 of file grpc_item_model.cpp.
setHeaders()
template<typename T> void muscovite::qt::models::GrpcItemModel< T >::setHeaders (const QStringList & headers) protected
Definition at line 122 of file grpc_item_model.cpp.
setItems()
template<typename T> void muscovite::qt::models::GrpcItemModel< T >::setItems (const std::vector< T > & items) inline
Definition at line 36 of file grpc_item_model.hpp.
setLoading()
template<typename T> void muscovite::qt::models::GrpcItemModel< T >::setLoading (bool loading) protected
Definition at line 143 of file grpc_item_model.cpp.
setRoleNames()
template<typename T> void muscovite::qt::models::GrpcItemModel< T >::setRoleNames (const QHash< int, QByteArray > & roles) protected
Definition at line 133 of file grpc_item_model.cpp.
setRows()
template<typename T> void muscovite::qt::models::GrpcItemModel< T >::setRows (QVector< QVector< QVariant > > && rows) protected
Definition at line 137 of file grpc_item_model.cpp.
Member Data Documentation
items_
template<typename T> std::vector<T> muscovite::qt::models::GrpcItemModel< T >::items_ protected
Definition at line 58 of file grpc_item_model.hpp.
Property Documentation
error
template<typename T> QString muscovite::qt::models::GrpcItemModel< T >::error read
Definition at line 51 of file grpc_item_model.hpp.
loading
template<typename T> bool muscovite::qt::models::GrpcItemModel< T >::loading read
Definition at line 50 of file grpc_item_model.hpp.
The documentation for this class was generated from the following files:
framework/qt/include/muscovite/qt/models/grpc_item_model.hpp
include/muscovite/qt/models/grpc_item_model.hpp
framework/qt/src/models/grpc_item_model.cpp