Muscovite C++ Framework: muscovite::dba::MessageBroker Class Reference
muscovite::dba::MessageBroker Class Reference abstract
#include <outbox_publisher.hpp>
Public Member Functions
virtual auto connect () -> bool=0
virtual void disconnect ()=0
Disconnect from the message broker.
virtual auto ensure_infrastructure (const std::string &stream_name, const std::string &subject_prefix) -> bool
virtual auto is_connected () const -> bool=0
Check if connected to the broker.
virtual auto publish (const std::string &subject, const std::string &payload, const std::string &event_id) -> PublishResult=0
Detailed Description
Abstract interface for message broker publishing
Implementations wrap specific message brokers (NATS, Kafka, etc.)
Definition at line 86 of file outbox_publisher.hpp.
Member Function Documentation
connect()
virtual auto muscovite::dba::MessageBroker::connect () -> bool nodiscard pure virtual
Connect to the message broker
Returns
true if connected successfully
Implemented in muscovite::dba::NatsMessageBroker.
disconnect()
virtual void muscovite::dba::MessageBroker::disconnect () pure virtual
Disconnect from the message broker.
Implemented in muscovite::dba::NatsMessageBroker.
ensure_infrastructure()
virtual auto muscovite::dba::MessageBroker::ensure_infrastructure (const std::string & stream_name, const std::string & subject_prefix) -> bool inline nodiscard virtual
Ensure necessary infrastructure exists (e.g., JetStream streams)
Called by OutboxPublisher on startup. Default implementation does nothing. Override in brokers that require pre-created resources.
Parameters
stream_name Logical stream name (typically schema name)
subject_prefix Subject prefix for events (e.g., "muscovite.patient")
Returns
true if infrastructure is ready, false on error
Reimplemented in muscovite::dba::NatsMessageBroker.
Definition at line 118 of file outbox_publisher.hpp.
References ensure_infrastructure().
Referenced by ensure_infrastructure().
is_connected()
virtual auto muscovite::dba::MessageBroker::is_connected () const -> bool nodiscard pure virtual
Check if connected to the broker.
Implemented in muscovite::dba::NatsMessageBroker.
publish()
virtual auto muscovite::dba::MessageBroker::publish (const std::string & subject, const std::string & payload, const std::string & event_id) -> PublishResult nodiscard pure virtual
Publish an event to the broker
Parameters
subject Message subject/topic (e.g., "muscovite.patient.PatientCreated")
payload JSON string payload (ADR 20260202: JSON-in-DB architecture)
event_id Event ID for deduplication/tracking
Returns
Result indicating success or error type
Implemented in muscovite::dba::NatsMessageBroker.
References publish().
Referenced by publish().
The documentation for this class was generated from the following file:
framework/dba/include/muscovite/dba/outbox_publisher.hpp