Muscovite C++ Framework: muscovite::spatial::Point Class Reference
muscovite::spatial::Point Class Reference
Geographic point (latitude, longitude) Represents a single location on Earth using WGS84 coordinates.
#include <geometry.hpp>
Public Member Functions
constexpr Point (Latitude lat=0.0, Longitude lon=0.0, SRID srid=WGS84_SRID)
auto distance_to_km (const Point &other) const -> Distance
Calculate distance to another point using Haversine formula.
auto distance_to_m (const Point &other) const -> Distance
Calculate distance to another point in meters.
auto is_within_km (const Point &center, Distance radius_km) const -> bool
Check if point is within a radius of another point.
auto is_within_m (const Point &center, Distance radius_m) const -> bool
Check if point is within a radius of another point (meters).
constexpr Latitude latitude () const
constexpr Longitude longitude () const
constexpr SRID srid () const
auto to_proto () const -> class ProtoPoint
Convert to gRPC muscovite.common.Point message.
auto to_wkt () const -> std::string
Convert to WKT (Well-Known Text) format Output format: "POINT(lon lat)".
Static Public Member Functions
static auto from_proto (const class ProtoPoint &proto_point) -> Point
Parse point from gRPC muscovite.common.Point message.
static auto from_wkt (std::string_view wkt) -> std::optional< Point >
Parse point from WKT string Format: "POINT(lon lat)" or "POINT(lon lat srid)" Example: "POINT(-122.4194 37.7749)".
Detailed Description
Geographic point (latitude, longitude) Represents a single location on Earth using WGS84 coordinates.
Example: Point sf{37.7749, -122.4194}; // San Francisco auto dist = sf.distance_to(Point{40.7128, -74.0060}); // km to NYC
Definition at line 57 of file geometry.hpp.
Constructor & Destructor Documentation
Point()
muscovite::spatial::Point::Point (Latitude lat = 0.0, Longitude lon = 0.0, SRID srid = WGS84_SRID) inline constexpr
Construct point from latitude and longitude
Parameters
lat Latitude (-90 to 90)
lon Longitude (-180 to 180)
srid Spatial Reference System ID (default: 4326 for WGS84)
Definition at line 63 of file geometry.hpp.
Referenced by distance_to_km(), distance_to_m(), from_proto(), is_within_km(), and is_within_m().
Member Function Documentation
distance_to_km()
auto muscovite::spatial::Point::distance_to_km (const Point & other) const -> Distance nodiscard
Calculate distance to another point using Haversine formula.
Parameters
other The target point
Returns
Distance in kilometers
References Point().
Referenced by distance_to_m(), and is_within_km().
distance_to_m()
auto muscovite::spatial::Point::distance_to_m (const Point & other) const -> Distance inline nodiscard
Calculate distance to another point in meters.
Parameters
other The target point
Returns
Distance in meters
Definition at line 99 of file geometry.hpp.
References Point(), and distance_to_km().
from_proto()
auto muscovite::spatial::Point::from_proto (const class ProtoPoint & proto_point) -> Point static nodiscard
Parse point from gRPC muscovite.common.Point message.
Parameters
proto_point The protobuf point message
References Point(), and from_proto().
Referenced by from_proto().
is_within_km()
auto muscovite::spatial::Point::is_within_km (const Point & center, Distance radius_km) const -> bool inline nodiscard
Check if point is within a radius of another point.
Parameters
center Center point
radius_km Radius in kilometers
Returns
true if this point is within radius_km of center
Definition at line 107 of file geometry.hpp.
References Point(), and distance_to_km().
Referenced by is_within_m().
is_within_m()
auto muscovite::spatial::Point::is_within_m (const Point & center, Distance radius_m) const -> bool inline nodiscard
Check if point is within a radius of another point (meters).
Parameters
center Center point
radius_m Radius in meters
Returns
true if this point is within radius_m of center
Definition at line 115 of file geometry.hpp.
References Point(), and is_within_km().
latitude()
Latitude muscovite::spatial::Point::latitude () const inline nodiscard constexpr
Definition at line 83 of file geometry.hpp.
longitude()
Longitude muscovite::spatial::Point::longitude () const inline nodiscard constexpr
Definition at line 84 of file geometry.hpp.
srid()
SRID muscovite::spatial::Point::srid () const inline nodiscard constexpr
Definition at line 85 of file geometry.hpp.
The documentation for this class was generated from the following file:
framework/spatial/include/muscovite/spatial/geometry.hpp