Muscovite C++ Framework: muscovite::qt::QtPositiveDecimal Class Reference
muscovite::qt::QtPositiveDecimal Class Reference
Qt-compatible positive decimal wrapper.
#include <qt_positive_decimal.hpp>
Public Member Functions
QtPositiveDecimal (double value)
Construct from double.
QtTypeBase ()=default
Default constructor creates empty value.
QtTypeBase (const char *value)
Construct from C string with validation.
QtTypeBase (const QString &value)
Construct with validation.
QtTypeBase (const std::string &value)
Construct from std::string with validation.
auto toDouble () const -> double
Convert to double.
Public Member Functions inherited from muscovite::qt::QtTypeBase< QtPositiveDecimal >
QtTypeBase ()=default
Default constructor creates empty value.
auto isEmpty () const noexcept -> bool
Check if empty.
auto operator!= (const QtTypeBase &other) const noexcept -> bool
Inequality comparison.
auto operator< (const QtTypeBase &other) const noexcept -> bool
Less-than for sorting.
auto operator== (const QtTypeBase &other) const noexcept -> bool
Equality comparison.
auto toStdString () const -> std::string
Convert to std::string.
auto toString () const noexcept -> QString
Convert to QString (alias for value()).
auto toVariant () const -> QVariant
Convert to QVariant for model/view.
auto value () const noexcept -> const QString &
Get the underlying QString value.
Static Public Member Functions
static auto isValid (QStringView value) -> bool
Validate positive decimal format.
static auto pattern () -> QString
Validation pattern.
static auto typeName () -> QString
Type name for error messages.
Static Public Member Functions inherited from muscovite::qt::QtTypeBase< QtPositiveDecimal >
static auto fromTrusted (QString value) noexcept -> QtPositiveDecimal
Construct from trusted source without validation.
Additional Inherited Members
Protected Attributes inherited from muscovite::qt::QtTypeBase< QtPositiveDecimal >
QString value_
Detailed Description
Qt-compatible positive decimal wrapper.
Stores decimal as QString to preserve exact representation.
Definition at line 23 of file qt_positive_decimal.hpp.
Constructor & Destructor Documentation
QtPositiveDecimal()
muscovite::qt::QtPositiveDecimal::QtPositiveDecimal (double value) inline explicit
Construct from double.
Definition at line 52 of file qt_positive_decimal.hpp.
References QtTypeBase(), muscovite::qt::QtTypeBase< QtPositiveDecimal >::toStdString(), and muscovite::qt::QtTypeBase< QtPositiveDecimal >::value().
Member Function Documentation
isValid()
auto muscovite::qt::QtPositiveDecimal::isValid (QStringView value) -> bool inline static nodiscard
Validate positive decimal format.
Definition at line 38 of file qt_positive_decimal.hpp.
References pattern(), and muscovite::qt::QtTypeBase< QtPositiveDecimal >::value().
pattern()
auto muscovite::qt::QtPositiveDecimal::pattern () -> QString inline static nodiscard
Validation pattern.
Definition at line 33 of file qt_positive_decimal.hpp.
Referenced by isValid().
QtTypeBase() [1/3]
muscovite::qt::QtTypeBase< Derived >::QtTypeBase (const char * value) inline explicit
Construct from C string with validation.
Definition at line 61 of file qt_type_base.hpp.
QtTypeBase() [2/3]
muscovite::qt::QtTypeBase< Derived >::QtTypeBase (const QString & value) inline explicit
Construct with validation.
Parameters
value The string value to wrap
Exceptions
std::invalid_argument if validation fails
Definition at line 47 of file qt_type_base.hpp.
QtTypeBase() [3/3]
muscovite::qt::QtTypeBase< Derived >::QtTypeBase (const std::string & value) inline explicit
Construct from std::string with validation.
Definition at line 57 of file qt_type_base.hpp.
toDouble()
auto muscovite::qt::QtPositiveDecimal::toDouble () const -> double inline nodiscard
Convert to double.
Definition at line 63 of file qt_positive_decimal.hpp.
typeName()
auto muscovite::qt::QtPositiveDecimal::typeName () -> QString inline static nodiscard
Type name for error messages.
Definition at line 28 of file qt_positive_decimal.hpp.
The documentation for this class was generated from the following file:
framework/qt/include/muscovite/qt/types/qt_positive_decimal.hpp