Muscovite C++ Framework: muscovite::qt::QtUrl Class Reference
muscovite::qt::QtUrl Class Reference
Qt-compatible URL wrapper.
#include <qt_url.hpp>
Public Member Functions
auto host () const -> QString
Extract host.
auto isSecure () const -> bool
Check if HTTPS (secure).
QtTypeBase ()=default
Default constructor creates empty value.
QtTypeBase (const char *value)
Construct from C string with validation.
QtTypeBase (const QString &value)
Construct with validation.
QtTypeBase (const std::string &value)
Construct from std::string with validation.
auto scheme () const -> QString
Extract protocol scheme.
auto toQUrl () const -> QUrl
Convert to QUrl for advanced operations.
Public Member Functions inherited from muscovite::qt::QtTypeBase< QtUrl >
QtTypeBase ()=default
Default constructor creates empty value.
auto isEmpty () const noexcept -> bool
Check if empty.
auto operator!= (const QtTypeBase &other) const noexcept -> bool
Inequality comparison.
auto operator< (const QtTypeBase &other) const noexcept -> bool
Less-than for sorting.
auto operator== (const QtTypeBase &other) const noexcept -> bool
Equality comparison.
auto toStdString () const -> std::string
Convert to std::string.
auto toString () const noexcept -> QString
Convert to QString (alias for value()).
auto toVariant () const -> QVariant
Convert to QVariant for model/view.
auto value () const noexcept -> const QString &
Get the underlying QString value.
Static Public Member Functions
static auto isValid (QStringView value) -> bool
Validate URL format.
static auto pattern () -> QString
Validation pattern (matches PostgreSQL CHECK).
static auto typeName () -> QString
Type name for error messages.
Static Public Member Functions inherited from muscovite::qt::QtTypeBase< QtUrl >
static auto fromTrusted (QString value) noexcept -> QtUrl
Construct from trusted source without validation.
Additional Inherited Members
Protected Attributes inherited from muscovite::qt::QtTypeBase< QtUrl >
QString value_
Detailed Description
Qt-compatible URL wrapper.
Provides validated URL with integration to QUrl for advanced parsing.
Definition at line 24 of file qt_url.hpp.
Member Function Documentation
host()
auto muscovite::qt::QtUrl::host () const -> QString inline nodiscard
Extract host.
Definition at line 56 of file qt_url.hpp.
References toQUrl().
isSecure()
auto muscovite::qt::QtUrl::isSecure () const -> bool inline nodiscard
Check if HTTPS (secure).
Definition at line 61 of file qt_url.hpp.
isValid()
auto muscovite::qt::QtUrl::isValid (QStringView value) -> bool inline static nodiscard
Validate URL format.
Definition at line 39 of file qt_url.hpp.
References pattern(), and muscovite::qt::QtTypeBase< QtUrl >::value().
pattern()
auto muscovite::qt::QtUrl::pattern () -> QString inline static nodiscard
Validation pattern (matches PostgreSQL CHECK).
Definition at line 34 of file qt_url.hpp.
Referenced by isValid().
QtTypeBase() [1/3]
muscovite::qt::QtTypeBase< Derived >::QtTypeBase (const char * value) inline explicit
Construct from C string with validation.
Definition at line 61 of file qt_type_base.hpp.
QtTypeBase() [2/3]
muscovite::qt::QtTypeBase< Derived >::QtTypeBase (const QString & value) inline explicit
Construct with validation.
Parameters
value The string value to wrap
Exceptions
std::invalid_argument if validation fails
Definition at line 47 of file qt_type_base.hpp.
QtTypeBase() [3/3]
muscovite::qt::QtTypeBase< Derived >::QtTypeBase (const std::string & value) inline explicit
Construct from std::string with validation.
Definition at line 57 of file qt_type_base.hpp.
scheme()
auto muscovite::qt::QtUrl::scheme () const -> QString inline nodiscard
Extract protocol scheme.
Definition at line 51 of file qt_url.hpp.
References toQUrl().
toQUrl()
auto muscovite::qt::QtUrl::toQUrl () const -> QUrl inline nodiscard
Convert to QUrl for advanced operations.
Definition at line 46 of file qt_url.hpp.
Referenced by host(), and scheme().
typeName()
auto muscovite::qt::QtUrl::typeName () -> QString inline static nodiscard
Type name for error messages.
Definition at line 29 of file qt_url.hpp.
The documentation for this class was generated from the following file:
framework/qt/include/muscovite/qt/types/qt_url.hpp