Muscovite C++ Framework: muscovite::qt::PrivilegeChecker Class Reference
muscovite::qt::PrivilegeChecker Class Reference
QML-friendly helper for privilege checking.
#include <privilege_checker.hpp>
Signals
void privilegesChanged ()
Emitted when privileges change (e.g., after login/logout).
Static Public Member Functions
static Q_INVOKABLE QString displayName ()
Get the current display name.
static Q_INVOKABLE bool has (const QString &privilege)
Check if the current user has a specific privilege.
static Q_INVOKABLE bool hasAll (const QStringList &privileges)
Check if the current user has all specified privileges.
static Q_INVOKABLE bool hasAny (const QStringList &privileges)
Check if the current user has any of the specified privileges.
static Q_INVOKABLE bool inGroup (const QString &group)
Check if the current user is in a specific group.
static PrivilegeChecker * instance ()
Get singleton instance.
static Q_INVOKABLE bool isAdmin ()
Check if the current user is an administrator.
static Q_INVOKABLE bool isAuthenticated ()
Check if the user is currently authenticated.
static Q_INVOKABLE QString username ()
Get the current username.
Detailed Description
QML-friendly helper for privilege checking.
This class provides a convenient interface for checking user privileges from QML, enabling conditional UI rendering based on permissions.
Usage in QML:
import Muscovite.Qt 1.0
Button {
    text: "Delete"
    visible: PrivilegeChecker.has("minerals:delete")
    enabled: PrivilegeChecker.has("minerals:delete")
    onClicked: mineralService.delete(mineralId)
}
// Or with any of several privileges
Button {
    text: "Edit"
    visible: PrivilegeChecker.hasAny(["minerals:write", "admin:*"])
}
Definition at line 41 of file privilege_checker.hpp.
Member Function Documentation
displayName()
QString muscovite::qt::PrivilegeChecker::displayName () static nodiscard
Get the current display name.
Returns
Display name or empty string
Definition at line 63 of file privilege_checker.cpp.
References muscovite::qt::AuthManager::displayName, and muscovite::qt::AuthManager::instance().
has()
bool muscovite::qt::PrivilegeChecker::has (const QString & privilege) static nodiscard
Check if the current user has a specific privilege.
Parameters
privilege Privilege name (e.g., "minerals:read")
Returns
true if user has the privilege
Definition at line 35 of file privilege_checker.cpp.
References muscovite::qt::AuthManager::hasPrivilege(), and muscovite::qt::AuthManager::instance().
hasAll()
bool muscovite::qt::PrivilegeChecker::hasAll (const QStringList & privileges) static nodiscard
Check if the current user has all specified privileges.
Parameters
privileges List of privilege names
Returns
true if user has all
Definition at line 43 of file privilege_checker.cpp.
References muscovite::qt::AuthManager::hasAllPrivileges(), and muscovite::qt::AuthManager::instance().
hasAny()
bool muscovite::qt::PrivilegeChecker::hasAny (const QStringList & privileges) static nodiscard
Check if the current user has any of the specified privileges.
Parameters
privileges List of privilege names
Returns
true if user has at least one
Definition at line 39 of file privilege_checker.cpp.
References muscovite::qt::AuthManager::hasAnyPrivilege(), and muscovite::qt::AuthManager::instance().
inGroup()
bool muscovite::qt::PrivilegeChecker::inGroup (const QString & group) static nodiscard
Check if the current user is in a specific group.
Parameters
group Group name
Returns
true if user is in the group
Definition at line 47 of file privilege_checker.cpp.
References muscovite::qt::AuthManager::instance(), and muscovite::qt::AuthManager::isInGroup().
instance()
PrivilegeChecker * muscovite::qt::PrivilegeChecker::instance () static
Get singleton instance.
Definition at line 24 of file privilege_checker.cpp.
References instance().
Referenced by instance().
isAdmin()
bool muscovite::qt::PrivilegeChecker::isAdmin () static nodiscard
Check if the current user is an administrator.
Returns
true if user is admin
Definition at line 51 of file privilege_checker.cpp.
References muscovite::qt::AuthManager::instance(), and muscovite::qt::AuthManager::isAdmin().
isAuthenticated()
bool muscovite::qt::PrivilegeChecker::isAuthenticated () static nodiscard
Check if the user is currently authenticated.
Returns
true if authenticated
Definition at line 55 of file privilege_checker.cpp.
References muscovite::qt::AuthManager::instance(), and muscovite::qt::AuthManager::isAuthenticated().
username()
QString muscovite::qt::PrivilegeChecker::username () static nodiscard
Get the current username.
Returns
Username or empty string
Definition at line 59 of file privilege_checker.cpp.
References muscovite::qt::AuthManager::instance(), and muscovite::qt::AuthManager::username.
The documentation for this class was generated from the following files:
framework/qt/include/muscovite/qt/auth/privilege_checker.hpp
framework/qt/src/auth/privilege_checker.cpp