Muscovite C++ Framework: muscovite::server::Server Class Reference
muscovite::server::Server Class Reference
Server lifecycle manager.
#include <server.hpp>
Public Member Functions
Server (Config config)
Construct a server with the given configuration.
Server (const Server &)=delete
Server (Server &&) noexcept
~Server ()
Destructor - ensures clean shutdown.
auto config () const noexcept -> const Config &
Get the current configuration.
auto is_running () const noexcept -> bool
Check if server is currently running.
void on_shutdown (std::function< void()> hook)
Register a callback to be invoked on shutdown.
void on_startup (std::function< void()> hook)
Register a callback to be invoked on startup.
Server & operator= (const Server &)=delete
Server & operator= (Server &&) noexcept
auto shutdown () -> std::expected< void, Error< ServerError > >
auto start () -> std::expected< void, Error< ServerError > >
void wait ()
Block until shutdown is complete.
Detailed Description
Server lifecycle manager.
Definition at line 31 of file server.hpp.
Constructor & Destructor Documentation
Server()
muscovite::server::Server::Server (Config config) explicit
Construct a server with the given configuration.
Definition at line 107 of file server.cpp.
References config().
Referenced by start().
~Server()
muscovite::server::Server::~Server ()
Destructor - ensures clean shutdown.
Definition at line 109 of file server.cpp.
Member Function Documentation
config()
auto muscovite::server::Server::config () const -> const Config & nodiscard noexcept
Get the current configuration.
Definition at line 134 of file server.cpp.
Referenced by Server().
is_running()
auto muscovite::server::Server::is_running () const -> bool nodiscard noexcept
Check if server is currently running.
Definition at line 130 of file server.cpp.
on_shutdown()
void muscovite::server::Server::on_shutdown (std::function< void()> hook)
Register a callback to be invoked on shutdown.
Definition at line 142 of file server.cpp.
on_startup()
void muscovite::server::Server::on_startup (std::function< void()> hook)
Register a callback to be invoked on startup.
Definition at line 138 of file server.cpp.
shutdown()
auto muscovite::server::Server::shutdown () -> std::expected< void, Error< ServerError > > nodiscard
Initiate graceful shutdown.
Returns
void on success, Error on failure
Definition at line 122 of file server.cpp.
start()
auto muscovite::server::Server::start () -> std::expected< void, Error< ServerError > > nodiscard
Start the server.
Returns
void on success, Error on failure
Definition at line 118 of file server.cpp.
References Server(), and start().
Referenced by start().
wait()
void muscovite::server::Server::wait ()
Block until shutdown is complete.
Definition at line 126 of file server.cpp.
The documentation for this class was generated from the following files:
framework/server/include/muscovite/server/server.hpp
framework/server/src/server.cpp