Muscovite C++ Framework: muscovite::qt::validation::GrpcUniquenessChecker Class Reference
muscovite::qt::validation::GrpcUniquenessChecker Class Reference abstract
Template for gRPC-based uniqueness checker.
#include <async_uniqueness_checker.hpp>
Public Member Functions
void cancel () override
Cancel any in-progress check.
void checkUniqueness (const QString &value, const QString &excludeId, UniquenessCallback callback) override
Check if a value is unique in the database.
Protected Member Functions
virtual void doCheck (const QString &value, const QString &excludeId, UniquenessCallback callback)=0
Implement the actual gRPC check.
Detailed Description
Template for gRPC-based uniqueness checker.
This template simplifies creating entity-specific uniqueness checkers. Implementations provide the gRPC call logic.
Example implementation:
class PatientMrnUniquenessChecker : public GrpcUniquenessChecker {
public:
    PatientMrnUniquenessChecker(std::shared_ptr<grpc::Channel> channel)
        : stub_(PatientService::NewStub(channel)) {}
protected:
    void doCheck(const QString& value, const QString& excludeId,
                 UniquenessCallback callback) override {
        // Create and execute async gRPC call
        CheckMrnUniquenessRequest request;
        request.set_mrn(value.toStdString());
        if (!excludeId.isEmpty()) {
            request.set_exclude_patient_id(excludeId.toStdString());
        }
        // ... async gRPC execution with callback
    }
private:
    std::unique_ptr<PatientService::Stub> stub_;
};
Definition at line 119 of file async_uniqueness_checker.hpp.
Member Function Documentation
cancel()
void muscovite::qt::validation::GrpcUniquenessChecker::cancel () override virtual
Cancel any in-progress check.
No-op for synchronous gRPC calls. For future async gRPC support, this would call ClientContext::TryCancel().
See also
AsyncUniquenessChecker::cancel()
Implements muscovite::qt::validation::AsyncUniquenessChecker.
Definition at line 17 of file async_uniqueness_checker.cpp.
Referenced by checkUniqueness().
checkUniqueness()
void muscovite::qt::validation::GrpcUniquenessChecker::checkUniqueness (const QString & value, const QString & excludeId, UniquenessCallback callback) override virtual
Check if a value is unique in the database.
Parameters
value The field value to check
excludeId Entity ID to exclude (current entity being edited), empty for new entities
callback Called with result (isUnique, conflictingId)
Implements muscovite::qt::validation::AsyncUniquenessChecker.
Definition at line 8 of file async_uniqueness_checker.cpp.
References cancel(), and doCheck().
doCheck()
virtual void muscovite::qt::validation::GrpcUniquenessChecker::doCheck (const QString & value, const QString & excludeId, UniquenessCallback callback) protected pure virtual
Implement the actual gRPC check.
Subclasses override this to make the service-specific gRPC call.
Referenced by checkUniqueness().
The documentation for this class was generated from the following files:
framework/qt/include/muscovite/qt/validation/async_uniqueness_checker.hpp
framework/qt/src/validation/async_uniqueness_checker.cpp