Muscovite C++ Framework: muscovite::qt::QtTypeBase< Derived > Class Template Reference
muscovite::qt::QtTypeBase< Derived > Class Template Reference
CRTP base class for Qt strong string-based types.
#include <qt_type_base.hpp>
Public Member Functions
QtTypeBase ()=default
Default constructor creates empty value.
QtTypeBase (const char *value)
Construct from C string with validation.
QtTypeBase (const QString &value)
Construct with validation.
QtTypeBase (const std::string &value)
Construct from std::string with validation.
auto isEmpty () const noexcept -> bool
Check if empty.
auto operator!= (const QtTypeBase &other) const noexcept -> bool
Inequality comparison.
auto operator< (const QtTypeBase &other) const noexcept -> bool
Less-than for sorting.
auto operator== (const QtTypeBase &other) const noexcept -> bool
Equality comparison.
auto toStdString () const -> std::string
Convert to std::string.
auto toString () const noexcept -> QString
Convert to QString (alias for value()).
auto toVariant () const -> QVariant
Convert to QVariant for model/view.
auto value () const noexcept -> const QString &
Get the underlying QString value.
Static Public Member Functions
static auto fromTrusted (QString value) noexcept -> Derived
Construct from trusted source without validation.
Protected Attributes
QString value_
Detailed Description
template<typename Derived>
class muscovite::qt::QtTypeBase< Derived >
CRTP base class for Qt strong string-based types.
Template Parameters
Derived The derived type (CRTP pattern)
Derived classes must provide:
static QString typeName() - Human-readable name for errors
static bool isValid(QStringView value) - Validation predicate
Definition at line 35 of file qt_type_base.hpp.
Constructor & Destructor Documentation
QtTypeBase() [1/3]
template<typename Derived> muscovite::qt::QtTypeBase< Derived >::QtTypeBase (const QString & value) inline explicit
Construct with validation.
Parameters
value The string value to wrap
Exceptions
std::invalid_argument if validation fails
Definition at line 47 of file qt_type_base.hpp.
References toStdString(), and value().
QtTypeBase() [2/3]
template<typename Derived> muscovite::qt::QtTypeBase< Derived >::QtTypeBase (const std::string & value) inline explicit
Construct from std::string with validation.
Definition at line 57 of file qt_type_base.hpp.
References QtTypeBase(), and value().
QtTypeBase() [3/3]
template<typename Derived> muscovite::qt::QtTypeBase< Derived >::QtTypeBase (const char * value) inline explicit
Construct from C string with validation.
Definition at line 61 of file qt_type_base.hpp.
References QtTypeBase(), and value().
Member Function Documentation
fromTrusted()
template<typename Derived> auto muscovite::qt::QtTypeBase< Derived >::fromTrusted (QString value) -> Derived inline static nodiscard noexcept
Construct from trusted source without validation.
Parameters
value The string value (assumed valid)
Returns
Constructed object
Definition at line 69 of file qt_type_base.hpp.
References value().
isEmpty()
template<typename Derived> auto muscovite::qt::QtTypeBase< Derived >::isEmpty () const -> bool inline nodiscard noexcept
Check if empty.
Definition at line 96 of file qt_type_base.hpp.
operator!=()
template<typename Derived> auto muscovite::qt::QtTypeBase< Derived >::operator!= (const QtTypeBase< Derived > & other) const -> bool inline nodiscard noexcept
Inequality comparison.
Definition at line 106 of file qt_type_base.hpp.
References QtTypeBase().
operator<()
template<typename Derived> auto muscovite::qt::QtTypeBase< Derived >::operator< (const QtTypeBase< Derived > & other) const -> bool inline nodiscard noexcept
Less-than for sorting.
Definition at line 111 of file qt_type_base.hpp.
References QtTypeBase().
operator==()
template<typename Derived> auto muscovite::qt::QtTypeBase< Derived >::operator== (const QtTypeBase< Derived > & other) const -> bool inline nodiscard noexcept
Equality comparison.
Definition at line 101 of file qt_type_base.hpp.
References QtTypeBase().
toStdString()
template<typename Derived> auto muscovite::qt::QtTypeBase< Derived >::toStdString () const -> std::string inline nodiscard
Convert to std::string.
Definition at line 86 of file qt_type_base.hpp.
Referenced by QtTypeBase().
toString()
template<typename Derived> auto muscovite::qt::QtTypeBase< Derived >::toString () const -> QString inline nodiscard noexcept
Convert to QString (alias for value()).
Definition at line 81 of file qt_type_base.hpp.
toVariant()
template<typename Derived> auto muscovite::qt::QtTypeBase< Derived >::toVariant () const -> QVariant inline nodiscard
Convert to QVariant for model/view.
Definition at line 91 of file qt_type_base.hpp.
value()
template<typename Derived> auto muscovite::qt::QtTypeBase< Derived >::value () const -> const QString & inline nodiscard noexcept
Get the underlying QString value.
Definition at line 76 of file qt_type_base.hpp.
Referenced by QtTypeBase(), QtTypeBase(), QtTypeBase(), and fromTrusted().
Member Data Documentation
value_
template<typename Derived> QString muscovite::qt::QtTypeBase< Derived >::value_ protected
Definition at line 116 of file qt_type_base.hpp.
The documentation for this class was generated from the following file:
framework/qt/include/muscovite/qt/types/qt_type_base.hpp