Muscovite C++ Framework: muscovite::grpc::GrpcServer Class Reference
muscovite::grpc::GrpcServer Class Reference
#include <server.hpp>
Public Member Functions
GrpcServer (const GrpcServer &)=delete
GrpcServer (GrpcServer &&) noexcept
GrpcServer (GrpcServerConfig config)
Construct server with configuration.
void add_interceptor (std::unique_ptr<::grpc::experimental::ServerInterceptorFactoryInterface > factory)
auto is_running () const noexcept -> bool
Check if server is running.
GrpcServer & operator= (const GrpcServer &)=delete
GrpcServer & operator= (GrpcServer &&) noexcept
auto port () const noexcept -> int
Get the bound port (useful when binding to port 0).
void register_service (::grpc::Service *service)
auto shutdown (std::chrono::milliseconds deadline=std::chrono::seconds{30}) -> std::expected< void, server::Error< GrpcServerError > >
auto start () -> std::expected< void, server::Error< GrpcServerError > >
void wait ()
Block until server is shut down.
Detailed Description
gRPC server lifecycle manager
Manages server startup, shutdown, and service registration. Uses PIMPL pattern for ABI stability.
Usage:
GrpcServer server{config};
server.register_service(&my_service);
server.start();
server.wait();  // Block until shutdown
Definition at line 58 of file server.hpp.
Constructor & Destructor Documentation
GrpcServer()
muscovite::grpc::GrpcServer::GrpcServer (GrpcServerConfig config) explicit
Construct server with configuration.
Definition at line 140 of file server.cpp.
Referenced by register_service().
~GrpcServer()
muscovite::grpc::GrpcServer::~GrpcServer ()
Definition at line 143 of file server.cpp.
Member Function Documentation
add_interceptor()
void muscovite::grpc::GrpcServer::add_interceptor (std::unique_ptr<::grpc::experimental::ServerInterceptorFactoryInterface > factory)
Add a server interceptor factory
Parameters
factory Interceptor factory (called per-RPC)
Definition at line 156 of file server.cpp.
is_running()
auto muscovite::grpc::GrpcServer::is_running () const -> bool nodiscard noexcept
Check if server is running.
Definition at line 174 of file server.cpp.
port()
auto muscovite::grpc::GrpcServer::port () const -> int nodiscard noexcept
Get the bound port (useful when binding to port 0).
Definition at line 178 of file server.cpp.
register_service()
void muscovite::grpc::GrpcServer::register_service (::grpc::Service * service)
Register a gRPC service before starting
Parameters
service The service implementation (must outlive server)
Definition at line 152 of file server.cpp.
References GrpcServer(), and register_service().
Referenced by register_service().
shutdown()
auto muscovite::grpc::GrpcServer::shutdown (std::chrono::milliseconds deadline = std::chrono::seconds{30}) -> std::expected< void, server::Error< GrpcServerError > > nodiscard
Initiate graceful shutdown
Parameters
deadline Maximum time to wait for in-flight RPCs
Definition at line 165 of file server.cpp.
start()
auto muscovite::grpc::GrpcServer::start () -> std::expected< void, server::Error< GrpcServerError > > nodiscard
Start the server
Returns
void on success, Error on failure
Definition at line 161 of file server.cpp.
wait()
void muscovite::grpc::GrpcServer::wait ()
Block until server is shut down.
Definition at line 170 of file server.cpp.
The documentation for this class was generated from the following files:
framework/grpc/include/muscovite/grpc/server.hpp
framework/grpc/src/server.cpp