Muscovite C++ Framework: muscovite::server::security::AuthorizationService Class Reference
muscovite::server::security::AuthorizationService Class Reference
Authorization service for privilege checking.
#include <authorization_service.hpp>
Classes
struct Config
Configuration options for AuthorizationService.
Public Member Functions
AuthorizationService (AuthorizationService &&) noexcept
AuthorizationService (const AuthorizationService &)=delete
AuthorizationService (const Config &config, std::shared_ptr< pqxx::connection > database)
Construct authorization service.
AccessCheckResult check_access (const std::string &principal_id, const std::string &resource, const std::string &action) const
Check if a user can access a resource with a given action.
void clear_cache () const
Clear all caches.
std::vector< std::string > get_user_groups (const std::string &principal_id) const
Get all groups for a user.
std::vector< std::string > get_user_privileges (const std::string &principal_id) const
Get all privileges for a user (via group membership).
bool has_all_privileges (const std::string &principal_id, const std::vector< std::string > &privilege_names) const
Check all of a set of privileges.
bool has_any_privilege (const std::string &principal_id, const std::vector< std::string > &privilege_names) const
Check any of a set of privileges.
bool has_privilege (const std::string &principal_id, const std::string &privilege_name) const
Check if a user has a specific privilege.
void invalidate_cache (const std::string &principal_id="")
Invalidate cached privileges for a user.
bool is_admin (const std::string &principal_id) const
Check if a user is an administrator.
bool is_in_group (const std::string &principal_id, const std::string &group_name) const
Check whether a user belongs to a specific group.
AuthorizationService & operator= (AuthorizationService &&) noexcept
AuthorizationService & operator= (const AuthorizationService &)=delete
Detailed Description
Authorization service for privilege checking.
This service handles group-based authorization:
Users belong to groups
Groups have privileges
Privileges define access to resources/actions
Privilege codes follow the pattern: {context}.{action} Examples: mineralogy.read, mineralogy.write, security.admin
Definition at line 48 of file authorization_service.hpp.
Constructor & Destructor Documentation
AuthorizationService()
muscovite::server::security::AuthorizationService::AuthorizationService (const Config & config, std::shared_ptr< pqxx::connection > database)
Construct authorization service.
Parameters
config Authorization configuration.
database pqxx connection used for queries.
Definition at line 152 of file authorization_service.cpp.
Referenced by has_privilege().
Member Function Documentation
check_access()
AccessCheckResult muscovite::server::security::AuthorizationService::check_access (const std::string & principal_id, const std::string & resource, const std::string & action) const nodiscard
Check if a user can access a resource with a given action.
This is a higher-level check that matches resource patterns.
Parameters
principal_id The user ID.
resource The resource path (e.g., "/mineralogy/minerals").
action The action (read, write, delete, admin).
Returns
true if access is allowed.
Definition at line 213 of file authorization_service.cpp.
References get_user_privileges(), and is_admin().
clear_cache()
void muscovite::server::security::AuthorizationService::clear_cache () const
Clear all caches.
Definition at line 310 of file authorization_service.cpp.
get_user_groups()
std::vector< std::string > muscovite::server::security::AuthorizationService::get_user_groups (const std::string & principal_id) const nodiscard
Get all groups for a user.
Parameters
principal_id The user ID.
Returns
List of group names.
Definition at line 268 of file authorization_service.cpp.
Referenced by is_in_group().
get_user_privileges()
std::vector< std::string > muscovite::server::security::AuthorizationService::get_user_privileges (const std::string & principal_id) const nodiscard
Get all privileges for a user (via group membership).
Parameters
principal_id The user ID.
Returns
List of privilege codes.
Definition at line 253 of file authorization_service.cpp.
Referenced by check_access(), has_all_privileges(), and has_any_privilege().
has_all_privileges()
bool muscovite::server::security::AuthorizationService::has_all_privileges (const std::string & principal_id, const std::vector< std::string > & privilege_names) const nodiscard
Check all of a set of privileges.
Definition at line 197 of file authorization_service.cpp.
References get_user_privileges().
has_any_privilege()
bool muscovite::server::security::AuthorizationService::has_any_privilege (const std::string & principal_id, const std::vector< std::string > & privilege_names) const nodiscard
Check any of a set of privileges.
Definition at line 181 of file authorization_service.cpp.
References get_user_privileges().
has_privilege()
bool muscovite::server::security::AuthorizationService::has_privilege (const std::string & principal_id, const std::string & privilege_name) const nodiscard
Check if a user has a specific privilege.
Parameters
principal_id The user ID.
privilege_name The privilege name (e.g., "mineralogy.read").
Returns
true if the user has the privilege via any group membership.
Definition at line 162 of file authorization_service.cpp.
References AuthorizationService(), and has_privilege().
Referenced by has_privilege().
invalidate_cache()
void muscovite::server::security::AuthorizationService::invalidate_cache (const std::string & principal_id = "")
Invalidate cached privileges for a user.
Call this after group membership or privilege changes.
Parameters
principal_id The user ID, or empty to clear all cache.
Definition at line 304 of file authorization_service.cpp.
is_admin()
bool muscovite::server::security::AuthorizationService::is_admin (const std::string & principal_id) const nodiscard
Check if a user is an administrator.
Administrators have the "security.admin" privilege.
Parameters
principal_id The user ID.
Returns
true if the user is an admin.
Definition at line 283 of file authorization_service.cpp.
References is_admin().
Referenced by check_access(), and is_admin().
is_in_group()
bool muscovite::server::security::AuthorizationService::is_in_group (const std::string & principal_id, const std::string & group_name) const nodiscard
Check whether a user belongs to a specific group.
Definition at line 296 of file authorization_service.cpp.
References get_user_groups().
The documentation for this class was generated from the following files:
framework/server/include/muscovite/server/security/authorization_service.hpp
framework/server/src/security/authorization_service.cpp