Muscovite C++ Framework: muscovite::qt::validation::ValidationMessage Class Reference
muscovite::qt::validation::ValidationMessage Class Reference
A single validation message (error or warning).
#include <validation_result.hpp>
Public Member Functions
ValidationMessage (ValidationCode code, QString fieldName, QString detail={})
ValidationCode code () const
QString detail () const
QString fieldName () const
bool isError () const
bool isWarning () const
ValidationSeverity severity () const
QString toHtml () const
Format as HTML (errors red, warnings orange).
QString toString () const
Format the message for display (e.g., "VAL010: Email - Invalid email format").
Static Public Member Functions
static ValidationMessage custom (const QString &fieldName, const QString &customMessage, bool isWarning=false)
Create a custom validation message.
Detailed Description
A single validation message (error or warning).
Definition at line 22 of file validation_result.hpp.
Constructor & Destructor Documentation
ValidationMessage()
muscovite::qt::validation::ValidationMessage::ValidationMessage (ValidationCode code, QString fieldName, QString detail = {})
Definition at line 22 of file validation_result.cpp.
Member Function Documentation
code()
ValidationCode muscovite::qt::validation::ValidationMessage::code () const inline nodiscard
Definition at line 29 of file validation_result.hpp.
custom()
ValidationMessage muscovite::qt::validation::ValidationMessage::custom (const QString & fieldName, const QString & customMessage, bool isWarning = false) static
Create a custom validation message.
Definition at line 25 of file validation_result.cpp.
References custom().
Referenced by custom(), and muscovite::qt::grpc::toValidationMessage().
detail()
QString muscovite::qt::validation::ValidationMessage::detail () const inline nodiscard
Definition at line 31 of file validation_result.hpp.
fieldName()
QString muscovite::qt::validation::ValidationMessage::fieldName () const inline nodiscard
Definition at line 30 of file validation_result.hpp.
isError()
bool muscovite::qt::validation::ValidationMessage::isError () const inline nodiscard
Definition at line 33 of file validation_result.hpp.
isWarning()
bool muscovite::qt::validation::ValidationMessage::isWarning () const inline nodiscard
Definition at line 34 of file validation_result.hpp.
severity()
ValidationSeverity muscovite::qt::validation::ValidationMessage::severity () const inline nodiscard
Definition at line 32 of file validation_result.hpp.
toHtml()
QString muscovite::qt::validation::ValidationMessage::toHtml () const nodiscard
Format as HTML (errors red, warnings orange).
Definition at line 47 of file validation_result.cpp.
References toHtml().
Referenced by toHtml().
toString()
QString muscovite::qt::validation::ValidationMessage::toString () const nodiscard
Format the message for display (e.g., "VAL010: Email - Invalid email format").
Definition at line 33 of file validation_result.cpp.
References toString().
Referenced by toString().
The documentation for this class was generated from the following files:
framework/qt/include/muscovite/qt/validation/validation_result.hpp
framework/qt/src/validation/validation_result.cpp