Muscovite C++ Framework: muscovite::types::PatternString< Pattern > Class Template Reference
muscovite::types::PatternString< Pattern > Class Template Reference
Public Types
using value_type = std::string
Public Member Functions
operator std::string_view () const noexcept
Implicit conversion to string_view.
auto operator<=> (const PatternString &) const noexcept=default
Three-way comparison.
auto operator== (const PatternString &) const noexcept -> bool=default
Equality.
auto value () const noexcept -> const std::string &
Get the underlying string value.
Static Public Member Functions
static auto from_trusted (std::string value) noexcept -> PatternString
Construct from trusted source without validation (DB loads).
static auto is_valid (std::string_view sv) noexcept -> bool
Validate string against the regex pattern.
static constexpr auto pattern () noexcept -> const char *
Get the pattern as string_view.
static auto try_from (std::string_view sv) -> std::expected< PatternString, std::string >
Try to construct from a string value.
Detailed Description
template<StringLiteral Pattern>
class muscovite::types::PatternString< Pattern >
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/pattern_string.hpp.
Definition at line 42 of file pattern_string.hpp.
Member Typedef Documentation
value_type
template<StringLiteral Pattern> using muscovite::types::PatternString< Pattern >::value_type = std::string
Definition at line 44 of file pattern_string.hpp.
Member Function Documentation
from_trusted()
template<StringLiteral Pattern> auto muscovite::types::PatternString< Pattern >::from_trusted (std::string value) -> PatternString inline static nodiscard noexcept
Construct from trusted source without validation (DB loads).
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/pattern_string.hpp.
Definition at line 72 of file pattern_string.hpp.
References value().
is_valid()
template<StringLiteral Pattern> auto muscovite::types::PatternString< Pattern >::is_valid (std::string_view sv) -> bool inline static nodiscard noexcept
Validate string against the regex pattern.
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/pattern_string.hpp.
Definition at line 52 of file pattern_string.hpp.
Referenced by try_from().
operator std::string_view()
template<StringLiteral Pattern> muscovite::types::PatternString< Pattern >::operator std::string_view () const inline nodiscard noexcept
Implicit conversion to string_view.
Definition at line 83 of file pattern_string.hpp.
pattern()
template<StringLiteral Pattern> constexpr auto muscovite::types::PatternString< Pattern >::pattern () -> const char * inline static nodiscard constexpr noexcept
Get the pattern as string_view.
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/pattern_string.hpp.
Definition at line 47 of file pattern_string.hpp.
try_from()
template<StringLiteral Pattern> auto muscovite::types::PatternString< Pattern >::try_from (std::string_view sv) -> std::expected< PatternString, std::string > inline static nodiscard
Try to construct from a string value.
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/pattern_string.hpp.
Definition at line 61 of file pattern_string.hpp.
References is_valid().
value()
template<StringLiteral Pattern> auto muscovite::types::PatternString< Pattern >::value () const -> const std::string & inline nodiscard noexcept
Get the underlying string value.
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/pattern_string.hpp.
Definition at line 78 of file pattern_string.hpp.
Referenced by from_trusted().
The documentation for this class was generated from the following file:
framework/types/include/muscovite/types/pattern_string.hpp