Muscovite C++ Framework: muscovite::dba::PooledConnection Class Reference
muscovite::dba::PooledConnection Class Reference
#include <connection_pool.hpp>
Public Member Functions
PooledConnection (const PooledConnection &)=delete
PooledConnection (PooledConnection &&) noexcept
auto get () -> pqxx::connection &
Get the underlying connection.
auto get () const -> const pqxx::connection &
auto is_open () const -> bool
Check if connection is open.
auto operator-> () -> pqxx::connection *
Arrow operator for direct access.
auto operator-> () const -> const pqxx::connection *
PooledConnection & operator= (const PooledConnection &)=delete
PooledConnection & operator= (PooledConnection &&) noexcept
Friends
class ConnectionPool
Detailed Description
RAII wrapper for a pooled connection. Returns connection to pool on destruction.
Definition at line 52 of file connection_pool.hpp.
Constructor & Destructor Documentation
PooledConnection()
muscovite::dba::PooledConnection::PooledConnection (PooledConnection && other) noexcept
Definition at line 242 of file connection_pool.cpp.
~PooledConnection()
muscovite::dba::PooledConnection::~PooledConnection ()
Definition at line 259 of file connection_pool.cpp.
Member Function Documentation
get() [1/2]
auto muscovite::dba::PooledConnection::get () -> pqxx::connection & nodiscard
Get the underlying connection.
Definition at line 265 of file connection_pool.cpp.
References get().
Referenced by get().
get() [2/2]
auto muscovite::dba::PooledConnection::get () const -> const pqxx::connection & nodiscard
Definition at line 269 of file connection_pool.cpp.
is_open()
auto muscovite::dba::PooledConnection::is_open () const -> bool nodiscard
Check if connection is open.
Definition at line 281 of file connection_pool.cpp.
References is_open().
Referenced by is_open().
operator->() [1/2]
auto muscovite::dba::PooledConnection::operator-> () -> pqxx::connection * nodiscard
Arrow operator for direct access.
Definition at line 273 of file connection_pool.cpp.
References operator->().
Referenced by operator->().
operator->() [2/2]
auto muscovite::dba::PooledConnection::operator-> () const -> const pqxx::connection * nodiscard
Definition at line 277 of file connection_pool.cpp.
operator=()
PooledConnection & muscovite::dba::PooledConnection::operator= (PooledConnection && other) noexcept
Definition at line 247 of file connection_pool.cpp.
Friends And Related Symbol Documentation
ConnectionPool
friend class ConnectionPool friend
Definition at line 74 of file connection_pool.hpp.
The documentation for this class was generated from the following files:
framework/dba/include/muscovite/dba/connection_pool.hpp
framework/dba/src/connection_pool.cpp