Muscovite C++ Framework: muscovite::qt::widgets::WktValidator Class Reference
muscovite::qt::widgets::WktValidator Class Reference
Validator for WKT geometry strings.
#include <wkt_edit.hpp>
Public Member Functions
WktValidator (GeometryType allowedType, QObject *parent=nullptr)
WktValidator (QObject *parent=nullptr)
GeometryType allowedType () const
void setAllowedType (GeometryType type)
Set which geometry type is allowed (default: Any).
QValidator::State validate (QString &input, int &pos) const override
QValidator interface.
WktValidationResult validateWkt (const QString &wkt) const
Full validation with detailed result.
Static Public Member Functions
static WktValidationResult validate (const QString &wkt, GeometryType allowedType=GeometryType::Any)
Static validation helper.
Detailed Description
Validator for WKT geometry strings.
Validates WKT syntax and optionally restricts to specific geometry types. Does NOT validate against a coordinate reference system - that requires PostGIS or a full geometry library.
Definition at line 58 of file wkt_edit.hpp.
Constructor & Destructor Documentation
WktValidator() [1/2]
muscovite::qt::widgets::WktValidator::WktValidator (QObject * parent = nullptr) explicit
Definition at line 21 of file wkt_edit.cpp.
WktValidator() [2/2]
muscovite::qt::widgets::WktValidator::WktValidator (GeometryType allowedType, QObject * parent = nullptr) explicit
Definition at line 25 of file wkt_edit.cpp.
Member Function Documentation
allowedType()
GeometryType muscovite::qt::widgets::WktValidator::allowedType () const inline nodiscard
Definition at line 68 of file wkt_edit.hpp.
setAllowedType()
void muscovite::qt::widgets::WktValidator::setAllowedType (GeometryType type) inline
Set which geometry type is allowed (default: Any).
Definition at line 67 of file wkt_edit.hpp.
validate() [1/2]
WktValidationResult muscovite::qt::widgets::WktValidator::validate (const QString & wkt, GeometryType allowedType = GeometryType::Any) static
Static validation helper.
Definition at line 43 of file wkt_edit.cpp.
References validate().
validate() [2/2]
QValidator::State muscovite::qt::widgets::WktValidator::validate (QString & input, int & pos) const override
QValidator interface.
Definition at line 30 of file wkt_edit.cpp.
References validate(), and validateWkt().
Referenced by validate(), validate(), and validateWkt().
validateWkt()
WktValidationResult muscovite::qt::widgets::WktValidator::validateWkt (const QString & wkt) const nodiscard
Full validation with detailed result.
Definition at line 39 of file wkt_edit.cpp.
References validate(), and validateWkt().
Referenced by validate(), and validateWkt().
The documentation for this class was generated from the following files:
framework/qt/include/muscovite/qt/widgets/wkt_edit.hpp
framework/qt/src/widgets/wkt_edit.cpp