Muscovite C++ Framework: muscovite::qt::OAuth2AuthManager Class Reference
muscovite::qt::OAuth2AuthManager Class Reference
Signals
void authError (const QString &message)
void authStateChanged ()
void tokenRefreshed ()
Public Member Functions
OAuth2AuthManager (QObject *parent=nullptr)
QString accessToken () const
QString buildAuthorizationUrl ()
Builds the authorization URL (Authorization Code + PKCE).
QFuture< bool > completeAuthorization (const QString &code)
Completes the OAuth2 flow with the returned code.
void configure (const OAuth2QtConfig &cfg)
bool isAuthenticated () const
QFuture< void > logout ()
Logout and revoke tokens if possible.
QFuture< bool > refreshIfNeeded ()
Attempts to refresh the access token if close to expiry.
std::optional< OAuth2Session > session () const
QString subject () const
Properties
QString accessToken
bool authenticated
QString subject
Detailed Description
Definition at line 36 of file oauth2_auth_manager.hpp.
Constructor & Destructor Documentation
OAuth2AuthManager()
muscovite::qt::OAuth2AuthManager::OAuth2AuthManager (QObject * parent = nullptr) explicit
Definition at line 22 of file oauth2_auth_manager.cpp.
Member Function Documentation
accessToken()
QString muscovite::qt::OAuth2AuthManager::accessToken () const
Definition at line 39 of file oauth2_auth_manager.cpp.
buildAuthorizationUrl()
QString muscovite::qt::OAuth2AuthManager::buildAuthorizationUrl ()
Builds the authorization URL (Authorization Code + PKCE).
Definition at line 54 of file oauth2_auth_manager.cpp.
References buildAuthorizationUrl().
Referenced by buildAuthorizationUrl().
completeAuthorization()
QFuture< bool > muscovite::qt::OAuth2AuthManager::completeAuthorization (const QString & code)
Completes the OAuth2 flow with the returned code.
Definition at line 61 of file oauth2_auth_manager.cpp.
References completeAuthorization().
Referenced by completeAuthorization().
configure()
void muscovite::qt::OAuth2AuthManager::configure (const OAuth2QtConfig & cfg)
Definition at line 28 of file oauth2_auth_manager.cpp.
isAuthenticated()
bool muscovite::qt::OAuth2AuthManager::isAuthenticated () const
Definition at line 34 of file oauth2_auth_manager.cpp.
logout()
QFuture< void > muscovite::qt::OAuth2AuthManager::logout ()
Logout and revoke tokens if possible.
Definition at line 108 of file oauth2_auth_manager.cpp.
References logout().
Referenced by logout().
refreshIfNeeded()
QFuture< bool > muscovite::qt::OAuth2AuthManager::refreshIfNeeded ()
Attempts to refresh the access token if close to expiry.
Definition at line 94 of file oauth2_auth_manager.cpp.
References refreshIfNeeded().
Referenced by refreshIfNeeded().
session()
std::optional< OAuth2Session > muscovite::qt::OAuth2AuthManager::session () const
Definition at line 49 of file oauth2_auth_manager.cpp.
subject()
QString muscovite::qt::OAuth2AuthManager::subject () const
Definition at line 44 of file oauth2_auth_manager.cpp.
Property Documentation
accessToken
QString muscovite::qt::OAuth2AuthManager::accessToken read
Definition at line 40 of file oauth2_auth_manager.hpp.
authenticated
bool muscovite::qt::OAuth2AuthManager::authenticated read
Definition at line 39 of file oauth2_auth_manager.hpp.
subject
QString muscovite::qt::OAuth2AuthManager::subject read
Definition at line 41 of file oauth2_auth_manager.hpp.
The documentation for this class was generated from the following files:
framework/qt/include/muscovite/qt/auth/oauth2_auth_manager.hpp
framework/qt/src/auth/oauth2_auth_manager.cpp