Muscovite C++ Framework: muscovite::qt::widgets::CoordinateValidator Class Reference
muscovite::qt::widgets::CoordinateValidator Class Reference
Validator for geographic coordinates.
#include <spatial_widgets.hpp>
Public Types
enum class Type { Latitude , Longitude , Radius }
Public Member Functions
CoordinateValidator (Type type, QObject *parent=nullptr)
bool isValid (double value) const
Check if a coordinate value is valid for this validator's type.
QString rangeDescription () const
Get human-readable range description for this coordinate type.
Type type () const
State validate (QString &input, int &pos) const override
Validate coordinate value and return validation state.
std::optional< validation::ValidationCode > validationCode (double value) const
Get validation error code if value is invalid.
Detailed Description
Validator for geographic coordinates.
Validates:
Latitude: [-90, 90]
Longitude: [-180, 180]
Decimal precision: 6 decimal places (±0.000001 degrees)
Can be used with QLineEdit or QDoubleSpinBox for immediate validation feedback.
Definition at line 50 of file spatial_widgets.hpp.
Member Enumeration Documentation
Type
enum class muscovite::qt::widgets::CoordinateValidator::Type strong
Definition at line 54 of file spatial_widgets.hpp.
Constructor & Destructor Documentation
CoordinateValidator()
muscovite::qt::widgets::CoordinateValidator::CoordinateValidator (Type type, QObject * parent = nullptr) explicit
Definition at line 29 of file spatial_widgets.cpp.
Member Function Documentation
isValid()
bool muscovite::qt::widgets::CoordinateValidator::isValid (double value) const nodiscard
Check if a coordinate value is valid for this validator's type.
Parameters
value The coordinate value to check
Returns
true if valid, false otherwise
Definition at line 54 of file spatial_widgets.cpp.
References isValid().
Referenced by isValid(), validate(), and validationCode().
rangeDescription()
QString muscovite::qt::widgets::CoordinateValidator::rangeDescription () const nodiscard
Get human-readable range description for this coordinate type.
Definition at line 103 of file spatial_widgets.cpp.
References rangeDescription().
Referenced by rangeDescription().
type()
Type muscovite::qt::widgets::CoordinateValidator::type () const inline nodiscard
Definition at line 88 of file spatial_widgets.hpp.
validate()
QValidator::State muscovite::qt::widgets::CoordinateValidator::validate (QString & input, int & pos) const override
Validate coordinate value and return validation state.
Returns
Acceptable if value is valid, Intermediate if needs more input, Invalid if definitely wrong
Definition at line 35 of file spatial_widgets.cpp.
References isValid(), and validate().
Referenced by validate().
validationCode()
std::optional< validation::ValidationCode > muscovite::qt::widgets::CoordinateValidator::validationCode (double value) const nodiscard
Get validation error code if value is invalid.
Parameters
value The value to check
Returns
ValidationCode if invalid, std::nullopt if valid
Definition at line 67 of file spatial_widgets.cpp.
References isValid(), and validationCode().
Referenced by validationCode().
The documentation for this class was generated from the following files:
framework/qt/include/muscovite/qt/widgets/spatial_widgets.hpp
framework/qt/src/widgets/spatial_widgets.cpp