Muscovite C++ Framework: muscovite::qt::QInfrastructureStateMachineBase Class Reference
muscovite::qt::QInfrastructureStateMachineBase Class Reference
Qt-based infrastructure state machine for frontend circuit breakers.
#include <q_infrastructure_state_machine.hpp>
Signals
void circuitClosed ()
Emitted when circuit recovers to Closed after successful probe.
void circuitHalfOpened ()
Emitted when circuit enters Half-Open probe state.
void circuitOpened ()
Emitted when circuit trips to Open (failures exceeded threshold).
void stateNameChanged ()
Emitted when stateName property changes.
Public Member Functions
QInfrastructureStateMachineBase (int failure_threshold=3, int probe_interval_ms=5000, QObject *parent=nullptr)
Construct and wire the three-state circuit breaker machine.
auto failureCount () const noexcept -> int
Number of consecutive failures in current cycle.
auto failureThreshold () const noexcept -> int
Configured failure threshold.
void recordFailure ()
Record a failed call. Increments failure count, may trip circuit.
void recordSuccess ()
Record a successful call. Resets failure count and returns to Closed.
void resetCircuit ()
Manual reset to Closed state.
auto stateName () const -> QString
Current state name ("Closed", "Open", or "HalfOpen").
Protected Member Functions
virtual void onHalfOpen ()
Called when circuit enters Half-Open. Override for probe setup.
virtual void onOpen ()
Called when circuit trips to Open. Override for plugin-specific behavior.
virtual void onTrip ()
Called on the failure that trips the circuit. Override for logging.
Protected Attributes
QState * closed_state_ {}
The Closed state object.
QState * half_open_state_ {}
The Half-Open state object.
QState * open_state_ {}
The Open state object.
Properties
QString stateName
Current state name as a string property.
Detailed Description
Qt-based infrastructure state machine for frontend circuit breakers.
Provides three states (Closed, Open, Half-Open) with Qt signals for UI integration. Generated FE circuit breakers derive from this class and override onOpen()/onHalfOpen()/onTrip() for plugin-specific behavior.
Signal Flow
circuitOpened() → disable plugin-dependent UI sections
circuitHalfOpened() → show "recovering..." indicator
circuitClosed() → re-enable plugin-dependent UI sections
See also
ADR 20260223-circuit-breaker-as-infrastructure-state-machine
Definition at line 40 of file q_infrastructure_state_machine.hpp.
Constructor & Destructor Documentation
QInfrastructureStateMachineBase()
muscovite::qt::QInfrastructureStateMachineBase::QInfrastructureStateMachineBase (int failure_threshold = 3, int probe_interval_ms = 5000, QObject * parent = nullptr) explicit
Construct and wire the three-state circuit breaker machine.
Parameters
failure_threshold Consecutive failures before tripping to Open.
probe_interval_ms Milliseconds between probe attempts in Open state.
parent Qt parent object.
Definition at line 18 of file q_infrastructure_state_machine.cpp.
References closed_state_.
Member Function Documentation
failureCount()
auto muscovite::qt::QInfrastructureStateMachineBase::failureCount () const -> int inline nodiscard noexcept
Number of consecutive failures in current cycle.
Definition at line 62 of file q_infrastructure_state_machine.hpp.
References failureCount().
Referenced by failureCount().
failureThreshold()
auto muscovite::qt::QInfrastructureStateMachineBase::failureThreshold () const -> int inline nodiscard noexcept
Configured failure threshold.
Definition at line 65 of file q_infrastructure_state_machine.hpp.
onHalfOpen()
virtual void muscovite::qt::QInfrastructureStateMachineBase::onHalfOpen () inline protected virtual
Called when circuit enters Half-Open. Override for probe setup.
Definition at line 102 of file q_infrastructure_state_machine.hpp.
onOpen()
virtual void muscovite::qt::QInfrastructureStateMachineBase::onOpen () inline protected virtual
Called when circuit trips to Open. Override for plugin-specific behavior.
Definition at line 99 of file q_infrastructure_state_machine.hpp.
onTrip()
virtual void muscovite::qt::QInfrastructureStateMachineBase::onTrip () inline protected virtual
Called on the failure that trips the circuit. Override for logging.
Definition at line 105 of file q_infrastructure_state_machine.hpp.
Referenced by recordFailure().
recordFailure()
void muscovite::qt::QInfrastructureStateMachineBase::recordFailure ()
Record a failed call. Increments failure count, may trip circuit.
Definition at line 58 of file q_infrastructure_state_machine.cpp.
References half_open_state_, and onTrip().
recordSuccess()
void muscovite::qt::QInfrastructureStateMachineBase::recordSuccess ()
Record a successful call. Resets failure count and returns to Closed.
Definition at line 50 of file q_infrastructure_state_machine.cpp.
References half_open_state_.
resetCircuit()
void muscovite::qt::QInfrastructureStateMachineBase::resetCircuit ()
Manual reset to Closed state.
Definition at line 74 of file q_infrastructure_state_machine.cpp.
stateName()
auto muscovite::qt::QInfrastructureStateMachineBase::stateName () const -> QString nodiscard
Current state name ("Closed", "Open", or "HalfOpen").
Definition at line 36 of file q_infrastructure_state_machine.cpp.
References closed_state_, half_open_state_, and open_state_.
Member Data Documentation
closed_state_
QState* muscovite::qt::QInfrastructureStateMachineBase::closed_state_ {} protected
The Closed state object.
Definition at line 107 of file q_infrastructure_state_machine.hpp.
Referenced by QInfrastructureStateMachineBase(), and stateName().
half_open_state_
QState* muscovite::qt::QInfrastructureStateMachineBase::half_open_state_ {} protected
The Half-Open state object.
Definition at line 109 of file q_infrastructure_state_machine.hpp.
Referenced by recordFailure(), recordSuccess(), and stateName().
open_state_
QState* muscovite::qt::QInfrastructureStateMachineBase::open_state_ {} protected
The Open state object.
Definition at line 108 of file q_infrastructure_state_machine.hpp.
Referenced by stateName().
Property Documentation
stateName
QString muscovite::qt::QInfrastructureStateMachineBase::stateName read
Current state name as a string property.
Definition at line 44 of file q_infrastructure_state_machine.hpp.
The documentation for this class was generated from the following files:
framework/qt/include/muscovite/qt/q_infrastructure_state_machine.hpp
framework/qt/src/q_infrastructure_state_machine.cpp