Muscovite C++ Framework: muscovite::search::SearchError Class Reference
muscovite::search::SearchError Class Reference
Base exception for all OpenSearch errors.
#include <search_error.hpp>
Public Member Functions
SearchError (const std::string &message, std::int32_t http_status, std::string response_body)
Construct a search error.
auto http_status () const noexcept -> std::int32_t
HTTP status code from the failed request.
auto response_body () const noexcept -> const std::string &
Raw response body from OpenSearch.
Detailed Description
Base exception for all OpenSearch errors.
Carries the HTTP status code (0 if connection-level failure) and the response body for diagnostics.
See also
OpenSearchClient — throws these on non-2xx responses
Definition at line 27 of file search_error.hpp.
Constructor & Destructor Documentation
SearchError()
muscovite::search::SearchError::SearchError (const std::string & message, std::int32_t http_status, std::string response_body) inline
Construct a search error.
Parameters
message Human-readable error description
http_status HTTP status code (0 for connection errors)
response_body Raw response body from OpenSearch
Definition at line 33 of file search_error.hpp.
References http_status(), and response_body().
Referenced by muscovite::search::SearchConnectionError::SearchConnectionError().
Member Function Documentation
http_status()
auto muscovite::search::SearchError::http_status () const -> std::int32_t inline nodiscard noexcept
HTTP status code from the failed request.
Returns
Status code, or 0 for connection-level failures.
Definition at line 42 of file search_error.hpp.
Referenced by SearchError().
response_body()
auto muscovite::search::SearchError::response_body () const -> const std::string & inline nodiscard noexcept
Raw response body from OpenSearch.
Returns
JSON string with OpenSearch error details, or empty for connection errors.
Definition at line 48 of file search_error.hpp.
Referenced by SearchError().
The documentation for this class was generated from the following file:
framework/search/include/muscovite/search/search_error.hpp