Muscovite C++ Framework: muscovite::geo::LineString< Srid > Class Template Reference
muscovite::geo::LineString< Srid > Class Template Reference
Geographic linestring (sequence of connected points).
#include <geography.hpp>
Public Types
using point_type = Point<Srid>
using srid_tag = Srid
Public Member Functions
LineString ()=default
Default constructor (empty linestring).
LineString (const std::vector< point_type > &points)
Construct from vector of points.
LineString (std::initializer_list< point_type > points)
Construct from initializer list.
point_type at (std::size_t idx) const
Access point at index.
BoundingBox< Srid > bounds () const
Get bounding box of this linestring.
bool empty () const noexcept
Check if linestring is empty.
double length_meters () const
Calculate total length in meters (geodetic).
const bg_linestring & native () const noexcept
Access underlying Boost.Geometry linestring.
bg_linestring & native () noexcept
void push_back (const point_type &point)
Add a point to the end.
std::size_t size () const noexcept
Number of points in linestring.
std::string to_ewkt () const
Convert to EWKT.
std::string to_wkt () const
Convert to WKT.
Static Public Attributes
static constexpr int srid = Srid::value
Detailed Description
template<SridTag Srid>
class muscovite::geo::LineString< Srid >
Geographic linestring (sequence of connected points).
Template Parameters
Srid SRID tag type
Definition at line 403 of file geography.hpp.
Member Typedef Documentation
point_type
template<SridTag Srid> using muscovite::geo::LineString< Srid >::point_type = Point<Srid>
Definition at line 407 of file geography.hpp.
srid_tag
template<SridTag Srid> using muscovite::geo::LineString< Srid >::srid_tag = Srid
Definition at line 405 of file geography.hpp.
Constructor & Destructor Documentation
LineString() [1/2]
template<SridTag Srid> muscovite::geo::LineString< Srid >::LineString (const std::vector< point_type > & points) inline explicit
Construct from vector of points.
Definition at line 419 of file geography.hpp.
LineString() [2/2]
template<SridTag Srid> muscovite::geo::LineString< Srid >::LineString (std::initializer_list< point_type > points) inline
Construct from initializer list.
Definition at line 426 of file geography.hpp.
Member Function Documentation
at()
template<SridTag Srid> point_type muscovite::geo::LineString< Srid >::at (std::size_t idx) const inline nodiscard
Access point at index.
Definition at line 444 of file geography.hpp.
bounds()
template<SridTag Srid> BoundingBox< Srid > muscovite::geo::LineString< Srid >::bounds () const inline nodiscard
Get bounding box of this linestring.
Definition at line 479 of file geography.hpp.
empty()
template<SridTag Srid> bool muscovite::geo::LineString< Srid >::empty () const inline nodiscard noexcept
Check if linestring is empty.
Definition at line 441 of file geography.hpp.
Referenced by muscovite::geo::LineString< srid_4326 >::bounds(), and muscovite::geo::LineString< srid_4326 >::to_wkt().
length_meters()
template<SridTag Srid> double muscovite::geo::LineString< Srid >::length_meters () const inline nodiscard
Calculate total length in meters (geodetic).
Definition at line 454 of file geography.hpp.
Referenced by muscovite::geo::MultiLineString< srid_4326 >::total_length_meters().
native() [1/2]
template<SridTag Srid> const bg_linestring & muscovite::geo::LineString< Srid >::native () const inline nodiscard noexcept
Access underlying Boost.Geometry linestring.
Definition at line 450 of file geography.hpp.
native() [2/2]
template<SridTag Srid> bg_linestring & muscovite::geo::LineString< Srid >::native () inline nodiscard noexcept
Definition at line 451 of file geography.hpp.
push_back()
template<SridTag Srid> void muscovite::geo::LineString< Srid >::push_back (const point_type & point) inline
Add a point to the end.
Definition at line 433 of file geography.hpp.
size()
template<SridTag Srid> std::size_t muscovite::geo::LineString< Srid >::size () const inline nodiscard noexcept
Number of points in linestring.
Definition at line 438 of file geography.hpp.
to_ewkt()
template<SridTag Srid> std::string muscovite::geo::LineString< Srid >::to_ewkt () const inline nodiscard
Convert to EWKT.
Definition at line 474 of file geography.hpp.
to_wkt()
template<SridTag Srid> std::string muscovite::geo::LineString< Srid >::to_wkt () const inline nodiscard
Convert to WKT.
Definition at line 461 of file geography.hpp.
Referenced by muscovite::geo::LineString< srid_4326 >::to_ewkt().
Member Data Documentation
srid
template<SridTag Srid> int muscovite::geo::LineString< Srid >::srid = Srid::value static constexpr
Definition at line 406 of file geography.hpp.
The documentation for this class was generated from the following file:
framework/geo/include/muscovite/geo/geography.hpp