Muscovite C++ Framework: muscovite::validation::ValidationErrors Class Reference
muscovite::validation::ValidationErrors Class Reference
Accumulating collection of field-level validation errors.
#include <validation_errors.hpp>
Public Member Functions
void add (std::string field, std::string message, ValidationTier tier, std::string code={})
Add a validation error for a specific field.
void clear () noexcept
Clear all accumulated errors.
auto errors () const noexcept -> const std::vector< ValidationError > &
Direct access to the error list.
auto errors_for_field (std::string_view field_name) const -> ValidationErrors
Filter errors by field name.
auto errors_for_tier (ValidationTier tier) const -> ValidationErrors
Filter errors by tier.
auto has_errors () const noexcept -> bool
Returns true if any validation errors have been recorded.
void merge (ValidationErrors other)
Merge errors from another ValidationErrors instance.
auto size () const noexcept -> std::size_t
Returns the number of accumulated errors.
auto to_json () const -> std::string
Serialize to JSON string for gRPC error details.
Detailed Description
Accumulating collection of field-level validation errors.
Designed for the three-tier validation pipeline where errors from strong types (Tier 1), entity validators (Tier 2), and plugin validators (Tier 3) are collected without short-circuiting, then returned as a single structured response.
Definition at line 58 of file validation_errors.hpp.
Member Function Documentation
add()
void muscovite::validation::ValidationErrors::add (std::string field, std::string message, ValidationTier tier, std::string code = {}) inline
Add a validation error for a specific field.
Parameters
field Name of the field that failed validation
message Human-readable description of the failure
tier Which validation tier produced this error
code Optional machine-readable error code (default: empty)
Definition at line 65 of file validation_errors.hpp.
Referenced by errors_for_field(), and errors_for_tier().
clear()
void muscovite::validation::ValidationErrors::clear () inline noexcept
Clear all accumulated errors.
Definition at line 160 of file validation_errors.hpp.
errors()
auto muscovite::validation::ValidationErrors::errors () const -> const std::vector< ValidationError > & inline nodiscard noexcept
Direct access to the error list.
Definition at line 94 of file validation_errors.hpp.
errors_for_field()
auto muscovite::validation::ValidationErrors::errors_for_field (std::string_view field_name) const -> ValidationErrors inline nodiscard
Filter errors by field name.
Parameters
field_name The field to filter on
Returns
New ValidationErrors containing only errors for the given field
Definition at line 114 of file validation_errors.hpp.
References add().
errors_for_tier()
auto muscovite::validation::ValidationErrors::errors_for_tier (ValidationTier tier) const -> ValidationErrors inline nodiscard
Filter errors by tier.
Parameters
tier The tier to filter on
Returns
New ValidationErrors containing only errors from the given tier
Definition at line 101 of file validation_errors.hpp.
References add().
has_errors()
auto muscovite::validation::ValidationErrors::has_errors () const -> bool inline nodiscard noexcept
Returns true if any validation errors have been recorded.
Definition at line 84 of file validation_errors.hpp.
merge()
void muscovite::validation::ValidationErrors::merge (ValidationErrors other) inline
Merge errors from another ValidationErrors instance.
Parameters
other Errors to absorb (moved from)
Definition at line 77 of file validation_errors.hpp.
size()
auto muscovite::validation::ValidationErrors::size () const -> std::size_t inline nodiscard noexcept
Returns the number of accumulated errors.
Definition at line 89 of file validation_errors.hpp.
to_json()
auto muscovite::validation::ValidationErrors::to_json () const -> std::string inline nodiscard
Serialize to JSON string for gRPC error details.
Format:
{
  "errors": [
    {"field": "age", "message": "must be positive", "tier": "strong_type", "code": "RANGE"},
    ...
  ]
}
Definition at line 135 of file validation_errors.hpp.
The documentation for this class was generated from the following file:
framework/validation/include/muscovite/validation/validation_errors.hpp