Muscovite C++ Framework: muscovite::grpc::ServiceBase< Derived > Class Template Reference
muscovite::grpc::ServiceBase< Derived > Class Template Reference
#include <service_base.hpp>
Public Member Functions
ServiceBase (dba::ConnectionPool &pool)
Construct with connection pool reference.
Protected Member Functions
template<typename F>
auto execute_read (F &&fn) -> ::grpc::Status
template<typename R, typename F>
auto execute_read (F &&fn, R &out) -> ::grpc::Status
template<typename F>
auto execute_write (F &&fn) -> ::grpc::Status
template<typename R, typename F>
auto execute_write (F &&fn, R &out) -> ::grpc::Status
Execute a write operation returning a value.
auto pool () -> dba::ConnectionPool &
Get the connection pool.
Detailed Description
template<typename Derived>
class muscovite::grpc::ServiceBase< Derived >
CRTP base class for generated gRPC service implementations
Usage:
class MyServiceImpl : public ServiceBase<MyServiceImpl>,
                      public myproto::MyService::Service {
public:
    using ServiceBase::ServiceBase;  // Inherit constructor
    ::grpc::Status GetById(
        ::grpc::ServerContext* context,
        const myproto::IdRequest* request,
        myproto::Entity* response) override {
        return execute_read([&](pqxx::transaction<>& tx) {
            // Database logic here
        });
    }
};
Definition at line 51 of file service_base.hpp.
Constructor & Destructor Documentation
ServiceBase()
template<typename Derived> muscovite::grpc::ServiceBase< Derived >::ServiceBase (dba::ConnectionPool & pool) inline explicit
Construct with connection pool reference.
Definition at line 54 of file service_base.hpp.
References pool().
Member Function Documentation
execute_read() [1/2]
template<typename Derived> template<typename F> auto muscovite::grpc::ServiceBase< Derived >::execute_read (F && fn) -> ::grpc::Status inline nodiscard protected
Execute a read-only operation with automatic transaction management
Template Parameters
F Callable taking pqxx::transaction<>& and returning void
Parameters
fn Database operation
Returns
grpc::Status (OK on success, mapped error on failure)
Definition at line 64 of file service_base.hpp.
References muscovite::grpc::map_db_error().
execute_read() [2/2]
template<typename Derived> template<typename R, typename F> auto muscovite::grpc::ServiceBase< Derived >::execute_read (F && fn, R & out) -> ::grpc::Status inline nodiscard protected
Execute a read-only operation returning a value
Template Parameters
R Return type
F Callable taking pqxx::transaction<>& and returning R
Parameters
fn Database operation
out Output value (set on success)
Returns
grpc::Status (OK on success, mapped error on failure)
Definition at line 79 of file service_base.hpp.
References muscovite::grpc::map_db_error().
execute_write() [1/2]
template<typename Derived> template<typename F> auto muscovite::grpc::ServiceBase< Derived >::execute_write (F && fn) -> ::grpc::Status inline nodiscard protected
Execute a write operation with automatic transaction management
Template Parameters
F Callable taking pqxx::transaction<>& and returning void
Parameters
fn Database operation
Returns
grpc::Status (OK on success, mapped error on failure)
Definition at line 93 of file service_base.hpp.
References muscovite::grpc::map_db_error().
execute_write() [2/2]
template<typename Derived> template<typename R, typename F> auto muscovite::grpc::ServiceBase< Derived >::execute_write (F && fn, R & out) -> ::grpc::Status inline nodiscard protected
Execute a write operation returning a value.
Definition at line 103 of file service_base.hpp.
References muscovite::grpc::map_db_error().
pool()
template<typename Derived> auto muscovite::grpc::ServiceBase< Derived >::pool () -> dba::ConnectionPool & inline nodiscard protected
Get the connection pool.
Definition at line 113 of file service_base.hpp.
Referenced by ServiceBase().
The documentation for this class was generated from the following file:
framework/grpc/include/muscovite/grpc/service_base.hpp