Muscovite C++ Framework: muscovite::dba::UnitOfWork Class Reference
muscovite::dba::UnitOfWork Class Reference
#include <unit_of_work.hpp>
Public Member Functions
UnitOfWork (ConnectionPool &pool, std::string_view schema)
UnitOfWork (const UnitOfWork &)=delete
UnitOfWork (pqxx::connection &connection, std::string_view schema="public")
UnitOfWork (UnitOfWork &&) noexcept
~UnitOfWork ()
Destructor - rolls back if not committed.
void add_event (DomainEvent event)
Add a domain event to be persisted on commit.
auto commit () -> std::expected< void, Error< DbError > >
void commit_or_throw ()
auto is_completed () const noexcept -> bool
Check if the unit of work has been committed or rolled back.
UnitOfWork & operator= (const UnitOfWork &)=delete
UnitOfWork & operator= (UnitOfWork &&) noexcept
auto pending_effect_count () const noexcept -> std::size_t
Get the number of pending effect intents (FTR-294).
auto pending_effects () const noexcept -> const std::vector< EffectIntent > &
Get read-only access to pending effect intents (FTR-294).
auto pending_event_count () const noexcept -> std::size_t
Get the number of pending events.
auto pending_events () const noexcept -> const std::vector< DomainEvent > &
Get read-only access to pending events.
void plan_effect (EffectIntent effect)
void rollback () noexcept
Rollback the transaction and discard all pending events.
auto transaction () -> pqxx::work &
Get the active transaction for repository operations.
Detailed Description
Unit of Work pattern implementation.
Provides a single transaction context for business operations with automatic domain event collection and persistence.
Key Features:
Single transaction for all repository operations
Collects domain events during the operation
Persists all events atomically on commit()
Events are discarded on rollback()
Usage:
void PatientService::create(const CreatePatientRequest& req) {
    UnitOfWork uow(pool_, "basedata");  // schema for domain_events table
    auto& txn = uow.transaction();
    auto patient = patient_repo_.insert(txn, req);  // Repo stays pure CRUD
    uow.add_event(DomainEvent::create(
        "PatientCreated",
        patient.id(),
        "Patient",
        nlohmann::json{{"mrn", patient.mrn()}}
    ));
    uow.commit();  // Events persisted atomically
}
Design Notes:
Repositories remain pure CRUD (no event logic)
Services decide WHAT events to emit
Infrastructure handles HOW events are persisted
Same physical transaction for data + events (atomicity)
Definition at line 142 of file unit_of_work.hpp.
Constructor & Destructor Documentation
UnitOfWork() [1/3]
muscovite::dba::UnitOfWork::UnitOfWork (pqxx::connection & connection, std::string_view schema = "public") explicit
Construct Unit of Work from an already-acquired connection
Parameters
connection Active database connection (caller retains ownership)
schema PostgreSQL schema containing domain_events table (default: "public")
Definition at line 33 of file unit_of_work.cpp.
UnitOfWork() [2/3]
muscovite::dba::UnitOfWork::UnitOfWork (ConnectionPool & pool, std::string_view schema)
Construct Unit of Work with schema for domain_events table
Parameters
pool Connection pool
schema PostgreSQL schema containing domain_events table
Definition at line 41 of file unit_of_work.cpp.
~UnitOfWork()
muscovite::dba::UnitOfWork::~UnitOfWork ()
Destructor - rolls back if not committed.
Definition at line 49 of file unit_of_work.cpp.
UnitOfWork() [3/3]
muscovite::dba::UnitOfWork::UnitOfWork (UnitOfWork && other) noexcept
Definition at line 60 of file unit_of_work.cpp.
Member Function Documentation
add_event()
void muscovite::dba::UnitOfWork::add_event (DomainEvent event)
Add a domain event to be persisted on commit.
Definition at line 99 of file unit_of_work.cpp.
References muscovite::dba::DomainEvent::aggregate_id, muscovite::dba::DomainEvent::aggregate_type, and muscovite::dba::DomainEvent::event_type.
commit()
auto muscovite::dba::UnitOfWork::commit () -> std::expected< void, Error< DbError > > nodiscard
Persist all pending events and commit the transaction
Returns
Error if commit fails
Definition at line 188 of file unit_of_work.cpp.
Referenced by commit_or_throw().
commit_or_throw()
void muscovite::dba::UnitOfWork::commit_or_throw ()
Persist all pending events and commit the transaction (throwing version)
Exceptions
std::runtime_error if commit fails
Definition at line 274 of file unit_of_work.cpp.
References commit().
Referenced by muscovite::dba::execute_uow().
is_completed()
auto muscovite::dba::UnitOfWork::is_completed () const -> bool nodiscard noexcept
Check if the unit of work has been committed or rolled back.
Definition at line 281 of file unit_of_work.cpp.
operator=()
UnitOfWork & muscovite::dba::UnitOfWork::operator= (UnitOfWork && other) noexcept
Definition at line 71 of file unit_of_work.cpp.
pending_effect_count()
auto muscovite::dba::UnitOfWork::pending_effect_count () const -> std::size_t nodiscard noexcept
Get the number of pending effect intents (FTR-294).
Definition at line 128 of file unit_of_work.cpp.
pending_effects()
auto muscovite::dba::UnitOfWork::pending_effects () const -> const std::vector< EffectIntent > & nodiscard noexcept
Get read-only access to pending effect intents (FTR-294).
Definition at line 132 of file unit_of_work.cpp.
pending_event_count()
auto muscovite::dba::UnitOfWork::pending_event_count () const -> std::size_t nodiscard noexcept
Get the number of pending events.
Definition at line 110 of file unit_of_work.cpp.
pending_events()
auto muscovite::dba::UnitOfWork::pending_events () const -> const std::vector< DomainEvent > & nodiscard noexcept
Get read-only access to pending events.
Definition at line 114 of file unit_of_work.cpp.
plan_effect()
void muscovite::dba::UnitOfWork::plan_effect (EffectIntent effect)
Add an effect intent to be persisted to the outbox on commit (FTR-294)
See also
ADR: 20260307-emit-plan-intent-separation.md
Definition at line 118 of file unit_of_work.cpp.
References muscovite::dba::EffectIntent::aggregate_id, and muscovite::dba::EffectIntent::effect_type.
rollback()
void muscovite::dba::UnitOfWork::rollback () noexcept
Rollback the transaction and discard all pending events.
Definition at line 258 of file unit_of_work.cpp.
transaction()
auto muscovite::dba::UnitOfWork::transaction () -> pqxx::work & nodiscard
Get the active transaction for repository operations.
Definition at line 92 of file unit_of_work.cpp.
The documentation for this class was generated from the following files:
framework/dba/include/muscovite/dba/unit_of_work.hpp
framework/dba/src/unit_of_work.cpp