Muscovite C++ Framework: muscovite::dba::NatsMessageBroker Class Reference
muscovite::dba::NatsMessageBroker Class Reference
#include <nats_message_broker.hpp>
Classes
struct ConnectionStats
Get statistics about the connection.
Public Member Functions
NatsMessageBroker (const NatsMessageBroker &)=delete
NatsMessageBroker (NatsConfig config)
NatsMessageBroker (NatsMessageBroker &&other) noexcept
auto connect () -> bool override
void disconnect () override
Disconnect from the NATS server.
auto ensure_infrastructure (const std::string &stream_name, const std::string &subject_prefix) -> bool override
auto ensure_stream (const std::string &stream_name, const std::vector< std::string > &subjects) -> bool
auto is_connected () const -> bool override
Check if connected to NATS.
auto last_error () const -> std::string
Get the last error message (if any).
NatsMessageBroker & operator= (const NatsMessageBroker &)=delete
NatsMessageBroker & operator= (NatsMessageBroker &&other) noexcept
auto publish (const std::string &subject, const std::string &payload, const std::string &event_id) -> PublishResult override
auto publish_jetstream (const std::string &subject, const std::string &payload, const JetStreamPublishOptions &options) -> std::optional< JetStreamPublishAck >
auto stats () const -> ConnectionStats
Detailed Description
NATS JetStream message broker implementation
Connects to NATS and publishes messages using JetStream for durability. Automatically reconnects on connection loss.
Thread Safety: This class is thread-safe. Multiple threads can call publish() concurrently. The underlying cnats library handles connection management.
Usage:
NatsConfig config;
config.url = "nats://localhost:4222";
NatsMessageBroker broker(config);
if (broker.connect()) {
    auto result = broker.publish("muscovite.patient.PatientCreated", payload, event_id);
    if (result == PublishResult::Success) {
        // Event published to JetStream
    }
}
Definition at line 113 of file nats_message_broker.hpp.
Constructor & Destructor Documentation
NatsMessageBroker() [1/2]
muscovite::dba::NatsMessageBroker::NatsMessageBroker (NatsConfig config) explicit
Create a NATS message broker
Parameters
config Connection configuration
Definition at line 25 of file nats_message_broker.cpp.
~NatsMessageBroker()
muscovite::dba::NatsMessageBroker::~NatsMessageBroker () override
Definition at line 31 of file nats_message_broker.cpp.
NatsMessageBroker() [2/2]
muscovite::dba::NatsMessageBroker::NatsMessageBroker (NatsMessageBroker && other) noexcept
Definition at line 35 of file nats_message_broker.cpp.
Member Function Documentation
connect()
auto muscovite::dba::NatsMessageBroker::connect () -> bool nodiscard override virtual
Connect to the NATS server
Returns
true if connection established, false on error
Implements muscovite::dba::MessageBroker.
Definition at line 66 of file nats_message_broker.cpp.
References make_js_context(), and make_nats_connection().
disconnect()
void muscovite::dba::NatsMessageBroker::disconnect () override virtual
Disconnect from the NATS server.
Implements muscovite::dba::MessageBroker.
Definition at line 120 of file nats_message_broker.cpp.
ensure_infrastructure()
auto muscovite::dba::NatsMessageBroker::ensure_infrastructure (const std::string & stream_name, const std::string & subject_prefix) -> bool nodiscard override virtual
Ensure JetStream stream exists for the schema
Creates a JetStream stream if it doesn't exist. Called by OutboxPublisher on startup.
Parameters
stream_name Stream name (typically schema name, e.g., "basedata")
subject_prefix Subject prefix for events (e.g., "muscovite.basedata")
Returns
true if stream exists or was created, false on error
Reimplemented from muscovite::dba::MessageBroker.
Definition at line 321 of file nats_message_broker.cpp.
References ensure_stream().
ensure_stream()
auto muscovite::dba::NatsMessageBroker::ensure_stream (const std::string & stream_name, const std::vector< std::string > & subjects) -> bool nodiscard
Ensure a JetStream stream exists for the given subject pattern
Creates the stream if it doesn't exist. Uses sensible defaults:
WorkQueue retention policy (events deleted after ack)
File storage for durability
7 day max age
Parameters
stream_name Name of the stream to create
subjects Subject patterns to capture (e.g., "muscovite.patient.>")
Returns
true if stream exists or was created, false on error
Definition at line 236 of file nats_message_broker.cpp.
Referenced by ensure_infrastructure().
is_connected()
auto muscovite::dba::NatsMessageBroker::is_connected () const -> bool nodiscard override virtual
Check if connected to NATS.
Implements muscovite::dba::MessageBroker.
Definition at line 124 of file nats_message_broker.cpp.
Referenced by publish().
last_error()
auto muscovite::dba::NatsMessageBroker::last_error () const -> std::string nodiscard
Get the last error message (if any).
Definition at line 232 of file nats_message_broker.cpp.
operator=()
NatsMessageBroker & muscovite::dba::NatsMessageBroker::operator= (NatsMessageBroker && other) noexcept
Definition at line 48 of file nats_message_broker.cpp.
publish()
auto muscovite::dba::NatsMessageBroker::publish (const std::string & subject, const std::string & payload, const std::string & event_id) -> PublishResult nodiscard override virtual
Publish an event to NATS JetStream
Parameters
subject Message subject (e.g., "muscovite.patient.PatientCreated")
payload JSON string payload (ADR 20260202: JSON-in-DB, Protobuf-on-wire)
event_id Event ID for deduplication
Returns
Result indicating success or error type
Implements muscovite::dba::MessageBroker.
Definition at line 134 of file nats_message_broker.cpp.
References is_connected(), muscovite::dba::JetStreamPublishOptions::msg_id, and publish_jetstream().
publish_jetstream()
auto muscovite::dba::NatsMessageBroker::publish_jetstream (const std::string & subject, const std::string & payload, const JetStreamPublishOptions & options) -> std::optional< JetStreamPublishAck > nodiscard
Publish with explicit JetStream options
Parameters
subject Message subject
payload JSON string payload
options JetStream-specific publish options
Returns
Publish acknowledgment on success, nullopt on error
Definition at line 164 of file nats_message_broker.cpp.
References muscovite::dba::JetStreamPublishAck::duplicate, muscovite::dba::JetStreamPublishAck::sequence, and muscovite::dba::JetStreamPublishAck::stream.
Referenced by publish().
stats()
auto muscovite::dba::NatsMessageBroker::stats () const -> ConnectionStats nodiscard
Definition at line 333 of file nats_message_broker.cpp.
The documentation for this class was generated from the following files:
framework/dba/include/muscovite/dba/nats_message_broker.hpp
framework/dba/src/nats_message_broker.cpp