Muscovite C++ Framework: muscovite::server::security::AuthenticationService Class Reference
muscovite::server::security::AuthenticationService Class Reference
Authentication service for login, logout, and token management.
#include <authentication_service.hpp>
Classes
struct Config
Configuration for authentication service.
Public Member Functions
AuthenticationService (AuthenticationService &&) noexcept
AuthenticationService (const AuthenticationService &)=delete
AuthenticationService (std::shared_ptr< muscovite::dba::ConnectionPool > pool, std::shared_ptr< JwtService > jwt_service, std::shared_ptr< PasswordService > password_service, const Config &config)
Construct authentication service.
void blacklist_token (const std::string &jti, const std::string &principal_id, std::chrono::system_clock::time_point expires_at, const std::string &reason)
Blacklist a JWT token (for immediate revocation).
bool change_password (const std::string &principal_id, const std::string &current_password, const std::string &new_password)
Change a user's password.
bool is_token_blacklisted (const std::string &jti)
Check if a JWT is blacklisted.
AuthResult login (const std::string &username, const std::string &password, const std::string &client_info="", const std::string &ip_address="", const std::string &user_agent="")
Authenticate a user with username and password.
bool logout (const std::string &session_id, const std::string &reason="logout")
Logout a session.
int logout_all (const std::string &principal_id, const std::string &reason="logout_all")
Logout all sessions for a user.
AuthenticationService & operator= (AuthenticationService &&) noexcept
AuthenticationService & operator= (const AuthenticationService &)=delete
AuthResult refresh (const std::string &refresh_token, const std::string &ip_address="", const std::string &user_agent="")
Refresh an access token using a refresh token.
std::optional< Principal > validate_token (const std::string &access_token)
Validate an access token and return the principal.
Detailed Description
Authentication service for login, logout, and token management.
This service handles:
User authentication (login/logout)
Token generation and validation
Session management
Account lockout after failed attempts
Refresh token rotation
Definition at line 89 of file authentication_service.hpp.
Constructor & Destructor Documentation
AuthenticationService()
muscovite::server::security::AuthenticationService::AuthenticationService (std::shared_ptr< muscovite::dba::ConnectionPool > pool, std::shared_ptr< JwtService > jwt_service, std::shared_ptr< PasswordService > password_service, const Config & config)
Construct authentication service.
Parameters
pool Database connection pool.
jwt_service JWT service for token operations.
password_service Password service for verification.
config Service configuration.
Definition at line 338 of file authentication_service.cpp.
Referenced by login().
Member Function Documentation
blacklist_token()
void muscovite::server::security::AuthenticationService::blacklist_token (const std::string & jti, const std::string & principal_id, std::chrono::system_clock::time_point expires_at, const std::string & reason)
Blacklist a JWT token (for immediate revocation).
Parameters
jti The JWT ID claim.
principal_id The user ID.
expires_at When the token would have expired.
reason Reason for blacklisting.
Definition at line 666 of file authentication_service.cpp.
References blacklist_token().
Referenced by blacklist_token().
change_password()
bool muscovite::server::security::AuthenticationService::change_password (const std::string & principal_id, const std::string & current_password, const std::string & new_password) nodiscard
Change a user's password.
Parameters
principal_id The user ID.
current_password The current password (for verification).
new_password The new password.
Returns
true if password was changed successfully.
Definition at line 610 of file authentication_service.cpp.
References change_password().
Referenced by change_password().
is_token_blacklisted()
bool muscovite::server::security::AuthenticationService::is_token_blacklisted (const std::string & jti) nodiscard
Check if a JWT is blacklisted.
Parameters
jti The JWT ID claim.
Returns
true if the token is blacklisted.
Definition at line 700 of file authentication_service.cpp.
References is_token_blacklisted().
Referenced by is_token_blacklisted(), and validate_token().
login()
AuthResult muscovite::server::security::AuthenticationService::login (const std::string & username, const std::string & password, const std::string & client_info = "", const std::string & ip_address = "", const std::string & user_agent = "") nodiscard
Authenticate a user with username and password.
Parameters
username The username.
password The plaintext password.
client_info Optional client information (app version, etc.)
ip_address Optional client IP address.
user_agent Optional user agent string.
Returns
Authentication result with tokens if successful.
Definition at line 350 of file authentication_service.cpp.
References AuthenticationService(), and login().
Referenced by login().
logout()
bool muscovite::server::security::AuthenticationService::logout (const std::string & session_id, const std::string & reason = "logout")
Logout a session.
Parameters
session_id The session ID to revoke.
reason Optional reason for audit.
Returns
true if session was revoked.
Definition at line 457 of file authentication_service.cpp.
References logout().
Referenced by logout().
logout_all()
int muscovite::server::security::AuthenticationService::logout_all (const std::string & principal_id, const std::string & reason = "logout_all")
Logout all sessions for a user.
Parameters
principal_id The user ID.
reason Optional reason for audit.
Returns
Number of sessions revoked.
Definition at line 493 of file authentication_service.cpp.
References logout_all().
Referenced by logout_all().
refresh()
AuthResult muscovite::server::security::AuthenticationService::refresh (const std::string & refresh_token, const std::string & ip_address = "", const std::string & user_agent = "") nodiscard
Refresh an access token using a refresh token.
Parameters
refresh_token The refresh token.
ip_address Optional current IP address.
user_agent Optional current user agent.
Returns
New tokens if successful.
Definition at line 513 of file authentication_service.cpp.
References muscovite::server::security::Principal::display_name, muscovite::server::security::Principal::id, refresh(), and muscovite::server::security::Principal::username.
Referenced by refresh().
validate_token()
std::optional< Principal > muscovite::server::security::AuthenticationService::validate_token (const std::string & access_token) nodiscard
Validate an access token and return the principal.
Parameters
access_token The JWT access token.
Returns
The principal if token is valid, nullopt otherwise.
Definition at line 590 of file authentication_service.cpp.
References muscovite::server::security::Principal::display_name, muscovite::server::security::Principal::groups, muscovite::server::security::Principal::id, is_token_blacklisted(), muscovite::server::security::Principal::privileges, muscovite::server::security::Principal::username, and validate_token().
Referenced by validate_token().
The documentation for this class was generated from the following files:
framework/server/include/muscovite/server/security/authentication_service.hpp
framework/server/src/security/authentication_service.cpp