Muscovite C++ Framework: muscovite::types::ConstrainedDate< Policy > Class Template Reference
muscovite::types::ConstrainedDate< Policy > Class Template Reference
Public Types
using clock_type = std::chrono::system_clock
using value_type = std::chrono::year_month_day
Public Member Functions
constexpr auto day () const noexcept -> std::chrono::day
Get the day.
constexpr auto month () const noexcept -> std::chrono::month
Get the month.
constexpr auto operator<=> (const ConstrainedDate &) const noexcept=default
Three-way comparison.
constexpr auto operator== (const ConstrainedDate &) const noexcept -> bool=default
Equality.
constexpr auto value () const noexcept -> const value_type &
Get the underlying date value.
constexpr auto year () const noexcept -> std::chrono::year
Get the year.
Static Public Member Functions
static constexpr auto from_trusted (const value_type &date) noexcept -> ConstrainedDate
Construct from trusted source without validation (DB loads).
static auto is_valid (const value_type &date) -> bool
Validate a date against the policy.
static auto try_from (const value_type &date) -> std::expected< ConstrainedDate, std::string >
Try to construct from a date value.
Detailed Description
template<typename Policy = Unconstrained>
class muscovite::types::ConstrainedDate< Policy >
Definition at line 41 of file constrained_date.hpp.
Member Typedef Documentation
clock_type
template<typename Policy = Unconstrained> using muscovite::types::ConstrainedDate< Policy >::clock_type = std::chrono::system_clock
Definition at line 44 of file constrained_date.hpp.
value_type
template<typename Policy = Unconstrained> using muscovite::types::ConstrainedDate< Policy >::value_type = std::chrono::year_month_day
Definition at line 43 of file constrained_date.hpp.
Member Function Documentation
day()
template<typename Policy = Unconstrained> auto muscovite::types::ConstrainedDate< Policy >::day () const -> std::chrono::day inline nodiscard constexpr noexcept
Get the day.
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/constrained_date.hpp.
Definition at line 86 of file constrained_date.hpp.
References day().
Referenced by day().
from_trusted()
template<typename Policy = Unconstrained> constexpr auto muscovite::types::ConstrainedDate< Policy >::from_trusted (const value_type & date) -> ConstrainedDate inline static nodiscard constexpr noexcept
Construct from trusted source without validation (DB loads).
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/constrained_date.hpp.
Definition at line 65 of file constrained_date.hpp.
is_valid()
template<typename Policy = Unconstrained> auto muscovite::types::ConstrainedDate< Policy >::is_valid (const value_type & date) -> bool inline static nodiscard
Validate a date against the policy.
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/constrained_date.hpp.
Definition at line 47 of file constrained_date.hpp.
month()
template<typename Policy = Unconstrained> auto muscovite::types::ConstrainedDate< Policy >::month () const -> std::chrono::month inline nodiscard constexpr noexcept
Get the month.
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/constrained_date.hpp.
Definition at line 81 of file constrained_date.hpp.
References month().
Referenced by month().
try_from()
template<typename Policy = Unconstrained> auto muscovite::types::ConstrainedDate< Policy >::try_from (const value_type & date) -> std::expected< ConstrainedDate, std::string > inline static nodiscard
Try to construct from a date value.
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/constrained_date.hpp.
Definition at line 53 of file constrained_date.hpp.
value()
template<typename Policy = Unconstrained> auto muscovite::types::ConstrainedDate< Policy >::value () const -> const value_type & inline nodiscard constexpr noexcept
Get the underlying date value.
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/constrained_date.hpp.
Definition at line 71 of file constrained_date.hpp.
year()
template<typename Policy = Unconstrained> auto muscovite::types::ConstrainedDate< Policy >::year () const -> std::chrono::year inline nodiscard constexpr noexcept
Get the year.
Examples
/home/jolo/muscovite/framework/types/include/muscovite/types/constrained_date.hpp.
Definition at line 76 of file constrained_date.hpp.
References year().
Referenced by year().
The documentation for this class was generated from the following file:
framework/types/include/muscovite/types/constrained_date.hpp