Muscovite C++ Framework: muscovite::grpc::oauth2::JWT Class Reference
muscovite::grpc::oauth2::JWT Class Reference
#include <jwt.hpp>
Static Public Member Functions
static nlohmann::json extractClaims (const std::string &token)
Parse JWT and extract claims (without signature verification).
static std::string extractSubject (const nlohmann::json &claims)
Extract username/subject from ID token.
static nlohmann::json getClaim (const nlohmann::json &claims, const std::string &claim_name)
Extract custom claim.
static bool isExpired (const nlohmann::json &claims, int clock_skew_seconds=60)
Check if token is expired (includes clock skew margin).
static bool validateStandardClaims (const nlohmann::json &claims, const std::string &expected_issuer, const std::string &expected_audience)
Validate standard OIDC claims (iss, sub, aud, exp, iat, etc.).
Detailed Description
JWT (JSON Web Token) utilities for OAuth2.
Provides JWT parsing and validation for OpenID Connect (OIDC) tokens and custom claims validation.
Note: This is for parsing/validation only. Token signature verification should be done by the authorization server via introspection endpoint or by maintaining a cached JWKS (JSON Web Key Set).
Definition at line 28 of file jwt.hpp.
Member Function Documentation
extractClaims()
json muscovite::grpc::oauth2::JWT::extractClaims (const std::string & token) static
Parse JWT and extract claims (without signature verification).
Definition at line 74 of file jwt.cpp.
Referenced by muscovite::grpc::oauth2::OAuth2Interceptor::completeOAuth2Flow().
extractSubject()
std::string muscovite::grpc::oauth2::JWT::extractSubject (const nlohmann::json & claims) static
Extract username/subject from ID token.
Definition at line 164 of file jwt.cpp.
Referenced by muscovite::grpc::oauth2::OAuth2Interceptor::completeOAuth2Flow().
getClaim()
json muscovite::grpc::oauth2::JWT::getClaim (const nlohmann::json & claims, const std::string & claim_name) static
Extract custom claim.
Definition at line 154 of file jwt.cpp.
isExpired()
bool muscovite::grpc::oauth2::JWT::isExpired (const nlohmann::json & claims, int clock_skew_seconds = 60) static
Check if token is expired (includes clock skew margin).
Definition at line 144 of file jwt.cpp.
Referenced by validateStandardClaims().
validateStandardClaims()
bool muscovite::grpc::oauth2::JWT::validateStandardClaims (const nlohmann::json & claims, const std::string & expected_issuer, const std::string & expected_audience) static
Validate standard OIDC claims (iss, sub, aud, exp, iat, etc.).
Definition at line 95 of file jwt.cpp.
References isExpired().
The documentation for this class was generated from the following files:
framework/grpc/include/muscovite/grpc/oauth2/jwt.hpp
framework/grpc/src/oauth2/jwt.cpp