Muscovite C++ Framework: muscovite::dba::NatsEventConsumer Class Reference
muscovite::dba::NatsEventConsumer Class Reference
#include <nats_event_consumer.hpp>
Public Member Functions
NatsEventConsumer (const NatsEventConsumer &)=delete
NatsEventConsumer (NatsEventConsumer &&)=delete
NatsEventConsumer (std::string nats_url, std::string stream_name, EventConsumerConfig config)
auto events_failed () const -> std::uint64_t override
Get events failed count.
auto events_processed () const -> std::uint64_t override
Get events processed count.
auto is_running () const -> bool override
Check if running.
auto last_error () const -> std::string override
Get last error.
void on (const std::string &event_type, EventHandler handler) override
Register a handler for a specific event type.
void on_any (EventHandler handler) override
Register a catch-all handler.
void on_error (ErrorHandler handler) override
Register an error handler.
auto operator= (const NatsEventConsumer &) -> NatsEventConsumer &=delete
auto operator= (NatsEventConsumer &&) -> NatsEventConsumer &=delete
auto start () -> bool override
Start consuming events.
void stop () override
Stop consuming events.
Detailed Description
NATS JetStream implementation of EventConsumer
Uses durable push subscriptions for reliable event delivery. Multiple consumers with the same name form a consumer group.
Definition at line 37 of file nats_event_consumer.hpp.
Constructor & Destructor Documentation
NatsEventConsumer()
muscovite::dba::NatsEventConsumer::NatsEventConsumer (std::string nats_url, std::string stream_name, EventConsumerConfig config)
Construct a consumer with the given configuration
Parameters
nats_url NATS server URL (e.g., "nats://localhost:4222")
stream_name JetStream stream name (e.g., "patient")
config Consumer configuration
Definition at line 51 of file nats_event_consumer.cpp.
~NatsEventConsumer()
muscovite::dba::NatsEventConsumer::~NatsEventConsumer () override
Definition at line 67 of file nats_event_consumer.cpp.
Member Function Documentation
events_failed()
auto muscovite::dba::NatsEventConsumer::events_failed () const -> std::uint64_t nodiscard override virtual
Get events failed count.
Implements muscovite::dba::EventConsumer.
Definition at line 278 of file nats_event_consumer.cpp.
events_processed()
auto muscovite::dba::NatsEventConsumer::events_processed () const -> std::uint64_t nodiscard override virtual
Get events processed count.
Implements muscovite::dba::EventConsumer.
Definition at line 274 of file nats_event_consumer.cpp.
is_running()
auto muscovite::dba::NatsEventConsumer::is_running () const -> bool nodiscard override virtual
Check if running.
Implements muscovite::dba::EventConsumer.
Definition at line 270 of file nats_event_consumer.cpp.
last_error()
auto muscovite::dba::NatsEventConsumer::last_error () const -> std::string nodiscard override virtual
Get last error.
Implements muscovite::dba::EventConsumer.
Definition at line 282 of file nats_event_consumer.cpp.
on()
void muscovite::dba::NatsEventConsumer::on (const std::string & event_type, EventHandler handler) override virtual
Register a handler for a specific event type.
Implements muscovite::dba::EventConsumer.
Definition at line 71 of file nats_event_consumer.cpp.
on_any()
void muscovite::dba::NatsEventConsumer::on_any (EventHandler handler) override virtual
Register a catch-all handler.
Implements muscovite::dba::EventConsumer.
Definition at line 77 of file nats_event_consumer.cpp.
on_error()
void muscovite::dba::NatsEventConsumer::on_error (ErrorHandler handler) override virtual
Register an error handler.
Implements muscovite::dba::EventConsumer.
Definition at line 83 of file nats_event_consumer.cpp.
start()
auto muscovite::dba::NatsEventConsumer::start () -> bool nodiscard override virtual
Start consuming events.
Implements muscovite::dba::EventConsumer.
Definition at line 89 of file nats_event_consumer.cpp.
References make_js_context(), make_js_subscription(), make_nats_connection(), and make_nats_options().
stop()
void muscovite::dba::NatsEventConsumer::stop () override virtual
Stop consuming events.
Implements muscovite::dba::EventConsumer.
Definition at line 205 of file nats_event_consumer.cpp.
The documentation for this class was generated from the following files:
framework/dba/include/muscovite/dba/nats_event_consumer.hpp
framework/dba/src/nats_event_consumer.cpp