Muscovite C++ Framework: muscovite::qt::models::EntityListModel Class Reference
muscovite::qt::models::EntityListModel Class Reference
Generic QAbstractListModel for QML ListViews.
#include <entity_list_model.hpp>
Signals
void countChanged ()
Emitted when the number of items changes.
Public Member Functions
EntityListModel (QObject *parent=nullptr)
Q_INVOKABLE void appendItem (const QVariantMap &item)
Append a single item. Emits proper insert notifications for animations.
Q_INVOKABLE void clear ()
Remove all items.
int count () const
Number of items (alias for rowCount, QML-friendly).
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
Returns data for the given index and role. Roles are mapped to QVariantMap keys derived from the first item.
Q_INVOKABLE QString idAt (int row) const
Convenience: get the "id" field at the given row, or empty string.
Q_INVOKABLE QVariantMap itemAt (int row) const
Get the full QVariantMap at the given row, or empty map if invalid.
Q_INVOKABLE void removeItem (int row)
Remove the item at the given row. Emits proper remove notifications.
Q_INVOKABLE void replaceItems (const QVariantList &items)
Replace all items. Derives roles from first item's keys. Uses beginResetModel/endResetModel.
QHash< int, QByteArray > roleNames () const override
Returns the role-name mapping derived from item keys.
int rowCount (const QModelIndex &parent=QModelIndex()) const override
Returns the number of rows (items) in the model.
Properties
int count
Number of items in the model (for QML binding).
Detailed Description
Generic QAbstractListModel for QML ListViews.
Stores items as QVariantMap and auto-derives role names from the keys of the first inserted item. Generated ViewModels own an instance and call replaceItems() after gRPC list fetches; QML delegates bind via model.roleName syntax.
Incremental updates
appendItem() → beginInsertRows/endInsertRows → ListView add-animation
removeItem() → beginRemoveRows/endRemoveRows → ListView remove-animation
replaceItems() → beginResetModel/endResetModel → full refresh
Role derivation
Roles are derived from the keys of the first item in the model. Qt::UserRole + 1 is mapped to the first key, +2 to the second, etc. Qt::DisplayRole is aliased to the "display" key (or first key if absent).
Example (generated code)
// In ViewModel constructor:
itemModel_ = new EntityListModel(this);
// After gRPC fetch:
QVariantList items;
for (const auto& e : response.items()) {
    QVariantMap row;
    row["id"]   = QString::fromStdString(e.id().value());
    row["name"] = QString::fromStdString(e.name());
    items.append(row);
}
itemModel_->replaceItems(items);
See also
ADR 20260227-qml-idiomatic-output-quality Decision 4
Definition at line 64 of file entity_list_model.hpp.
Constructor & Destructor Documentation
EntityListModel()
muscovite::qt::models::EntityListModel::EntityListModel (QObject * parent = nullptr) explicit
Definition at line 14 of file entity_list_model.cpp.
Member Function Documentation
appendItem()
void muscovite::qt::models::EntityListModel::appendItem (const QVariantMap & item)
Append a single item. Emits proper insert notifications for animations.
Definition at line 59 of file entity_list_model.cpp.
References appendItem(), and countChanged().
Referenced by appendItem().
clear()
void muscovite::qt::models::EntityListModel::clear ()
Remove all items.
Definition at line 97 of file entity_list_model.cpp.
References clear(), and countChanged().
Referenced by clear().
count()
int muscovite::qt::models::EntityListModel::count () const nodiscard
Number of items (alias for rowCount, QML-friendly).
Definition at line 55 of file entity_list_model.cpp.
References count.
data()
QVariant muscovite::qt::models::EntityListModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const nodiscard override
Returns data for the given index and role. Roles are mapped to QVariantMap keys derived from the first item.
Definition at line 24 of file entity_list_model.cpp.
References data().
Referenced by data().
idAt()
QString muscovite::qt::models::EntityListModel::idAt (int row) const nodiscard
Convenience: get the "id" field at the given row, or empty string.
Definition at line 114 of file entity_list_model.cpp.
References idAt().
Referenced by idAt().
itemAt()
QVariantMap muscovite::qt::models::EntityListModel::itemAt (int row) const nodiscard
Get the full QVariantMap at the given row, or empty map if invalid.
Definition at line 107 of file entity_list_model.cpp.
References itemAt().
Referenced by itemAt().
removeItem()
void muscovite::qt::models::EntityListModel::removeItem (int row)
Remove the item at the given row. Emits proper remove notifications.
Definition at line 72 of file entity_list_model.cpp.
References countChanged(), and removeItem().
Referenced by removeItem().
replaceItems()
void muscovite::qt::models::EntityListModel::replaceItems (const QVariantList & items)
Replace all items. Derives roles from first item's keys. Uses beginResetModel/endResetModel.
Definition at line 82 of file entity_list_model.cpp.
References countChanged(), and replaceItems().
Referenced by replaceItems().
roleNames()
QHash< int, QByteArray > muscovite::qt::models::EntityListModel::roleNames () const nodiscard override
Returns the role-name mapping derived from item keys.
Definition at line 51 of file entity_list_model.cpp.
References roleNames().
Referenced by roleNames().
rowCount()
int muscovite::qt::models::EntityListModel::rowCount (const QModelIndex & parent = QModelIndex()) const nodiscard override
Returns the number of rows (items) in the model.
Definition at line 17 of file entity_list_model.cpp.
References rowCount().
Referenced by rowCount().
Property Documentation
count
int muscovite::qt::models::EntityListModel::count read
Number of items in the model (for QML binding).
Definition at line 68 of file entity_list_model.hpp.
Referenced by count().
The documentation for this class was generated from the following files:
framework/qt/include/muscovite/qt/models/entity_list_model.hpp
framework/qt/src/models/entity_list_model.cpp