Muscovite C++ Framework: muscovite::qt::Theme Class Reference
muscovite::qt::Theme Class Reference
Centralized theming singleton for Muscovite Qt applications.
#include <theme.hpp>
Public Member Functions
Theme (Theme &&)=delete
Theme (Theme const &)=delete
auto backgroundColor () const -> QColor
Background color for main content areas.
auto baseSpacing () const -> int
Base spacing unit in pixels (default: 8).
auto borderRadius () const -> int
Border radius in pixels (default: 4).
auto errorColor () const -> QColor
Error/destructive action color (default: Material Red #F44336).
auto errorLabelStyle () const -> QString
Error label style (red text).
auto fieldClearStyle () const -> QString
Field clear style (removes borders/highlights).
auto fieldErrorHighlightStyle () const -> QString
Field error highlight style (red border).
auto fieldValidHighlightStyle () const -> QString
Field valid highlight style (green border).
auto infoPanelStyle () const -> QString
Info panel style (light grey background with padding).
auto isDarkMode () const -> bool
Whether dark mode is active.
auto operator= (Theme &&) -> Theme &=delete
auto operator= (Theme const &) -> Theme &=delete
auto primaryColor () const -> QColor
Primary brand color (default: Material Blue #2196F3).
void setDarkMode (bool dark)
Toggle dark mode at runtime.
auto statusErrorTextStyle () const -> QString
Status error text style (red text, small font).
auto statusLabelStyle () const -> QString
Status label style (blue text).
auto statusTextStyle () const -> QString
Status text style (muted grey, small font).
auto statusValidTextStyle () const -> QString
Status valid text style (green text, small font).
auto successColor () const -> QColor
Success/confirmation color (default: Material Green #4CAF50).
auto surfaceColor () const -> QColor
Surface color for cards, dialogs, elevated elements.
auto textColor () const -> QColor
Primary text color.
auto textOnPrimaryColor () const -> QColor
Text color for use on primary-colored backgrounds.
auto warningColor () const -> QColor
Warning color (default: Material Amber #FFC107).
Static Public Member Functions
static void configure (ThemeConfig config)
Configure the theme before first use.
static auto instance () -> Theme const &
Access the global theme instance.
Detailed Description
Centralized theming singleton for Muscovite Qt applications.
Generated Qt Widgets code calls Theme::instance().primaryColor() etc. instead of embedding hardcoded color literals.
Usage:
// Optional: configure before first use
muscovite::qt::ThemeConfig cfg;
cfg.primaryColor = QColor("#FF5722");
muscovite::qt::Theme::configure(std::move(cfg));
// Access anywhere
auto color = muscovite::qt::Theme::instance().primaryColor();
widget->setStyleSheet(
    QString("background-color: %1;").arg(color.name()));
Note
Thread-safe. configure() must be called before the first instance() call.
Definition at line 71 of file theme.hpp.
Member Function Documentation
backgroundColor()
auto muscovite::qt::Theme::backgroundColor () const -> QColor nodiscard
Background color for main content areas.
Definition at line 52 of file theme.cpp.
baseSpacing()
auto muscovite::qt::Theme::baseSpacing () const -> int nodiscard
Base spacing unit in pixels (default: 8).
Definition at line 82 of file theme.cpp.
borderRadius()
auto muscovite::qt::Theme::borderRadius () const -> int nodiscard
Border radius in pixels (default: 4).
Definition at line 86 of file theme.cpp.
configure()
void muscovite::qt::Theme::configure (ThemeConfig config) static
Configure the theme before first use.
Parameters
config Theme overrides. Unset fields retain defaults.
Exceptions
std::logic_error if called after instance() has been accessed.
Definition at line 38 of file theme.cpp.
errorColor()
auto muscovite::qt::Theme::errorColor () const -> QColor nodiscard
Error/destructive action color (default: Material Red #F44336).
Definition at line 60 of file theme.cpp.
Referenced by errorLabelStyle(), fieldErrorHighlightStyle(), and statusErrorTextStyle().
errorLabelStyle()
auto muscovite::qt::Theme::errorLabelStyle () const -> QString nodiscard
Error label style (red text).
Definition at line 120 of file theme.cpp.
References errorColor().
fieldClearStyle()
auto muscovite::qt::Theme::fieldClearStyle () const -> QString nodiscard
Field clear style (removes borders/highlights).
Definition at line 136 of file theme.cpp.
fieldErrorHighlightStyle()
auto muscovite::qt::Theme::fieldErrorHighlightStyle () const -> QString nodiscard
Field error highlight style (red border).
Definition at line 128 of file theme.cpp.
References errorColor().
fieldValidHighlightStyle()
auto muscovite::qt::Theme::fieldValidHighlightStyle () const -> QString nodiscard
Field valid highlight style (green border).
Definition at line 132 of file theme.cpp.
References successColor().
infoPanelStyle()
auto muscovite::qt::Theme::infoPanelStyle () const -> QString nodiscard
Info panel style (light grey background with padding).
Definition at line 140 of file theme.cpp.
References surfaceColor(), and textColor().
instance()
auto muscovite::qt::Theme::instance () -> Theme const & static nodiscard
Access the global theme instance.
Returns
Reference to the singleton Theme.
Definition at line 26 of file theme.cpp.
isDarkMode()
auto muscovite::qt::Theme::isDarkMode () const -> bool nodiscard
Whether dark mode is active.
Definition at line 92 of file theme.cpp.
primaryColor()
auto muscovite::qt::Theme::primaryColor () const -> QColor nodiscard
Primary brand color (default: Material Blue #2196F3).
Definition at line 48 of file theme.cpp.
Referenced by statusLabelStyle().
setDarkMode()
void muscovite::qt::Theme::setDarkMode (bool dark)
Toggle dark mode at runtime.
Parameters
dark True for dark mode, false for light mode.
Definition at line 96 of file theme.cpp.
statusErrorTextStyle()
auto muscovite::qt::Theme::statusErrorTextStyle () const -> QString nodiscard
Status error text style (red text, small font).
Definition at line 153 of file theme.cpp.
References errorColor().
statusLabelStyle()
auto muscovite::qt::Theme::statusLabelStyle () const -> QString nodiscard
Status label style (blue text).
Definition at line 124 of file theme.cpp.
References primaryColor().
statusTextStyle()
auto muscovite::qt::Theme::statusTextStyle () const -> QString nodiscard
Status text style (muted grey, small font).
Definition at line 146 of file theme.cpp.
References textColor().
statusValidTextStyle()
auto muscovite::qt::Theme::statusValidTextStyle () const -> QString nodiscard
Status valid text style (green text, small font).
Definition at line 157 of file theme.cpp.
References successColor().
successColor()
auto muscovite::qt::Theme::successColor () const -> QColor nodiscard
Success/confirmation color (default: Material Green #4CAF50).
Definition at line 64 of file theme.cpp.
Referenced by fieldValidHighlightStyle(), and statusValidTextStyle().
surfaceColor()
auto muscovite::qt::Theme::surfaceColor () const -> QColor nodiscard
Surface color for cards, dialogs, elevated elements.
Definition at line 56 of file theme.cpp.
Referenced by infoPanelStyle().
textColor()
auto muscovite::qt::Theme::textColor () const -> QColor nodiscard
Primary text color.
Definition at line 72 of file theme.cpp.
Referenced by infoPanelStyle(), and statusTextStyle().
textOnPrimaryColor()
auto muscovite::qt::Theme::textOnPrimaryColor () const -> QColor nodiscard
Text color for use on primary-colored backgrounds.
Definition at line 76 of file theme.cpp.
warningColor()
auto muscovite::qt::Theme::warningColor () const -> QColor nodiscard
Warning color (default: Material Amber #FFC107).
Definition at line 68 of file theme.cpp.
The documentation for this class was generated from the following files:
framework/qt/include/muscovite/qt/theme.hpp
framework/qt/src/theme.cpp