Muscovite C++ Framework: muscovite::messaging::Publisher Class Reference
muscovite::messaging::Publisher Class Reference abstract
#include <publisher.hpp>
Public Member Functions
virtual auto connect () -> bool=0
virtual void disconnect ()=0
Disconnect from the message broker.
virtual auto ensure_infrastructure (const std::string &stream_name, const std::string &subject_prefix) -> bool=0
virtual auto is_connected () const -> bool=0
Check if connected to the broker.
virtual auto last_error () const -> std::string=0
Get the last error message.
virtual auto messages_published () const -> std::uint64_t=0
Get number of messages published since connect.
virtual auto publish (const MessageEnvelope &envelope) -> PublishResult=0
virtual auto publish_acked (const MessageEnvelope &envelope) -> std::optional< PublishAck >=0
Detailed Description
Abstract publisher interface
Provides a transport-agnostic API for publishing messages. Generated code depends only on this interface; the concrete implementation (NATS, in-memory) is injected at construction time.
Thread Safety: Implementations MUST be thread-safe for concurrent publish().
Definition at line 35 of file publisher.hpp.
Member Function Documentation
connect()
virtual auto muscovite::messaging::Publisher::connect () -> bool nodiscard pure virtual
Connect to the message broker
Returns
true if connected, false on error
Implemented in muscovite::messaging::InMemoryPublisher, and muscovite::messaging::NatsPublisher.
disconnect()
virtual void muscovite::messaging::Publisher::disconnect () pure virtual
Disconnect from the message broker.
Implemented in muscovite::messaging::InMemoryPublisher, and muscovite::messaging::NatsPublisher.
ensure_infrastructure()
virtual auto muscovite::messaging::Publisher::ensure_infrastructure (const std::string & stream_name, const std::string & subject_prefix) -> bool nodiscard pure virtual
Ensure broker infrastructure exists (e.g., JetStream streams)
Parameters
stream_name Name of the stream to create
subject_prefix Subject prefix for the stream (e.g., "muscovite.patient")
Returns
true if infrastructure ready, false on error
Implemented in muscovite::messaging::InMemoryPublisher, and muscovite::messaging::NatsPublisher.
References ensure_infrastructure().
Referenced by ensure_infrastructure().
is_connected()
virtual auto muscovite::messaging::Publisher::is_connected () const -> bool nodiscard pure virtual
Check if connected to the broker.
Implemented in muscovite::messaging::InMemoryPublisher, and muscovite::messaging::NatsPublisher.
last_error()
virtual auto muscovite::messaging::Publisher::last_error () const -> std::string nodiscard pure virtual
Get the last error message.
Implemented in muscovite::messaging::InMemoryPublisher, and muscovite::messaging::NatsPublisher.
References last_error().
Referenced by last_error().
messages_published()
virtual auto muscovite::messaging::Publisher::messages_published () const -> std::uint64_t nodiscard pure virtual
Get number of messages published since connect.
Implemented in muscovite::messaging::InMemoryPublisher, and muscovite::messaging::NatsPublisher.
References messages_published().
Referenced by messages_published().
publish()
virtual auto muscovite::messaging::Publisher::publish (const MessageEnvelope & envelope) -> PublishResult nodiscard pure virtual
Publish a message envelope to the broker
Parameters
envelope Message with subject, payload, and metadata
Returns
PublishResult indicating success or error type
Implemented in muscovite::messaging::InMemoryPublisher, and muscovite::messaging::NatsPublisher.
References publish().
Referenced by publish().
publish_acked()
virtual auto muscovite::messaging::Publisher::publish_acked (const MessageEnvelope & envelope) -> std::optional< PublishAck > nodiscard pure virtual
Publish with explicit acknowledgment details
Parameters
envelope Message to publish
Returns
PublishAck on success, nullopt on error
Implemented in muscovite::messaging::InMemoryPublisher, and muscovite::messaging::NatsPublisher.
References publish_acked().
Referenced by publish_acked().
The documentation for this class was generated from the following file:
framework/messaging/include/muscovite/messaging/publisher.hpp