Muscovite C++ Framework: muscovite::qt::TokenStorage Class Reference
muscovite::qt::TokenStorage Class Reference
Secure token storage using platform keychain.
#include <token_storage.hpp>
Signals
void errorOccurred (const QString &_t1)
Emitted when an error occurs.
void tokensCleared ()
Emitted when tokens are cleared.
void tokensSaved ()
Emitted when tokens are saved.
Public Member Functions
TokenStorage (const TokenStorage &)=delete
TokenStorage (TokenStorage &&)=delete
bool clearTokens ()
Clear stored tokens.
TokenStorage & operator= (const TokenStorage &)=delete
TokenStorage & operator= (TokenStorage &&)=delete
bool saveTokens (const StoredTokens &tokens)
Save tokens to secure storage.
QString serviceName () const
Get the current service name.
void setServiceName (const QString &serviceName)
Set the service name for keychain.
Static Public Member Functions
static bool hasStoredTokens ()
Check if tokens are stored.
static TokenStorage & instance ()
Get singleton instance.
static std::optional< StoredTokens > loadTokens ()
Load tokens from secure storage.
Detailed Description
Secure token storage using platform keychain.
On macOS: Uses Keychain On Linux: Uses libsecret/kwallet On Windows: Uses Windows Credential Manager
Falls back to encrypted file storage if no keychain is available.
Definition at line 35 of file token_storage.hpp.
Member Function Documentation
clearTokens()
bool muscovite::qt::TokenStorage::clearTokens ()
Clear stored tokens.
Returns
true if cleared successfully
Definition at line 288 of file token_storage.cpp.
References tokensCleared().
errorOccurred
void muscovite::qt::TokenStorage::errorOccurred (const QString & _t1) signal
Emitted when an error occurs.
Parameters
error Error message
Referenced by saveTokens().
hasStoredTokens()
bool muscovite::qt::TokenStorage::hasStoredTokens () static
Check if tokens are stored.
Returns
true if tokens exist in storage
Definition at line 307 of file token_storage.cpp.
References loadTokens().
instance()
TokenStorage & muscovite::qt::TokenStorage::instance () static
Get singleton instance.
Definition at line 241 of file token_storage.cpp.
References instance().
Referenced by instance().
loadTokens()
std::optional< StoredTokens > muscovite::qt::TokenStorage::loadTokens () static
Load tokens from secure storage.
Returns
Stored tokens or nullopt if not found
Definition at line 275 of file token_storage.cpp.
Referenced by hasStoredTokens().
saveTokens()
bool muscovite::qt::TokenStorage::saveTokens (const StoredTokens & tokens)
Save tokens to secure storage.
Parameters
tokens Tokens to save
Returns
true if saved successfully
Definition at line 252 of file token_storage.cpp.
References errorOccurred(), and tokensSaved().
serviceName()
QString muscovite::qt::TokenStorage::serviceName () const nodiscard
Get the current service name.
Returns
Service name
Definition at line 315 of file token_storage.cpp.
Referenced by setServiceName().
setServiceName()
void muscovite::qt::TokenStorage::setServiceName (const QString & serviceName)
Set the service name for keychain.
Parameters
serviceName Service name (default: "muscovite")
Definition at line 311 of file token_storage.cpp.
References serviceName().
The documentation for this class was generated from the following files:
framework/qt/include/muscovite/qt/auth/token_storage.hpp
framework/qt/src/auth/token_storage.cpp