Muscovite C++ Framework: muscovite::grpc Namespace Reference
muscovite::grpc Namespace Reference
gRPC service infrastructure for muscovite
Namespaces
namespace oauth2
Classes
class ActorContext
Thread-local holder for the authenticated caller's principal UUID string.
class CorrelationContext
Thread-local holder for request-scoped correlation ID (UUIDv4).
class CorrelationFlagFormatter
spdlog custom flag formatter reading the thread-local correlation ID.
class GrpcServer
struct GrpcServerConfig
gRPC server configuration
class ServiceBase
Typedefs
using Decimal = boost::multiprecision::cpp_dec_float_50
Decimal type alias (50 digits).
Enumerations
enum class GrpcServerError { AlreadyRunning , NotRunning , BuildFailed , ShutdownFailed }
gRPC server error codes
Functions
auto bool_to_string (bool value) noexcept -> std::string
Convert bool to protobuf string.
auto date_to_iso8601 (const std::chrono::year_month_day &date) -> std::string
Convert year_month_day to ISO 8601 date string.
auto date_to_string (const std::chrono::year_month_day &date) -> std::string
Convert std::chrono::year_month_day to ISO 8601 string.
auto decimal_from_proto (const proto::Decimal &src) -> Decimal
Convert proto Decimal to Decimal (explicit helper for generator).
void decimal_to_proto (const Decimal &src, proto::Decimal *dst)
Convert Decimal to proto Decimal (explicit helper for generator).
auto decimal_to_string (const Decimal &value) -> std::string
Convert Decimal to protobuf string with full precision.
auto from_proto (const proto::Date &src) -> std::chrono::year_month_day
Convert proto Date to chrono year_month_day.
auto from_proto (const proto::Decimal &src) -> Decimal
Convert proto Decimal to Decimal.
auto from_proto (const proto::Interval &src) -> std::chrono::microseconds
Convert proto Interval to chrono microseconds.
auto from_proto (const proto::TimeOfDay &src) -> std::chrono::microseconds
auto from_proto (const proto::Timestamp &src) -> std::chrono::system_clock::time_point
Convert proto Timestamp to chrono time_point.
auto from_proto (const proto::UUID &src) -> boost::uuids::uuid
Convert proto UUID to boost::uuid.
template<typename Proto, typename T>
auto from_proto_optional (const Proto &src, bool has_value) -> std::optional< T >
Convert proto to optional (checks if field has meaningful value).
auto int32_to_string (std::int32_t value) -> std::string
Convert std::int32_t to protobuf string.
auto int64_to_string (std::int64_t value) -> std::string
Convert std::int64_t to protobuf string.
constexpr auto is_deadline_exceeded (const ::grpc::Status &status) noexcept -> bool
Check if a gRPC status specifically indicates a deadline exceeded.
constexpr auto is_permanent (const ::grpc::Status &status) noexcept -> bool
Check if a gRPC status represents a permanent, non-retryable error.
constexpr auto is_retryable (const ::grpc::Status &status) noexcept -> bool
Check if a gRPC status represents a retryable transient error.
auto iso8601_to_date (std::string_view s) -> std::chrono::year_month_day
Convert ISO 8601 date string to year_month_day.
auto iso8601_to_timestamp (std::string_view s) -> std::chrono::system_clock::time_point
Convert ISO 8601 string to system_clock::time_point.
auto make_status (::grpc::StatusCode code, const std::string &message, const std::string &sql_state={}) -> ::grpc::Status
auto map_db_error (const dba::Error< dba::DbError > &error) -> ::grpc::Status
auto map_pool_error (const dba::Error< dba::PoolError > &error) -> ::grpc::Status
auto optional_bool_to_string (const std::optional< bool > &value) -> std::string
Convert optional bool to protobuf string.
auto optional_date_to_string (const std::optional< std::chrono::year_month_day > &date) -> std::string
Convert optional date to protobuf string.
auto optional_decimal_to_string (const std::optional< Decimal > &value) -> std::string
Convert optional Decimal to protobuf string.
auto optional_int64_to_string (const std::optional< std::int64_t > &value) -> std::string
Convert optional std::int64_t to protobuf string (empty string if not set).
auto optional_string_from_proto (std::string_view str) -> std::optional< std::string >
Convert protobuf string to optional string (empty = not set).
auto optional_string_to_bool (std::string_view str) noexcept -> std::optional< bool >
Parse optional protobuf string to optional bool.
auto optional_string_to_date (std::string_view str) -> std::optional< std::chrono::year_month_day >
Parse optional protobuf string to optional date.
auto optional_string_to_decimal (std::string_view str) -> std::optional< Decimal >
Parse optional protobuf string to optional Decimal.
auto optional_string_to_int64 (std::string_view str) -> std::optional< std::int64_t >
Parse optional protobuf string to optional std::int64_t.
auto optional_string_to_proto (const std::optional< std::string > &str) -> std::string
Convert optional string to protobuf string (empty if not set).
auto optional_string_to_string (std::string_view str) -> std::optional< std::string >
Parse optional protobuf string to optional string (alias for optional_string_from_proto).
auto optional_string_to_time (std::string_view str) -> std::optional< std::chrono::microseconds >
Parse optional protobuf string to optional time.
auto optional_string_to_timestamp (std::string_view str) -> std::optional< std::chrono::system_clock::time_point >
Parse optional protobuf string to optional timestamp.
auto optional_string_to_uuid (std::string_view s) -> std::optional< boost::uuids::uuid >
Convert string to optional UUID (nullopt if empty).
auto optional_time_to_string (const std::optional< std::chrono::microseconds > &time) -> std::string
Convert optional time to protobuf string.
auto optional_timestamp_to_string (const std::optional< std::chrono::system_clock::time_point > &ts) -> std::string
Convert optional timestamp to protobuf string.
auto optional_uuid_to_string (const std::optional< boost::uuids::uuid > &id) noexcept -> std::string
Convert optional UUID to string (empty string if not set).
auto spatial_to_wkt (const proto::LineString &src) -> std::string
auto spatial_to_wkt (const proto::Point &src) -> std::string
auto spatial_to_wkt (const proto::Polygon &src) -> std::string
auto string_to_bool (std::string_view str) noexcept -> bool
Parse protobuf string to bool.
auto string_to_date (std::string_view str) -> std::chrono::year_month_day
Parse protobuf string (ISO 8601 YYYY-MM-DD) to std::chrono::year_month_day.
auto string_to_decimal (std::string_view str) -> Decimal
Parse protobuf string to Decimal.
auto string_to_int32 (std::string_view str) -> std::int32_t
Parse protobuf string to std::int32_t using std::from_chars.
auto string_to_int64 (std::string_view str) -> std::int64_t
Parse protobuf string to std::int64_t using std::from_chars.
auto string_to_time (std::string_view str) -> std::chrono::microseconds
Parse protobuf string (HH:MM:SS or HH:MM:SS.ffffff) to std::chrono::microseconds.
auto string_to_timestamp (std::string_view str) -> std::chrono::system_clock::time_point
Parse protobuf string (ISO 8601) to std::chrono::system_clock::time_point.
auto string_to_uuid (std::string_view s) -> boost::uuids::uuid
Convert string to boost::uuids::uuid.
auto time_to_string (const std::chrono::microseconds &time) -> std::string
Convert std::chrono::microseconds (time of day) to HH:MM:SS[.ffffff] string.
auto timestamp_to_iso8601 (const std::chrono::system_clock::time_point &ts) -> std::string
Convert system_clock::time_point to ISO 8601 UTC string.
auto timestamp_to_string (const std::chrono::system_clock::time_point &ts) -> std::string
Convert std::chrono::system_clock::time_point to ISO 8601 string.
void to_proto (const boost::uuids::uuid &src, proto::UUID *dst)
Convert boost::uuid to proto UUID.
void to_proto (const Decimal &src, proto::Decimal *dst)
Convert Decimal to proto Decimal.
void to_proto (const std::chrono::microseconds &src, proto::Interval *dst)
Convert chrono microseconds to proto Interval.
void to_proto (const std::chrono::microseconds &src, proto::TimeOfDay *dst)
void to_proto (const std::chrono::system_clock::time_point &src, proto::Timestamp *dst)
Convert chrono time_point to proto Timestamp.
void to_proto (const std::chrono::year_month_day &src, proto::Date *dst)
Convert chrono year_month_day to proto Date.
template<typename T, typename Proto>
void to_proto_optional (const std::optional< T > &src, Proto *dst)
Convert optional value to proto (sets field if present).
auto uuid_from_string (const std::string &s) -> boost::uuids::uuid
Convert UUID string to boost::uuid (with validation).
auto uuid_to_string (const boost::uuids::uuid &id) noexcept -> std::string
Convert boost::uuids::uuid to string representation.
void wkt_to_spatial (const std::string &wkt, proto::LineString *dst)
void wkt_to_spatial (const std::string &wkt, proto::Point *dst)
void wkt_to_spatial (const std::string &wkt, proto::Polygon *dst)
Detailed Description
gRPC service infrastructure for muscovite
This library provides:
GrpcServer: Server lifecycle management
ServiceBase: CRTP base class for generated services
Type mapping: Convert between C++ and proto types
Error mapping: Map DbError/PoolError to gRPC status
Interceptors: Logging, metrics, error handling
Usage
Generated services inherit from ServiceBase and use the utilities:
#include <muscovite/grpc.hpp>
class MyServiceImpl : public muscovite::grpc::ServiceBase<MyServiceImpl>,
                      public myproto::MyService::Service {
public:
    using ServiceBase::ServiceBase;
    ::grpc::Status GetById(...) override {
        return execute_read([&](pqxx::transaction<>& tx) {
            // Database operations
        });
    }
};
int main() {
    // Create connection pool
    auto pool = dba::ConnectionPool::create(config).value();
    // Create and configure server
    muscovite::grpc::GrpcServer server{grpc_config};
    // Register service
    MyServiceImpl service{pool};
    server.register_service(&service);
    // Start and wait
    server.start();
    server.wait();
}
Typedef Documentation
Decimal
using muscovite::grpc::Decimal = boost::multiprecision::cpp_dec_float_50
Decimal type alias (50 digits).
Definition at line 40 of file proto_type_converters.hpp.
Enumeration Type Documentation
GrpcServerError
enum class muscovite::grpc::GrpcServerError strong
gRPC server error codes
Enumerator
AlreadyRunning
Server is already running.
NotRunning
Server is not running.
BuildFailed
Failed to build server.
ShutdownFailed
Failed to shutdown gracefully.
Definition at line 30 of file server.hpp.
Function Documentation
bool_to_string()
auto muscovite::grpc::bool_to_string (bool value) -> std::string inline nodiscard noexcept
Convert bool to protobuf string.
Parameters
value The boolean to serialize.
Returns
"true" or "false".
Definition at line 511 of file proto_type_converters.hpp.
Referenced by optional_bool_to_string().
date_to_iso8601()
auto muscovite::grpc::date_to_iso8601 (const std::chrono::year_month_day & date) -> std::string inline nodiscard
Convert year_month_day to ISO 8601 date string.
Parameters
date The date to convert
Returns
ISO 8601 date string (YYYY-MM-DD)
Definition at line 145 of file proto_converters.hpp.
date_to_string()
auto muscovite::grpc::date_to_string (const std::chrono::year_month_day & date) -> std::string inline nodiscard
Convert std::chrono::year_month_day to ISO 8601 string.
Parameters
date The date to serialize.
Returns
String in YYYY-MM-DD format.
Definition at line 254 of file proto_type_converters.hpp.
Referenced by optional_date_to_string().
decimal_from_proto()
auto muscovite::grpc::decimal_from_proto (const proto::Decimal & src) -> Decimal nodiscard
Convert proto Decimal to Decimal (explicit helper for generator).
Definition at line 75 of file type_mapping.cpp.
References from_proto().
decimal_to_proto()
void muscovite::grpc::decimal_to_proto (const Decimal & src, proto::Decimal * dst)
Convert Decimal to proto Decimal (explicit helper for generator).
Definition at line 79 of file type_mapping.cpp.
References to_proto().
decimal_to_string()
auto muscovite::grpc::decimal_to_string (const Decimal & value) -> std::string inline nodiscard
Convert Decimal to protobuf string with full precision.
Parameters
value The Decimal to serialize.
Returns
String with max_digits10 precision.
Definition at line 179 of file proto_type_converters.hpp.
Referenced by optional_decimal_to_string().
from_proto() [1/6]
auto muscovite::grpc::from_proto (const proto::Date & src) -> std::chrono::year_month_day nodiscard
Convert proto Date to chrono year_month_day.
Definition at line 91 of file type_mapping.cpp.
from_proto() [2/6]
auto muscovite::grpc::from_proto (const proto::Decimal & src) -> Decimal nodiscard
Convert proto Decimal to Decimal.
Definition at line 71 of file type_mapping.cpp.
from_proto() [3/6]
auto muscovite::grpc::from_proto (const proto::Interval & src) -> std::chrono::microseconds nodiscard
Convert proto Interval to chrono microseconds.
Definition at line 105 of file type_mapping.cpp.
from_proto() [4/6]
auto muscovite::grpc::from_proto (const proto::TimeOfDay & src) -> std::chrono::microseconds nodiscard
Convert proto TimeOfDay to chrono microseconds Returns microseconds since midnight for DBA compatibility
Definition at line 97 of file type_mapping.cpp.
from_proto() [5/6]
auto muscovite::grpc::from_proto (const proto::Timestamp & src) -> std::chrono::system_clock::time_point nodiscard
Convert proto Timestamp to chrono time_point.
Definition at line 83 of file type_mapping.cpp.
from_proto() [6/6]
auto muscovite::grpc::from_proto (const proto::UUID & src) -> boost::uuids::uuid nodiscard
Convert proto UUID to boost::uuid.
Definition at line 66 of file type_mapping.cpp.
Referenced by decimal_from_proto(), and from_proto_optional().
from_proto_optional()
template<typename Proto, typename T> auto muscovite::grpc::from_proto_optional (const Proto & src, bool has_value) -> std::optional< T > nodiscard
Convert proto to optional (checks if field has meaningful value).
Definition at line 143 of file type_mapping.hpp.
References from_proto().
int32_to_string()
auto muscovite::grpc::int32_to_string (std::int32_t value) -> std::string inline nodiscard
Convert std::int32_t to protobuf string.
Parameters
value The integer to serialize.
Returns
Decimal string representation.
Definition at line 115 of file proto_type_converters.hpp.
int64_to_string()
auto muscovite::grpc::int64_to_string (std::int64_t value) -> std::string inline nodiscard
Convert std::int64_t to protobuf string.
Parameters
value The integer to serialize.
Returns
Decimal string representation.
Definition at line 139 of file proto_type_converters.hpp.
Referenced by optional_int64_to_string().
is_deadline_exceeded()
auto muscovite::grpc::is_deadline_exceeded (const ::grpc::Status & status) -> bool nodiscard constexpr noexcept
Check if a gRPC status specifically indicates a deadline exceeded.
DEADLINE_EXCEEDED is technically retryable, but callers should check remaining time budget before retrying (FTR-235 RetryPolicy.deadline).
Parameters
status The gRPC status to classify
Returns
true if the error is DEADLINE_EXCEEDED
See also
FTR-233, FTR-235
Definition at line 93 of file retry_classification.hpp.
is_permanent()
auto muscovite::grpc::is_permanent (const ::grpc::Status & status) -> bool nodiscard constexpr noexcept
Check if a gRPC status represents a permanent, non-retryable error.
Permanent codes: NOT_FOUND, ALREADY_EXISTS, INVALID_ARGUMENT, PERMISSION_DENIED, UNAUTHENTICATED, UNIMPLEMENTED, FAILED_PRECONDITION. Retrying these will produce the same result.
Parameters
status The gRPC status to classify
Returns
true if the error is permanent and should not be retried
See also
FTR-233
Definition at line 70 of file retry_classification.hpp.
is_retryable()
auto muscovite::grpc::is_retryable (const ::grpc::Status & status) -> bool nodiscard constexpr noexcept
Check if a gRPC status represents a retryable transient error.
Retryable codes: ABORTED, UNAVAILABLE, DEADLINE_EXCEEDED, RESOURCE_EXHAUSTED. These indicate transient conditions where a retry may succeed.
Parameters
status The gRPC status to classify
Returns
true if the error is potentially transient and retryable
See also
FTR-233
Definition at line 49 of file retry_classification.hpp.
iso8601_to_date()
auto muscovite::grpc::iso8601_to_date (std::string_view s) -> std::chrono::year_month_day inline nodiscard
Convert ISO 8601 date string to year_month_day.
Parameters
s ISO 8601 date string (YYYY-MM-DD)
Returns
Parsed date
Exceptions
std::invalid_argument if the string is not a valid ISO 8601 date
Definition at line 160 of file proto_converters.hpp.
iso8601_to_timestamp()
auto muscovite::grpc::iso8601_to_timestamp (std::string_view s) -> std::chrono::system_clock::time_point inline nodiscard
Convert ISO 8601 string to system_clock::time_point.
Parameters
s ISO 8601 formatted string (YYYY-MM-DDTHH:MM:SS or with Z suffix)
Returns
Parsed time point
Exceptions
std::invalid_argument if the string is not a valid ISO 8601 timestamp
Definition at line 109 of file proto_converters.hpp.
make_status()
auto muscovite::grpc::make_status (::grpc::StatusCode code, const std::string & message, const std::string & sql_state = {}) -> ::grpc::Status nodiscard
Create gRPC Status with error details
Parameters
code gRPC status code
message Human-readable message
sql_state PostgreSQL SQLSTATE (optional)
Definition at line 78 of file error_mapping.cpp.
Referenced by map_db_error().
map_db_error()
auto muscovite::grpc::map_db_error (const dba::Error< dba::DbError > & error) -> ::grpc::Status nodiscard
Map DbError to gRPC Status
Mapping table:
DbError gRPC Code
ConnectionFailed UNAVAILABLE
QueryFailed INTERNAL
SerializationFailure ABORTED
DeadlockDetected ABORTED
UniqueViolation ALREADY_EXISTS
ForeignKeyViolation FAILED_PRECONDITION
ConstraintViolation INVALID_ARGUMENT
CheckViolation INVALID_ARGUMENT
NotNullViolation INVALID_ARGUMENT
ConversionError INVALID_ARGUMENT
Timeout DEADLINE_EXCEEDED
Unknown UNKNOWN
Definition at line 17 of file error_mapping.cpp.
References make_status().
Referenced by muscovite::grpc::ServiceBase< Derived >::execute_read(), muscovite::grpc::ServiceBase< Derived >::execute_read(), muscovite::grpc::ServiceBase< Derived >::execute_write(), and muscovite::grpc::ServiceBase< Derived >::execute_write().
map_pool_error()
auto muscovite::grpc::map_pool_error (const dba::Error< dba::PoolError > & error) -> ::grpc::Status nodiscard
Map PoolError to gRPC Status
PoolError gRPC Code
ConnectionFailed UNAVAILABLE
PoolExhausted RESOURCE_EXHAUSTED
Timeout DEADLINE_EXCEEDED
InvalidConfig INTERNAL
AlreadyShutdown UNAVAILABLE
Definition at line 55 of file error_mapping.cpp.
optional_bool_to_string()
auto muscovite::grpc::optional_bool_to_string (const std::optional< bool > & value) -> std::string inline nodiscard
Convert optional bool to protobuf string.
Parameters
value Optional boolean.
Returns
"true", "false", or empty string.
Definition at line 518 of file proto_type_converters.hpp.
References bool_to_string().
optional_date_to_string()
auto muscovite::grpc::optional_date_to_string (const std::optional< std::chrono::year_month_day > & date) -> std::string inline nodiscard
Convert optional date to protobuf string.
Parameters
date Optional date value.
Returns
ISO 8601 string or empty string.
Definition at line 264 of file proto_type_converters.hpp.
References date_to_string().
optional_decimal_to_string()
auto muscovite::grpc::optional_decimal_to_string (const std::optional< Decimal > & value) -> std::string inline nodiscard
Convert optional Decimal to protobuf string.
Parameters
value Optional Decimal value.
Returns
Precision string or empty string.
Definition at line 196 of file proto_type_converters.hpp.
References decimal_to_string().
optional_int64_to_string()
auto muscovite::grpc::optional_int64_to_string (const std::optional< std::int64_t > & value) -> std::string inline nodiscard
Convert optional std::int64_t to protobuf string (empty string if not set).
Parameters
value Optional integer value.
Returns
Decimal string or empty string.
Definition at line 146 of file proto_type_converters.hpp.
References int64_to_string().
optional_string_from_proto()
auto muscovite::grpc::optional_string_from_proto (std::string_view str) -> std::optional< std::string > inline nodiscard
Convert protobuf string to optional string (empty = not set).
Parameters
str Input string from protobuf.
Returns
The string value or std::nullopt if empty.
Definition at line 463 of file proto_type_converters.hpp.
optional_string_to_bool()
auto muscovite::grpc::optional_string_to_bool (std::string_view str) -> std::optional< bool > inline nodiscard noexcept
Parse optional protobuf string to optional bool.
Parameters
str Boolean string; empty yields std::nullopt.
Returns
Parsed boolean or std::nullopt if empty.
Definition at line 528 of file proto_type_converters.hpp.
References string_to_bool().
optional_string_to_date()
auto muscovite::grpc::optional_string_to_date (std::string_view str) -> std::optional< std::chrono::year_month_day > inline nodiscard
Parse optional protobuf string to optional date.
Parameters
str Date string; empty yields std::nullopt.
Returns
Parsed date or std::nullopt if empty.
Exceptions
std::invalid_argument if non-empty but malformed.
Definition at line 275 of file proto_type_converters.hpp.
References string_to_date().
optional_string_to_decimal()
auto muscovite::grpc::optional_string_to_decimal (std::string_view str) -> std::optional< Decimal > inline nodiscard
Parse optional protobuf string to optional Decimal.
Parameters
str Decimal string; empty yields std::nullopt.
Returns
Parsed Decimal or std::nullopt if empty.
Definition at line 186 of file proto_type_converters.hpp.
optional_string_to_int64()
auto muscovite::grpc::optional_string_to_int64 (std::string_view str) -> std::optional< std::int64_t > inline nodiscard
Parse optional protobuf string to optional std::int64_t.
Parameters
str Integer string; empty yields std::nullopt.
Returns
Parsed integer or std::nullopt if empty.
Exceptions
std::invalid_argument if non-empty but invalid.
Definition at line 157 of file proto_type_converters.hpp.
References string_to_int64().
optional_string_to_proto()
auto muscovite::grpc::optional_string_to_proto (const std::optional< std::string > & str) -> std::string inline nodiscard
Convert optional string to protobuf string (empty if not set).
Parameters
str Optional string value.
Returns
String value or empty string.
Definition at line 483 of file proto_type_converters.hpp.
optional_string_to_string()
auto muscovite::grpc::optional_string_to_string (std::string_view str) -> std::optional< std::string > inline nodiscard
Parse optional protobuf string to optional string (alias for optional_string_from_proto).
Parameters
str Input string from protobuf.
Returns
The string value or std::nullopt if empty.
Definition at line 473 of file proto_type_converters.hpp.
optional_string_to_time()
auto muscovite::grpc::optional_string_to_time (std::string_view str) -> std::optional< std::chrono::microseconds > inline nodiscard
Parse optional protobuf string to optional time.
Parameters
str Time string; empty yields std::nullopt.
Returns
Parsed duration or std::nullopt if empty.
Exceptions
std::invalid_argument if non-empty but malformed.
Definition at line 449 of file proto_type_converters.hpp.
References string_to_time().
optional_string_to_timestamp()
auto muscovite::grpc::optional_string_to_timestamp (std::string_view str) -> std::optional< std::chrono::system_clock::time_point > inline nodiscard
Parse optional protobuf string to optional timestamp.
Parameters
str Timestamp string; empty yields std::nullopt.
Returns
Parsed time point or std::nullopt if empty.
Exceptions
std::invalid_argument if non-empty but malformed.
Definition at line 355 of file proto_type_converters.hpp.
References string_to_timestamp().
optional_string_to_uuid()
auto muscovite::grpc::optional_string_to_uuid (std::string_view str) -> std::optional< boost::uuids::uuid > inline nodiscard
Convert string to optional UUID (nullopt if empty).
Convert optional protobuf string to optional UUID.
Parameters
s String representation of a UUID or empty
Returns
Optional UUID
Exceptions
std::invalid_argument if non-empty string is not a valid UUID
Parameters
str UUID string; empty yields std::nullopt.
Returns
Parsed UUID or std::nullopt if empty.
Exceptions
std::invalid_argument if non-empty but invalid.
Definition at line 79 of file proto_converters.hpp.
References string_to_uuid().
optional_time_to_string()
auto muscovite::grpc::optional_time_to_string (const std::optional< std::chrono::microseconds > & time) -> std::string inline nodiscard
Convert optional time to protobuf string.
Parameters
time Optional duration since midnight.
Returns
Formatted time string or empty string.
Definition at line 438 of file proto_type_converters.hpp.
References time_to_string().
optional_timestamp_to_string()
auto muscovite::grpc::optional_timestamp_to_string (const std::optional< std::chrono::system_clock::time_point > & ts) -> std::string inline nodiscard
Convert optional timestamp to protobuf string.
Parameters
ts Optional time point.
Returns
ISO 8601 string or empty string.
Definition at line 344 of file proto_type_converters.hpp.
References timestamp_to_string().
optional_uuid_to_string()
auto muscovite::grpc::optional_uuid_to_string (const std::optional< boost::uuids::uuid > & id) -> std::string inline nodiscard noexcept
Convert optional UUID to string (empty string if not set).
Convert optional UUID to protobuf string (empty string if not set).
Parameters
id Optional UUID
Returns
String representation or empty string
Parameters
id Optional UUID value.
Returns
Canonical string or empty string.
Definition at line 67 of file proto_converters.hpp.
References uuid_to_string().
spatial_to_wkt() [1/3]
auto muscovite::grpc::spatial_to_wkt (const proto::LineString & src) -> std::string nodiscard
Convert proto LineString to WKT string Example output: "LINESTRING(-122.4 37.7, -122.5 37.8)"
Definition at line 119 of file type_mapping.cpp.
spatial_to_wkt() [2/3]
auto muscovite::grpc::spatial_to_wkt (const proto::Point & src) -> std::string nodiscard
Convert proto Point to WKT string Example output: "POINT(-122.4194 37.7749)"
Definition at line 113 of file type_mapping.cpp.
spatial_to_wkt() [3/3]
auto muscovite::grpc::spatial_to_wkt (const proto::Polygon & src) -> std::string nodiscard
Convert proto Polygon to WKT string Example output: "POLYGON((-122.4 37.7, -122.5 37.8, -122.4 37.9, -122.4 37.7))"
Definition at line 132 of file type_mapping.cpp.
string_to_bool()
auto muscovite::grpc::string_to_bool (std::string_view str) -> bool inline nodiscard noexcept
Parse protobuf string to bool.
Parameters
str Boolean string ("true", "1", "yes", "false", "0", "no", etc.).
Returns
Parsed boolean; ambiguous values default to false with a warning.
Definition at line 497 of file proto_type_converters.hpp.
Referenced by optional_string_to_bool().
string_to_date()
auto muscovite::grpc::string_to_date (std::string_view str) -> std::chrono::year_month_day inline nodiscard
Parse protobuf string (ISO 8601 YYYY-MM-DD) to std::chrono::year_month_day.
Parameters
str Date string in YYYY-MM-DD format.
Returns
Parsed date value.
Exceptions
std::invalid_argument if str is empty or malformed.
Definition at line 225 of file proto_type_converters.hpp.
Referenced by optional_string_to_date().
string_to_decimal()
auto muscovite::grpc::string_to_decimal (std::string_view str) -> Decimal inline nodiscard
Parse protobuf string to Decimal.
Parameters
str Decimal number string (e.g. "123.45").
Returns
Parsed Decimal value.
Note
boost::multiprecision constructor requires std::string (no string_view overload).
Definition at line 172 of file proto_type_converters.hpp.
string_to_int32()
auto muscovite::grpc::string_to_int32 (std::string_view str) -> std::int32_t inline nodiscard
Parse protobuf string to std::int32_t using std::from_chars.
Parameters
str Non-empty integer string.
Returns
Parsed 32-bit integer.
Exceptions
std::invalid_argument if str is empty or not a valid integer.
Definition at line 99 of file proto_type_converters.hpp.
string_to_int64()
auto muscovite::grpc::string_to_int64 (std::string_view str) -> std::int64_t inline nodiscard
Parse protobuf string to std::int64_t using std::from_chars.
Parameters
str Non-empty integer string.
Returns
Parsed 64-bit integer.
Exceptions
std::invalid_argument if str is empty or not a valid integer.
Definition at line 123 of file proto_type_converters.hpp.
Referenced by optional_string_to_int64().
string_to_time()
auto muscovite::grpc::string_to_time (std::string_view str) -> std::chrono::microseconds inline nodiscard
Parse protobuf string (HH:MM:SS or HH:MM:SS.ffffff) to std::chrono::microseconds.
Parameters
str Time-of-day string.
Returns
Duration since midnight in microseconds.
Exceptions
std::invalid_argument if str is empty, malformed, or out of range.
Definition at line 370 of file proto_type_converters.hpp.
Referenced by optional_string_to_time().
string_to_timestamp()
auto muscovite::grpc::string_to_timestamp (std::string_view str) -> std::chrono::system_clock::time_point inline nodiscard
Parse protobuf string (ISO 8601) to std::chrono::system_clock::time_point.
Parameters
str Timestamp string (e.g. "2024-12-25T10:30:45Z").
Returns
Parsed time point in UTC.
Exceptions
std::invalid_argument if str is empty or malformed.
Definition at line 286 of file proto_type_converters.hpp.
Referenced by optional_string_to_timestamp().
string_to_uuid()
auto muscovite::grpc::string_to_uuid (std::string_view str) -> boost::uuids::uuid inline nodiscard
Convert string to boost::uuids::uuid.
Convert protobuf string UUID to boost::uuids::uuid.
Parameters
s String representation of a UUID
Returns
Parsed UUID
Exceptions
std::invalid_argument if the string is not a valid UUID
Parameters
str Non-empty UUID string in canonical form (e.g. "550e8400-e29b-41d4-a716-446655440000").
Returns
Parsed UUID value.
Exceptions
std::invalid_argument if str is empty or not a valid UUID.
Definition at line 55 of file proto_converters.hpp.
Referenced by optional_string_to_uuid().
time_to_string()
auto muscovite::grpc::time_to_string (const std::chrono::microseconds & time) -> std::string inline nodiscard
Convert std::chrono::microseconds (time of day) to HH:MM:SS[.ffffff] string.
Parameters
time Duration since midnight.
Returns
Formatted time string (fractional part omitted if zero).
Definition at line 419 of file proto_type_converters.hpp.
Referenced by optional_time_to_string().
timestamp_to_iso8601()
auto muscovite::grpc::timestamp_to_iso8601 (const std::chrono::system_clock::time_point & ts) -> std::string inline nodiscard
Convert system_clock::time_point to ISO 8601 UTC string.
Parameters
ts The time point to convert
Returns
ISO 8601 formatted string (YYYY-MM-DDTHH:MM:SSZ)
Definition at line 94 of file proto_converters.hpp.
timestamp_to_string()
auto muscovite::grpc::timestamp_to_string (const std::chrono::system_clock::time_point & ts) -> std::string inline nodiscard
Convert std::chrono::system_clock::time_point to ISO 8601 string.
Parameters
ts The time point to serialize (UTC).
Returns
String in "YYYY-MM-DDThh:mm:ssZ" format.
Definition at line 331 of file proto_type_converters.hpp.
Referenced by optional_timestamp_to_string().
to_proto() [1/6]
void muscovite::grpc::to_proto (const boost::uuids::uuid & src, proto::UUID * dst)
Convert boost::uuid to proto UUID.
Definition at line 26 of file type_mapping.cpp.
Referenced by decimal_to_proto(), and to_proto_optional().
to_proto() [2/6]
void muscovite::grpc::to_proto (const Decimal & src, proto::Decimal * dst)
Convert Decimal to proto Decimal.
Definition at line 30 of file type_mapping.cpp.
to_proto() [3/6]
void muscovite::grpc::to_proto (const std::chrono::microseconds & src, proto::Interval * dst)
Convert chrono microseconds to proto Interval.
Definition at line 58 of file type_mapping.cpp.
to_proto() [4/6]
void muscovite::grpc::to_proto (const std::chrono::microseconds & src, proto::TimeOfDay * dst)
Convert chrono microseconds to proto TimeOfDay Accepts microseconds since midnight for DBA compatibility
Definition at line 49 of file type_mapping.cpp.
to_proto() [5/6]
void muscovite::grpc::to_proto (const std::chrono::system_clock::time_point & src, proto::Timestamp * dst)
Convert chrono time_point to proto Timestamp.
Definition at line 34 of file type_mapping.cpp.
to_proto() [6/6]
void muscovite::grpc::to_proto (const std::chrono::year_month_day & src, proto::Date * dst)
Convert chrono year_month_day to proto Date.
Definition at line 43 of file type_mapping.cpp.
to_proto_optional()
template<typename T, typename Proto> void muscovite::grpc::to_proto_optional (const std::optional< T > & src, Proto * dst)
Convert optional value to proto (sets field if present).
Definition at line 135 of file type_mapping.hpp.
References to_proto().
uuid_from_string()
auto muscovite::grpc::uuid_from_string (const std::string & s) -> boost::uuids::uuid nodiscard
Convert UUID string to boost::uuid (with validation).
Definition at line 238 of file type_mapping.cpp.
uuid_to_string()
auto muscovite::grpc::uuid_to_string (const boost::uuids::uuid & id) -> std::string inline nodiscard noexcept
Convert boost::uuids::uuid to string representation.
Convert boost::uuid to string.
Convert boost::uuids::uuid to protobuf string UUID.
Parameters
id The UUID to convert
Returns
String representation of the UUID (lowercase hex with hyphens)
Parameters
id The UUID to serialize.
Returns
Canonical string representation.
Definition at line 46 of file proto_converters.hpp.
Referenced by optional_uuid_to_string().
wkt_to_spatial() [1/3]
void muscovite::grpc::wkt_to_spatial (const std::string & wkt, proto::LineString * dst)
Convert WKT string to proto LineString Parses: "LINESTRING(lon1 lat1, lon2 lat2, ...)"
Definition at line 164 of file type_mapping.cpp.
wkt_to_spatial() [2/3]
void muscovite::grpc::wkt_to_spatial (const std::string & wkt, proto::Point * dst)
Convert WKT string to proto Point Parses: "POINT(lon lat)" or "POINT(lon lat srid)"
Definition at line 146 of file type_mapping.cpp.
wkt_to_spatial() [3/3]
void muscovite::grpc::wkt_to_spatial (const std::string & wkt, proto::Polygon * dst)
Convert WKT string to proto Polygon Parses: "POLYGON((lon1 lat1, lon2 lat2, ..., lon1 lat1))"
Definition at line 199 of file type_mapping.cpp.