Muscovite C++ Framework: framework/dba/include/muscovite/dba/nats/nats_connection.hpp File Reference
nats_connection.hpp File Reference
RAII wrapper for cnats natsConnection handle.
#include <memory>
#include <nats/nats.h>
Classes
struct JsCtxDeleter
Custom deleter for jsCtx (JetStream context) handles.
struct muscovite::dba::NatsConnectionDeleter
Custom deleter for natsConnection handles.
struct NatsOptionsDeleter
Custom deleter for natsOptions handles.
Typedefs
using JsCtxPtr = std::unique_ptr<jsCtx, JsCtxDeleter>
RAII wrapper for jsCtx* (move-only).
using NatsConnectionPtr = std::unique_ptr<natsConnection, NatsConnectionDeleter>
using NatsOptionsPtr = std::unique_ptr<natsOptions, NatsOptionsDeleter>
RAII wrapper for natsOptions* (move-only).
Functions
auto make_js_context (natsConnection *conn, jsOptions *opts=nullptr) -> std::pair< natsStatus, JsCtxPtr >
Create a JetStream context from an existing connection.
auto make_nats_connection (natsOptions *opts) -> std::pair< natsStatus, NatsConnectionPtr >
Connect to a NATS server and return RAII-managed connection.
auto make_nats_options () -> std::pair< natsStatus, NatsOptionsPtr >
Create NATS options with RAII ownership.
Detailed Description
RAII wrapper for cnats natsConnection handle.
See also
FTR-208 — NATS RAII connection wrappers
CPP-PATTERNS.md §17 — RAII for all resources
Wraps the raw natsConnection* C handle in a std::unique_ptr with a custom deleter that calls natsConnection_Destroy() on scope exit. Move-only (deleted copy). Use release() when the C API needs to take ownership (e.g., callback registrations that outlive the wrapper).
Definition in file nats_connection.hpp.
Typedef Documentation
JsCtxPtr
using JsCtxPtr = std::unique_ptr<jsCtx, JsCtxDeleter>
RAII wrapper for jsCtx* (move-only).
Definition at line 69 of file nats_connection.hpp.
NatsConnectionPtr
using NatsConnectionPtr = std::unique_ptr<natsConnection, NatsConnectionDeleter>
Definition at line 45 of file nats_connection.hpp.
NatsOptionsPtr
using NatsOptionsPtr = std::unique_ptr<natsOptions, NatsOptionsDeleter>
RAII wrapper for natsOptions* (move-only).
Definition at line 57 of file nats_connection.hpp.
Function Documentation
make_js_context()
auto make_js_context (natsConnection * conn, jsOptions * opts = nullptr) -> std::pair< natsStatus, JsCtxPtr > inline nodiscard
Create a JetStream context from an existing connection.
Parameters
conn Active NATS connection (non-owning)
opts JetStream options (may be nullptr for defaults)
Returns
{status, context} pair; context is null on failure
Definition at line 100 of file nats_connection.hpp.
Referenced by muscovite::dba::NatsMessageBroker::connect(), and muscovite::dba::NatsEventConsumer::start().
make_nats_connection()
auto make_nats_connection (natsOptions * opts) -> std::pair< natsStatus, NatsConnectionPtr > inline nodiscard
Connect to a NATS server and return RAII-managed connection.
Parameters
opts NATS options (may be nullptr for defaults)
Returns
{status, connection} pair; connection is null on failure
Definition at line 88 of file nats_connection.hpp.
Referenced by muscovite::dba::NatsMessageBroker::connect(), and muscovite::dba::NatsEventConsumer::start().
make_nats_options()
auto make_nats_options () -> std::pair< natsStatus, NatsOptionsPtr > inline nodiscard
Create NATS options with RAII ownership.
Returns
{status, options} pair; options is null on failure
Definition at line 77 of file nats_connection.hpp.
Referenced by muscovite::dba::NatsEventConsumer::start().