Muscovite C++ Framework: muscovite::dba::Page< T > Struct Template Reference
muscovite::dba::Page< T > Struct Template Reference
A page of results with metadata.
#include <pagination.hpp>
Public Member Functions
constexpr auto begin () const noexcept
constexpr auto begin () noexcept
constexpr auto cbegin () const noexcept
constexpr auto cend () const noexcept
constexpr auto empty () const noexcept -> bool
Check if page is empty.
constexpr auto end () const noexcept
constexpr auto end () noexcept
constexpr auto has_content () const noexcept -> bool
Check if page has content.
constexpr auto has_next () const noexcept -> bool
Check if there's a next page.
constexpr auto has_previous () const noexcept -> bool
Check if there's a previous page.
constexpr auto is_first () const noexcept -> bool
Check if this is the first page.
constexpr auto is_last () const noexcept -> bool
Check if this is the last page.
constexpr auto number_of_elements () const noexcept -> std::size_t
Number of elements on this page.
Public Attributes
std::vector< T > content
Items on this page.
std::size_t page_number
Current page (0-based).
std::size_t page_size
Requested page size.
std::size_t total_elements
Total items across all pages.
std::size_t total_pages
Total number of pages.
Detailed Description
template<typename T>
struct muscovite::dba::Page< T >
A page of results with metadata.
Definition at line 51 of file pagination.hpp.
Member Function Documentation
begin() [1/2]
template<typename T> auto muscovite::dba::Page< T >::begin () const inline nodiscard constexpr noexcept
Definition at line 84 of file pagination.hpp.
begin() [2/2]
template<typename T> auto muscovite::dba::Page< T >::begin () inline nodiscard constexpr noexcept
Definition at line 82 of file pagination.hpp.
cbegin()
template<typename T> auto muscovite::dba::Page< T >::cbegin () const inline nodiscard constexpr noexcept
Definition at line 86 of file pagination.hpp.
cend()
template<typename T> auto muscovite::dba::Page< T >::cend () const inline nodiscard constexpr noexcept
Definition at line 87 of file pagination.hpp.
empty()
template<typename T> auto muscovite::dba::Page< T >::empty () const -> bool inline nodiscard constexpr noexcept
Check if page is empty.
Definition at line 79 of file pagination.hpp.
References content.
end() [1/2]
template<typename T> auto muscovite::dba::Page< T >::end () const inline nodiscard constexpr noexcept
Definition at line 85 of file pagination.hpp.
end() [2/2]
template<typename T> auto muscovite::dba::Page< T >::end () inline nodiscard constexpr noexcept
Definition at line 83 of file pagination.hpp.
has_content()
template<typename T> auto muscovite::dba::Page< T >::has_content () const -> bool inline nodiscard constexpr noexcept
Check if page has content.
Definition at line 76 of file pagination.hpp.
References content.
has_next()
template<typename T> auto muscovite::dba::Page< T >::has_next () const -> bool inline nodiscard constexpr noexcept
Check if there's a next page.
Definition at line 67 of file pagination.hpp.
References is_last().
has_previous()
template<typename T> auto muscovite::dba::Page< T >::has_previous () const -> bool inline nodiscard constexpr noexcept
Check if there's a previous page.
Definition at line 70 of file pagination.hpp.
References is_first().
is_first()
template<typename T> auto muscovite::dba::Page< T >::is_first () const -> bool inline nodiscard constexpr noexcept
Check if this is the first page.
Definition at line 59 of file pagination.hpp.
References page_number.
Referenced by has_previous().
is_last()
template<typename T> auto muscovite::dba::Page< T >::is_last () const -> bool inline nodiscard constexpr noexcept
Check if this is the last page.
Definition at line 62 of file pagination.hpp.
References page_number, and total_pages.
Referenced by has_next().
number_of_elements()
template<typename T> auto muscovite::dba::Page< T >::number_of_elements () const -> std::size_t inline nodiscard constexpr noexcept
Number of elements on this page.
Definition at line 73 of file pagination.hpp.
References content.
Member Data Documentation
content
template<typename T> std::vector<T> muscovite::dba::Page< T >::content
Items on this page.
Definition at line 52 of file pagination.hpp.
Referenced by empty(), has_content(), and number_of_elements().
page_number
template<typename T> std::size_t muscovite::dba::Page< T >::page_number
Current page (0-based).
Definition at line 53 of file pagination.hpp.
Referenced by is_first(), and is_last().
page_size
template<typename T> std::size_t muscovite::dba::Page< T >::page_size
Requested page size.
Definition at line 54 of file pagination.hpp.
total_elements
template<typename T> std::size_t muscovite::dba::Page< T >::total_elements
Total items across all pages.
Definition at line 55 of file pagination.hpp.
total_pages
template<typename T> std::size_t muscovite::dba::Page< T >::total_pages
Total number of pages.
Definition at line 56 of file pagination.hpp.
Referenced by is_last().
The documentation for this struct was generated from the following file:
framework/dba/include/muscovite/dba/pagination.hpp